/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type Transfer = {
  sender: Address;
  mint: Address;
  source: Address;
  destination: Address;
  amount: bigint;
};

export type TransferArgs = {
  sender: Address;
  mint: Address;
  source: Address;
  destination: Address;
  amount: number | bigint;
};

export function getTransferEncoder(): FixedSizeEncoder<TransferArgs> {
  return getStructEncoder([
    ["sender", getAddressEncoder()],
    ["mint", getAddressEncoder()],
    ["source", getAddressEncoder()],
    ["destination", getAddressEncoder()],
    ["amount", getU64Encoder()],
  ]);
}

export function getTransferDecoder(): FixedSizeDecoder<Transfer> {
  return getStructDecoder([
    ["sender", getAddressDecoder()],
    ["mint", getAddressDecoder()],
    ["source", getAddressDecoder()],
    ["destination", getAddressDecoder()],
    ["amount", getU64Decoder()],
  ]);
}

export function getTransferCodec(): FixedSizeCodec<TransferArgs, Transfer> {
  return combineCodec(getTransferEncoder(), getTransferDecoder());
}
