/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const PERMISSION_CONFIG_DISCRIMINATOR = new Uint8Array([1]);

export function getPermissionConfigDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 1).encode(
    PERMISSION_CONFIG_DISCRIMINATOR,
  );
}

export type PermissionConfig = {
  discriminator: ReadonlyUint8Array;
  bump: number;
  admin: Address;
  pendingAdmin: Address;
};

export type PermissionConfigArgs = {
  bump: number;
  admin: Address;
  pendingAdmin: Address;
};

/** Gets the encoder for {@link PermissionConfigArgs} account data. */
export function getPermissionConfigEncoder(): FixedSizeEncoder<PermissionConfigArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 1)],
      ["bump", getU8Encoder()],
      ["admin", getAddressEncoder()],
      ["pendingAdmin", getAddressEncoder()],
    ]),
    (value) => ({ ...value, discriminator: PERMISSION_CONFIG_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link PermissionConfig} account data. */
export function getPermissionConfigDecoder(): FixedSizeDecoder<PermissionConfig> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 1)],
    ["bump", getU8Decoder()],
    ["admin", getAddressDecoder()],
    ["pendingAdmin", getAddressDecoder()],
  ]);
}

/** Gets the codec for {@link PermissionConfig} account data. */
export function getPermissionConfigCodec(): FixedSizeCodec<
  PermissionConfigArgs,
  PermissionConfig
> {
  return combineCodec(
    getPermissionConfigEncoder(),
    getPermissionConfigDecoder(),
  );
}

export function decodePermissionConfig<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<PermissionConfig, TAddress>;
export function decodePermissionConfig<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<PermissionConfig, TAddress>;
export function decodePermissionConfig<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
):
  | Account<PermissionConfig, TAddress>
  | MaybeAccount<PermissionConfig, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getPermissionConfigDecoder(),
  );
}

export async function fetchPermissionConfig<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<PermissionConfig, TAddress>> {
  const maybeAccount = await fetchMaybePermissionConfig(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybePermissionConfig<
  TAddress extends string = string,
>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<PermissionConfig, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodePermissionConfig(maybeAccount);
}

export async function fetchAllPermissionConfig(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<PermissionConfig>[]> {
  const maybeAccounts = await fetchAllMaybePermissionConfig(
    rpc,
    addresses,
    config,
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybePermissionConfig(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<PermissionConfig>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) =>
    decodePermissionConfig(maybeAccount),
  );
}

export function getPermissionConfigSize(): number {
  return 66;
}
