/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const USER_PERMISSIONS_DISCRIMINATOR = new Uint8Array([2]);

export function getUserPermissionsDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 1).encode(
    USER_PERMISSIONS_DISCRIMINATOR,
  );
}

export type UserPermissions = {
  discriminator: ReadonlyUint8Array;
  bump: number;
  roles: ReadonlyUint8Array;
};

export type UserPermissionsArgs = { bump: number; roles: ReadonlyUint8Array };

/** Gets the encoder for {@link UserPermissionsArgs} account data. */
export function getUserPermissionsEncoder(): FixedSizeEncoder<UserPermissionsArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 1)],
      ["bump", getU8Encoder()],
      ["roles", fixEncoderSize(getBytesEncoder(), 32)],
    ]),
    (value) => ({ ...value, discriminator: USER_PERMISSIONS_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link UserPermissions} account data. */
export function getUserPermissionsDecoder(): FixedSizeDecoder<UserPermissions> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 1)],
    ["bump", getU8Decoder()],
    ["roles", fixDecoderSize(getBytesDecoder(), 32)],
  ]);
}

/** Gets the codec for {@link UserPermissions} account data. */
export function getUserPermissionsCodec(): FixedSizeCodec<
  UserPermissionsArgs,
  UserPermissions
> {
  return combineCodec(getUserPermissionsEncoder(), getUserPermissionsDecoder());
}

export function decodeUserPermissions<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<UserPermissions, TAddress>;
export function decodeUserPermissions<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<UserPermissions, TAddress>;
export function decodeUserPermissions<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
):
  | Account<UserPermissions, TAddress>
  | MaybeAccount<UserPermissions, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getUserPermissionsDecoder(),
  );
}

export async function fetchUserPermissions<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<UserPermissions, TAddress>> {
  const maybeAccount = await fetchMaybeUserPermissions(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeUserPermissions<
  TAddress extends string = string,
>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<UserPermissions, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeUserPermissions(maybeAccount);
}

export async function fetchAllUserPermissions(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<UserPermissions>[]> {
  const maybeAccounts = await fetchAllMaybeUserPermissions(
    rpc,
    addresses,
    config,
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeUserPermissions(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<UserPermissions>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) =>
    decodeUserPermissions(maybeAccount),
  );
}

export function getUserPermissionsSize(): number {
  return 34;
}
