/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { SPIKO_TRANSFER_HOOK_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const INIT_EXTRA_ACCOUNT_METAS_DISCRIMINATOR = new Uint8Array([0]);

export function getInitExtraAccountMetasDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 1).encode(
    INIT_EXTRA_ACCOUNT_METAS_DISCRIMINATOR,
  );
}

export type InitExtraAccountMetasInstruction<
  TProgram extends string = typeof SPIKO_TRANSFER_HOOK_PROGRAM_ADDRESS,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountExtraAccountMetaList extends string | AccountMeta<string> = string,
  TAccountMint extends string | AccountMeta<string> = string,
  TAccountTokenConfig extends string | AccountMeta<string> = string,
  TAccountSpikoTokenProgram extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? WritableSignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountExtraAccountMetaList extends string
        ? WritableAccount<TAccountExtraAccountMetaList>
        : TAccountExtraAccountMetaList,
      TAccountMint extends string
        ? ReadonlyAccount<TAccountMint>
        : TAccountMint,
      TAccountTokenConfig extends string
        ? ReadonlyAccount<TAccountTokenConfig>
        : TAccountTokenConfig,
      TAccountSpikoTokenProgram extends string
        ? ReadonlyAccount<TAccountSpikoTokenProgram>
        : TAccountSpikoTokenProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type InitExtraAccountMetasInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type InitExtraAccountMetasInstructionDataArgs = {};

export function getInitExtraAccountMetasInstructionDataEncoder(): FixedSizeEncoder<InitExtraAccountMetasInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 1)]]),
    (value) => ({
      ...value,
      discriminator: INIT_EXTRA_ACCOUNT_METAS_DISCRIMINATOR,
    }),
  );
}

export function getInitExtraAccountMetasInstructionDataDecoder(): FixedSizeDecoder<InitExtraAccountMetasInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 1)],
  ]);
}

export function getInitExtraAccountMetasInstructionDataCodec(): FixedSizeCodec<
  InitExtraAccountMetasInstructionDataArgs,
  InitExtraAccountMetasInstructionData
> {
  return combineCodec(
    getInitExtraAccountMetasInstructionDataEncoder(),
    getInitExtraAccountMetasInstructionDataDecoder(),
  );
}

export type InitExtraAccountMetasInput<
  TAccountAdmin extends string = string,
  TAccountExtraAccountMetaList extends string = string,
  TAccountMint extends string = string,
  TAccountTokenConfig extends string = string,
  TAccountSpikoTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** Admin / deployer (payer) */
  admin: TransactionSigner<TAccountAdmin>;
  /** ExtraAccountMetaList PDA. Seeds: ["extra-account-metas", mint] */
  extraAccountMetaList: Address<TAccountExtraAccountMetaList>;
  /** Token-2022 Mint */
  mint: Address<TAccountMint>;
  /** TokenConfig PDA (must be initialized, owned by spiko-token) */
  tokenConfig: Address<TAccountTokenConfig>;
  /** SpikoToken program */
  spikoTokenProgram: Address<TAccountSpikoTokenProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
};

export function getInitExtraAccountMetasInstruction<
  TAccountAdmin extends string,
  TAccountExtraAccountMetaList extends string,
  TAccountMint extends string,
  TAccountTokenConfig extends string,
  TAccountSpikoTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof SPIKO_TRANSFER_HOOK_PROGRAM_ADDRESS,
>(
  input: InitExtraAccountMetasInput<
    TAccountAdmin,
    TAccountExtraAccountMetaList,
    TAccountMint,
    TAccountTokenConfig,
    TAccountSpikoTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): InitExtraAccountMetasInstruction<
  TProgramAddress,
  TAccountAdmin,
  TAccountExtraAccountMetaList,
  TAccountMint,
  TAccountTokenConfig,
  TAccountSpikoTokenProgram,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? SPIKO_TRANSFER_HOOK_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    extraAccountMetaList: {
      value: input.extraAccountMetaList ?? null,
      isWritable: true,
    },
    mint: { value: input.mint ?? null, isWritable: false },
    tokenConfig: { value: input.tokenConfig ?? null, isWritable: false },
    spikoTokenProgram: {
      value: input.spikoTokenProgram ?? null,
      isWritable: false,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.admin),
      getAccountMeta(accounts.extraAccountMetaList),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.tokenConfig),
      getAccountMeta(accounts.spikoTokenProgram),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getInitExtraAccountMetasInstructionDataEncoder().encode({}),
    programAddress,
  } as InitExtraAccountMetasInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountExtraAccountMetaList,
    TAccountMint,
    TAccountTokenConfig,
    TAccountSpikoTokenProgram,
    TAccountSystemProgram
  >);
}

export type ParsedInitExtraAccountMetasInstruction<
  TProgram extends string = typeof SPIKO_TRANSFER_HOOK_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Admin / deployer (payer) */
    admin: TAccountMetas[0];
    /** ExtraAccountMetaList PDA. Seeds: ["extra-account-metas", mint] */
    extraAccountMetaList: TAccountMetas[1];
    /** Token-2022 Mint */
    mint: TAccountMetas[2];
    /** TokenConfig PDA (must be initialized, owned by spiko-token) */
    tokenConfig: TAccountMetas[3];
    /** SpikoToken program */
    spikoTokenProgram: TAccountMetas[4];
    systemProgram: TAccountMetas[5];
  };
  data: InitExtraAccountMetasInstructionData;
};

export function parseInitExtraAccountMetasInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedInitExtraAccountMetasInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 6) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      admin: getNextAccount(),
      extraAccountMetaList: getNextAccount(),
      mint: getNextAccount(),
      tokenConfig: getNextAccount(),
      spikoTokenProgram: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getInitExtraAccountMetasInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
