/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";
import { SPIKO_TRANSFER_HOOK_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const TRANSFER_HOOK_EXECUTE_DISCRIMINATOR = new Uint8Array([
  105, 37, 101, 197, 75, 251, 102, 26,
]);

export function getTransferHookExecuteDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    TRANSFER_HOOK_EXECUTE_DISCRIMINATOR,
  );
}

export type TransferHookExecuteInstruction<
  TProgram extends string = typeof SPIKO_TRANSFER_HOOK_PROGRAM_ADDRESS,
  TAccountSource extends string | AccountMeta<string> = string,
  TAccountMint extends string | AccountMeta<string> = string,
  TAccountDestination extends string | AccountMeta<string> = string,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountExtraAccountMetaList extends string | AccountMeta<string> = string,
  TAccountPermissionManagerProgram extends string | AccountMeta<string> =
    string,
  TAccountSpikoTokenProgram extends string | AccountMeta<string> = string,
  TAccountTokenConfig extends string | AccountMeta<string> = string,
  TAccountSenderPermissions extends string | AccountMeta<string> = string,
  TAccountRecipientPermissions extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSource extends string
        ? ReadonlyAccount<TAccountSource>
        : TAccountSource,
      TAccountMint extends string
        ? ReadonlyAccount<TAccountMint>
        : TAccountMint,
      TAccountDestination extends string
        ? ReadonlyAccount<TAccountDestination>
        : TAccountDestination,
      TAccountAuthority extends string
        ? ReadonlyAccount<TAccountAuthority>
        : TAccountAuthority,
      TAccountExtraAccountMetaList extends string
        ? ReadonlyAccount<TAccountExtraAccountMetaList>
        : TAccountExtraAccountMetaList,
      TAccountPermissionManagerProgram extends string
        ? ReadonlyAccount<TAccountPermissionManagerProgram>
        : TAccountPermissionManagerProgram,
      TAccountSpikoTokenProgram extends string
        ? ReadonlyAccount<TAccountSpikoTokenProgram>
        : TAccountSpikoTokenProgram,
      TAccountTokenConfig extends string
        ? ReadonlyAccount<TAccountTokenConfig>
        : TAccountTokenConfig,
      TAccountSenderPermissions extends string
        ? ReadonlyAccount<TAccountSenderPermissions>
        : TAccountSenderPermissions,
      TAccountRecipientPermissions extends string
        ? ReadonlyAccount<TAccountRecipientPermissions>
        : TAccountRecipientPermissions,
      ...TRemainingAccounts,
    ]
  >;

export type TransferHookExecuteInstructionData = {
  discriminator: ReadonlyUint8Array;
  amount: bigint;
};

export type TransferHookExecuteInstructionDataArgs = {
  amount: number | bigint;
};

export function getTransferHookExecuteInstructionDataEncoder(): FixedSizeEncoder<TransferHookExecuteInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["amount", getU64Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: TRANSFER_HOOK_EXECUTE_DISCRIMINATOR,
    }),
  );
}

export function getTransferHookExecuteInstructionDataDecoder(): FixedSizeDecoder<TransferHookExecuteInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["amount", getU64Decoder()],
  ]);
}

export function getTransferHookExecuteInstructionDataCodec(): FixedSizeCodec<
  TransferHookExecuteInstructionDataArgs,
  TransferHookExecuteInstructionData
> {
  return combineCodec(
    getTransferHookExecuteInstructionDataEncoder(),
    getTransferHookExecuteInstructionDataDecoder(),
  );
}

export type TransferHookExecuteInput<
  TAccountSource extends string = string,
  TAccountMint extends string = string,
  TAccountDestination extends string = string,
  TAccountAuthority extends string = string,
  TAccountExtraAccountMetaList extends string = string,
  TAccountPermissionManagerProgram extends string = string,
  TAccountSpikoTokenProgram extends string = string,
  TAccountTokenConfig extends string = string,
  TAccountSenderPermissions extends string = string,
  TAccountRecipientPermissions extends string = string,
> = {
  /** Source token account */
  source: Address<TAccountSource>;
  /** Token-2022 Mint */
  mint: Address<TAccountMint>;
  /** Destination token account */
  destination: Address<TAccountDestination>;
  /** Source owner / delegate */
  authority: Address<TAccountAuthority>;
  /** ExtraAccountMetaList PDA (owned by this program) */
  extraAccountMetaList: Address<TAccountExtraAccountMetaList>;
  /** PermissionManager program (extra account) */
  permissionManagerProgram: Address<TAccountPermissionManagerProgram>;
  /** SpikoToken program (extra account) */
  spikoTokenProgram: Address<TAccountSpikoTokenProgram>;
  /** TokenConfig PDA (extra account, derived from SpikoToken) */
  tokenConfig: Address<TAccountTokenConfig>;
  /** Sender's UserPermissions PDA (extra account) */
  senderPermissions: Address<TAccountSenderPermissions>;
  /** Recipient's UserPermissions PDA (extra account) */
  recipientPermissions: Address<TAccountRecipientPermissions>;
  amount: TransferHookExecuteInstructionDataArgs["amount"];
};

export function getTransferHookExecuteInstruction<
  TAccountSource extends string,
  TAccountMint extends string,
  TAccountDestination extends string,
  TAccountAuthority extends string,
  TAccountExtraAccountMetaList extends string,
  TAccountPermissionManagerProgram extends string,
  TAccountSpikoTokenProgram extends string,
  TAccountTokenConfig extends string,
  TAccountSenderPermissions extends string,
  TAccountRecipientPermissions extends string,
  TProgramAddress extends Address = typeof SPIKO_TRANSFER_HOOK_PROGRAM_ADDRESS,
>(
  input: TransferHookExecuteInput<
    TAccountSource,
    TAccountMint,
    TAccountDestination,
    TAccountAuthority,
    TAccountExtraAccountMetaList,
    TAccountPermissionManagerProgram,
    TAccountSpikoTokenProgram,
    TAccountTokenConfig,
    TAccountSenderPermissions,
    TAccountRecipientPermissions
  >,
  config?: { programAddress?: TProgramAddress },
): TransferHookExecuteInstruction<
  TProgramAddress,
  TAccountSource,
  TAccountMint,
  TAccountDestination,
  TAccountAuthority,
  TAccountExtraAccountMetaList,
  TAccountPermissionManagerProgram,
  TAccountSpikoTokenProgram,
  TAccountTokenConfig,
  TAccountSenderPermissions,
  TAccountRecipientPermissions
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? SPIKO_TRANSFER_HOOK_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    source: { value: input.source ?? null, isWritable: false },
    mint: { value: input.mint ?? null, isWritable: false },
    destination: { value: input.destination ?? null, isWritable: false },
    authority: { value: input.authority ?? null, isWritable: false },
    extraAccountMetaList: {
      value: input.extraAccountMetaList ?? null,
      isWritable: false,
    },
    permissionManagerProgram: {
      value: input.permissionManagerProgram ?? null,
      isWritable: false,
    },
    spikoTokenProgram: {
      value: input.spikoTokenProgram ?? null,
      isWritable: false,
    },
    tokenConfig: { value: input.tokenConfig ?? null, isWritable: false },
    senderPermissions: {
      value: input.senderPermissions ?? null,
      isWritable: false,
    },
    recipientPermissions: {
      value: input.recipientPermissions ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.source),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.destination),
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.extraAccountMetaList),
      getAccountMeta(accounts.permissionManagerProgram),
      getAccountMeta(accounts.spikoTokenProgram),
      getAccountMeta(accounts.tokenConfig),
      getAccountMeta(accounts.senderPermissions),
      getAccountMeta(accounts.recipientPermissions),
    ],
    data: getTransferHookExecuteInstructionDataEncoder().encode(
      args as TransferHookExecuteInstructionDataArgs,
    ),
    programAddress,
  } as TransferHookExecuteInstruction<
    TProgramAddress,
    TAccountSource,
    TAccountMint,
    TAccountDestination,
    TAccountAuthority,
    TAccountExtraAccountMetaList,
    TAccountPermissionManagerProgram,
    TAccountSpikoTokenProgram,
    TAccountTokenConfig,
    TAccountSenderPermissions,
    TAccountRecipientPermissions
  >);
}

export type ParsedTransferHookExecuteInstruction<
  TProgram extends string = typeof SPIKO_TRANSFER_HOOK_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Source token account */
    source: TAccountMetas[0];
    /** Token-2022 Mint */
    mint: TAccountMetas[1];
    /** Destination token account */
    destination: TAccountMetas[2];
    /** Source owner / delegate */
    authority: TAccountMetas[3];
    /** ExtraAccountMetaList PDA (owned by this program) */
    extraAccountMetaList: TAccountMetas[4];
    /** PermissionManager program (extra account) */
    permissionManagerProgram: TAccountMetas[5];
    /** SpikoToken program (extra account) */
    spikoTokenProgram: TAccountMetas[6];
    /** TokenConfig PDA (extra account, derived from SpikoToken) */
    tokenConfig: TAccountMetas[7];
    /** Sender's UserPermissions PDA (extra account) */
    senderPermissions: TAccountMetas[8];
    /** Recipient's UserPermissions PDA (extra account) */
    recipientPermissions: TAccountMetas[9];
  };
  data: TransferHookExecuteInstructionData;
};

export function parseTransferHookExecuteInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedTransferHookExecuteInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 10) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      source: getNextAccount(),
      mint: getNextAccount(),
      destination: getNextAccount(),
      authority: getNextAccount(),
      extraAccountMetaList: getNextAccount(),
      permissionManagerProgram: getNextAccount(),
      spikoTokenProgram: getNextAccount(),
      tokenConfig: getNextAccount(),
      senderPermissions: getNextAccount(),
      recipientPermissions: getNextAccount(),
    },
    data: getTransferHookExecuteInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
