/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertIsInstructionWithAccounts,
  containsBytes,
  fixEncoderSize,
  getBytesEncoder,
  type Address,
  type Instruction,
  type InstructionWithData,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  parseApproveMintInstruction,
  parseCancelMintInstruction,
  parseInitializeMinterInstruction,
  parseInitiateMintInstruction,
  parseSetDailyLimitInstruction,
  parseSetMaxDelayInstruction,
  type ParsedApproveMintInstruction,
  type ParsedCancelMintInstruction,
  type ParsedInitializeMinterInstruction,
  type ParsedInitiateMintInstruction,
  type ParsedSetDailyLimitInstruction,
  type ParsedSetMaxDelayInstruction,
} from "../instructions";

export const MINTER_PROGRAM_ADDRESS =
  "6jbcB2eNfm1qLXRFd9jJes9yYEUWYafJDjfZ1dobSQ9z" as Address<"6jbcB2eNfm1qLXRFd9jJes9yYEUWYafJDjfZ1dobSQ9z">;

export enum MinterAccount {
  MinterConfig,
  DailyLimit,
  MintOperation,
}

export function identifyMinterAccount(
  account: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): MinterAccount {
  const data = "data" in account ? account.data : account;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 1).encode(new Uint8Array([1])),
      0,
    )
  ) {
    return MinterAccount.MinterConfig;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 1).encode(new Uint8Array([2])),
      0,
    )
  ) {
    return MinterAccount.DailyLimit;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 1).encode(new Uint8Array([3])),
      0,
    )
  ) {
    return MinterAccount.MintOperation;
  }
  throw new Error(
    "The provided account could not be identified as a minter account.",
  );
}

export enum MinterInstruction {
  InitializeMinter,
  InitiateMint,
  ApproveMint,
  CancelMint,
  SetDailyLimit,
  SetMaxDelay,
}

export function identifyMinterInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): MinterInstruction {
  const data = "data" in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 1).encode(new Uint8Array([0])),
      0,
    )
  ) {
    return MinterInstruction.InitializeMinter;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 1).encode(new Uint8Array([1])),
      0,
    )
  ) {
    return MinterInstruction.InitiateMint;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 1).encode(new Uint8Array([2])),
      0,
    )
  ) {
    return MinterInstruction.ApproveMint;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 1).encode(new Uint8Array([3])),
      0,
    )
  ) {
    return MinterInstruction.CancelMint;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 1).encode(new Uint8Array([4])),
      0,
    )
  ) {
    return MinterInstruction.SetDailyLimit;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 1).encode(new Uint8Array([5])),
      0,
    )
  ) {
    return MinterInstruction.SetMaxDelay;
  }
  throw new Error(
    "The provided instruction could not be identified as a minter instruction.",
  );
}

export type ParsedMinterInstruction<
  TProgram extends string = "6jbcB2eNfm1qLXRFd9jJes9yYEUWYafJDjfZ1dobSQ9z",
> =
  | ({
      instructionType: MinterInstruction.InitializeMinter;
    } & ParsedInitializeMinterInstruction<TProgram>)
  | ({
      instructionType: MinterInstruction.InitiateMint;
    } & ParsedInitiateMintInstruction<TProgram>)
  | ({
      instructionType: MinterInstruction.ApproveMint;
    } & ParsedApproveMintInstruction<TProgram>)
  | ({
      instructionType: MinterInstruction.CancelMint;
    } & ParsedCancelMintInstruction<TProgram>)
  | ({
      instructionType: MinterInstruction.SetDailyLimit;
    } & ParsedSetDailyLimitInstruction<TProgram>)
  | ({
      instructionType: MinterInstruction.SetMaxDelay;
    } & ParsedSetMaxDelayInstruction<TProgram>);

export function parseMinterInstruction<TProgram extends string>(
  instruction: Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array>,
): ParsedMinterInstruction<TProgram> {
  const instructionType = identifyMinterInstruction(instruction);
  switch (instructionType) {
    case MinterInstruction.InitializeMinter: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: MinterInstruction.InitializeMinter,
        ...parseInitializeMinterInstruction(instruction),
      };
    }
    case MinterInstruction.InitiateMint: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: MinterInstruction.InitiateMint,
        ...parseInitiateMintInstruction(instruction),
      };
    }
    case MinterInstruction.ApproveMint: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: MinterInstruction.ApproveMint,
        ...parseApproveMintInstruction(instruction),
      };
    }
    case MinterInstruction.CancelMint: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: MinterInstruction.CancelMint,
        ...parseCancelMintInstruction(instruction),
      };
    }
    case MinterInstruction.SetDailyLimit: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: MinterInstruction.SetDailyLimit,
        ...parseSetDailyLimitInstruction(instruction),
      };
    }
    case MinterInstruction.SetMaxDelay: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: MinterInstruction.SetMaxDelay,
        ...parseSetMaxDelayInstruction(instruction),
      };
    }
    default:
      throw new Error(
        `Unrecognized instruction type: ${instructionType as string}`,
      );
  }
}
