/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import { MINTER_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const CANCEL_MINT_DISCRIMINATOR = new Uint8Array([3]);

export function getCancelMintDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 1).encode(CANCEL_MINT_DISCRIMINATOR);
}

export type CancelMintInstruction<
  TProgram extends string = typeof MINTER_PROGRAM_ADDRESS,
  TAccountCaller extends string | AccountMeta<string> = string,
  TAccountMinterConfig extends string | AccountMeta<string> = string,
  TAccountMintOperation extends string | AccountMeta<string> = string,
  TAccountCallerPermissions extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountCaller extends string
        ? ReadonlySignerAccount<TAccountCaller> &
            AccountSignerMeta<TAccountCaller>
        : TAccountCaller,
      TAccountMinterConfig extends string
        ? ReadonlyAccount<TAccountMinterConfig>
        : TAccountMinterConfig,
      TAccountMintOperation extends string
        ? WritableAccount<TAccountMintOperation>
        : TAccountMintOperation,
      TAccountCallerPermissions extends string
        ? ReadonlyAccount<TAccountCallerPermissions>
        : TAccountCallerPermissions,
      ...TRemainingAccounts,
    ]
  >;

export type CancelMintInstructionData = {
  discriminator: ReadonlyUint8Array;
  user: Address;
  tokenMintArg: Address;
  amount: bigint;
  salt: bigint;
};

export type CancelMintInstructionDataArgs = {
  user: Address;
  tokenMintArg: Address;
  amount: number | bigint;
  salt: number | bigint;
};

export function getCancelMintInstructionDataEncoder(): FixedSizeEncoder<CancelMintInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 1)],
      ["user", getAddressEncoder()],
      ["tokenMintArg", getAddressEncoder()],
      ["amount", getU64Encoder()],
      ["salt", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: CANCEL_MINT_DISCRIMINATOR }),
  );
}

export function getCancelMintInstructionDataDecoder(): FixedSizeDecoder<CancelMintInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 1)],
    ["user", getAddressDecoder()],
    ["tokenMintArg", getAddressDecoder()],
    ["amount", getU64Decoder()],
    ["salt", getU64Decoder()],
  ]);
}

export function getCancelMintInstructionDataCodec(): FixedSizeCodec<
  CancelMintInstructionDataArgs,
  CancelMintInstructionData
> {
  return combineCodec(
    getCancelMintInstructionDataEncoder(),
    getCancelMintInstructionDataDecoder(),
  );
}

export type CancelMintInput<
  TAccountCaller extends string = string,
  TAccountMinterConfig extends string = string,
  TAccountMintOperation extends string = string,
  TAccountCallerPermissions extends string = string,
> = {
  /** Caller (must have ROLE_MINT_APPROVER) */
  caller: TransactionSigner<TAccountCaller>;
  /** MinterConfig PDA */
  minterConfig: Address<TAccountMinterConfig>;
  /** MintOperation PDA */
  mintOperation: Address<TAccountMintOperation>;
  /** Caller's UserPermissions PDA (from permission_manager) */
  callerPermissions: Address<TAccountCallerPermissions>;
  user: CancelMintInstructionDataArgs["user"];
  tokenMintArg: CancelMintInstructionDataArgs["tokenMintArg"];
  amount: CancelMintInstructionDataArgs["amount"];
  salt: CancelMintInstructionDataArgs["salt"];
};

export function getCancelMintInstruction<
  TAccountCaller extends string,
  TAccountMinterConfig extends string,
  TAccountMintOperation extends string,
  TAccountCallerPermissions extends string,
  TProgramAddress extends Address = typeof MINTER_PROGRAM_ADDRESS,
>(
  input: CancelMintInput<
    TAccountCaller,
    TAccountMinterConfig,
    TAccountMintOperation,
    TAccountCallerPermissions
  >,
  config?: { programAddress?: TProgramAddress },
): CancelMintInstruction<
  TProgramAddress,
  TAccountCaller,
  TAccountMinterConfig,
  TAccountMintOperation,
  TAccountCallerPermissions
> {
  // Program address.
  const programAddress = config?.programAddress ?? MINTER_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    caller: { value: input.caller ?? null, isWritable: false },
    minterConfig: { value: input.minterConfig ?? null, isWritable: false },
    mintOperation: { value: input.mintOperation ?? null, isWritable: true },
    callerPermissions: {
      value: input.callerPermissions ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.caller),
      getAccountMeta(accounts.minterConfig),
      getAccountMeta(accounts.mintOperation),
      getAccountMeta(accounts.callerPermissions),
    ],
    data: getCancelMintInstructionDataEncoder().encode(
      args as CancelMintInstructionDataArgs,
    ),
    programAddress,
  } as CancelMintInstruction<
    TProgramAddress,
    TAccountCaller,
    TAccountMinterConfig,
    TAccountMintOperation,
    TAccountCallerPermissions
  >);
}

export type ParsedCancelMintInstruction<
  TProgram extends string = typeof MINTER_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Caller (must have ROLE_MINT_APPROVER) */
    caller: TAccountMetas[0];
    /** MinterConfig PDA */
    minterConfig: TAccountMetas[1];
    /** MintOperation PDA */
    mintOperation: TAccountMetas[2];
    /** Caller's UserPermissions PDA (from permission_manager) */
    callerPermissions: TAccountMetas[3];
  };
  data: CancelMintInstructionData;
};

export function parseCancelMintInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedCancelMintInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      caller: getNextAccount(),
      minterConfig: getNextAccount(),
      mintOperation: getNextAccount(),
      callerPermissions: getNextAccount(),
    },
    data: getCancelMintInstructionDataDecoder().decode(instruction.data),
  };
}
