/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import { MINTER_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const INITIATE_MINT_DISCRIMINATOR = new Uint8Array([1]);

export function getInitiateMintDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 1).encode(
    INITIATE_MINT_DISCRIMINATOR,
  );
}

export type InitiateMintInstruction<
  TProgram extends string = typeof MINTER_PROGRAM_ADDRESS,
  TAccountCaller extends string | AccountMeta<string> = string,
  TAccountMinterConfig extends string | AccountMeta<string> = string,
  TAccountDailyLimit extends string | AccountMeta<string> = string,
  TAccountMintOperation extends string | AccountMeta<string> = string,
  TAccountCallerPermissions extends string | AccountMeta<string> = string,
  TAccountSpikoTokenProgram extends string | AccountMeta<string> = string,
  TAccountTokenConfig extends string | AccountMeta<string> = string,
  TAccountTokenMint extends string | AccountMeta<string> = string,
  TAccountRecipientTokenAccount extends string | AccountMeta<string> = string,
  TAccountMintAuthority extends string | AccountMeta<string> = string,
  TAccountMinterUserPermissions extends string | AccountMeta<string> = string,
  TAccountRecipientPermissions extends string | AccountMeta<string> = string,
  TAccountToken2022Program extends string | AccountMeta<string> =
    "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb",
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountCaller extends string
        ? ReadonlySignerAccount<TAccountCaller> &
            AccountSignerMeta<TAccountCaller>
        : TAccountCaller,
      TAccountMinterConfig extends string
        ? WritableAccount<TAccountMinterConfig>
        : TAccountMinterConfig,
      TAccountDailyLimit extends string
        ? WritableAccount<TAccountDailyLimit>
        : TAccountDailyLimit,
      TAccountMintOperation extends string
        ? WritableAccount<TAccountMintOperation>
        : TAccountMintOperation,
      TAccountCallerPermissions extends string
        ? ReadonlyAccount<TAccountCallerPermissions>
        : TAccountCallerPermissions,
      TAccountSpikoTokenProgram extends string
        ? ReadonlyAccount<TAccountSpikoTokenProgram>
        : TAccountSpikoTokenProgram,
      TAccountTokenConfig extends string
        ? ReadonlyAccount<TAccountTokenConfig>
        : TAccountTokenConfig,
      TAccountTokenMint extends string
        ? WritableAccount<TAccountTokenMint>
        : TAccountTokenMint,
      TAccountRecipientTokenAccount extends string
        ? WritableAccount<TAccountRecipientTokenAccount>
        : TAccountRecipientTokenAccount,
      TAccountMintAuthority extends string
        ? ReadonlyAccount<TAccountMintAuthority>
        : TAccountMintAuthority,
      TAccountMinterUserPermissions extends string
        ? ReadonlyAccount<TAccountMinterUserPermissions>
        : TAccountMinterUserPermissions,
      TAccountRecipientPermissions extends string
        ? ReadonlyAccount<TAccountRecipientPermissions>
        : TAccountRecipientPermissions,
      TAccountToken2022Program extends string
        ? ReadonlyAccount<TAccountToken2022Program>
        : TAccountToken2022Program,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type InitiateMintInstructionData = {
  discriminator: ReadonlyUint8Array;
  user: Address;
  amount: bigint;
  salt: bigint;
};

export type InitiateMintInstructionDataArgs = {
  user: Address;
  amount: number | bigint;
  salt: number | bigint;
};

export function getInitiateMintInstructionDataEncoder(): FixedSizeEncoder<InitiateMintInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 1)],
      ["user", getAddressEncoder()],
      ["amount", getU64Encoder()],
      ["salt", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: INITIATE_MINT_DISCRIMINATOR }),
  );
}

export function getInitiateMintInstructionDataDecoder(): FixedSizeDecoder<InitiateMintInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 1)],
    ["user", getAddressDecoder()],
    ["amount", getU64Decoder()],
    ["salt", getU64Decoder()],
  ]);
}

export function getInitiateMintInstructionDataCodec(): FixedSizeCodec<
  InitiateMintInstructionDataArgs,
  InitiateMintInstructionData
> {
  return combineCodec(
    getInitiateMintInstructionDataEncoder(),
    getInitiateMintInstructionDataDecoder(),
  );
}

export type InitiateMintInput<
  TAccountCaller extends string = string,
  TAccountMinterConfig extends string = string,
  TAccountDailyLimit extends string = string,
  TAccountMintOperation extends string = string,
  TAccountCallerPermissions extends string = string,
  TAccountSpikoTokenProgram extends string = string,
  TAccountTokenConfig extends string = string,
  TAccountTokenMint extends string = string,
  TAccountRecipientTokenAccount extends string = string,
  TAccountMintAuthority extends string = string,
  TAccountMinterUserPermissions extends string = string,
  TAccountRecipientPermissions extends string = string,
  TAccountToken2022Program extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** Caller (must have ROLE_MINT_INITIATOR) */
  caller: TransactionSigner<TAccountCaller>;
  /** MinterConfig PDA */
  minterConfig: Address<TAccountMinterConfig>;
  /** DailyLimit PDA for this token. Seeds: ["daily_limit", mint] */
  dailyLimit: Address<TAccountDailyLimit>;
  /** MintOperation PDA. Seeds: ["mint_op", operation_id] */
  mintOperation: Address<TAccountMintOperation>;
  /** Caller's UserPermissions PDA (from permission_manager) */
  callerPermissions: Address<TAccountCallerPermissions>;
  /** Spiko Token program (for CPI if immediate mint) */
  spikoTokenProgram: Address<TAccountSpikoTokenProgram>;
  /** TokenConfig PDA (on spiko-token, for CPI) */
  tokenConfig: Address<TAccountTokenConfig>;
  /** Token-2022 Mint (for CPI) */
  tokenMint: Address<TAccountTokenMint>;
  /** Recipient's token account (for CPI) */
  recipientTokenAccount: Address<TAccountRecipientTokenAccount>;
  /** Mint authority PDA (spiko-token, for CPI) */
  mintAuthority: Address<TAccountMintAuthority>;
  /** Minter's UserPermissions PDA (MinterConfig has ROLE_MINTER) */
  minterUserPermissions: Address<TAccountMinterUserPermissions>;
  /** Recipient's UserPermissions PDA (whitelist check, for CPI) */
  recipientPermissions: Address<TAccountRecipientPermissions>;
  token2022Program?: Address<TAccountToken2022Program>;
  systemProgram?: Address<TAccountSystemProgram>;
  user: InitiateMintInstructionDataArgs["user"];
  amount: InitiateMintInstructionDataArgs["amount"];
  salt: InitiateMintInstructionDataArgs["salt"];
};

export function getInitiateMintInstruction<
  TAccountCaller extends string,
  TAccountMinterConfig extends string,
  TAccountDailyLimit extends string,
  TAccountMintOperation extends string,
  TAccountCallerPermissions extends string,
  TAccountSpikoTokenProgram extends string,
  TAccountTokenConfig extends string,
  TAccountTokenMint extends string,
  TAccountRecipientTokenAccount extends string,
  TAccountMintAuthority extends string,
  TAccountMinterUserPermissions extends string,
  TAccountRecipientPermissions extends string,
  TAccountToken2022Program extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof MINTER_PROGRAM_ADDRESS,
>(
  input: InitiateMintInput<
    TAccountCaller,
    TAccountMinterConfig,
    TAccountDailyLimit,
    TAccountMintOperation,
    TAccountCallerPermissions,
    TAccountSpikoTokenProgram,
    TAccountTokenConfig,
    TAccountTokenMint,
    TAccountRecipientTokenAccount,
    TAccountMintAuthority,
    TAccountMinterUserPermissions,
    TAccountRecipientPermissions,
    TAccountToken2022Program,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): InitiateMintInstruction<
  TProgramAddress,
  TAccountCaller,
  TAccountMinterConfig,
  TAccountDailyLimit,
  TAccountMintOperation,
  TAccountCallerPermissions,
  TAccountSpikoTokenProgram,
  TAccountTokenConfig,
  TAccountTokenMint,
  TAccountRecipientTokenAccount,
  TAccountMintAuthority,
  TAccountMinterUserPermissions,
  TAccountRecipientPermissions,
  TAccountToken2022Program,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? MINTER_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    caller: { value: input.caller ?? null, isWritable: false },
    minterConfig: { value: input.minterConfig ?? null, isWritable: true },
    dailyLimit: { value: input.dailyLimit ?? null, isWritable: true },
    mintOperation: { value: input.mintOperation ?? null, isWritable: true },
    callerPermissions: {
      value: input.callerPermissions ?? null,
      isWritable: false,
    },
    spikoTokenProgram: {
      value: input.spikoTokenProgram ?? null,
      isWritable: false,
    },
    tokenConfig: { value: input.tokenConfig ?? null, isWritable: false },
    tokenMint: { value: input.tokenMint ?? null, isWritable: true },
    recipientTokenAccount: {
      value: input.recipientTokenAccount ?? null,
      isWritable: true,
    },
    mintAuthority: { value: input.mintAuthority ?? null, isWritable: false },
    minterUserPermissions: {
      value: input.minterUserPermissions ?? null,
      isWritable: false,
    },
    recipientPermissions: {
      value: input.recipientPermissions ?? null,
      isWritable: false,
    },
    token2022Program: {
      value: input.token2022Program ?? null,
      isWritable: false,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.token2022Program.value) {
    accounts.token2022Program.value =
      "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb" as Address<"TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.caller),
      getAccountMeta(accounts.minterConfig),
      getAccountMeta(accounts.dailyLimit),
      getAccountMeta(accounts.mintOperation),
      getAccountMeta(accounts.callerPermissions),
      getAccountMeta(accounts.spikoTokenProgram),
      getAccountMeta(accounts.tokenConfig),
      getAccountMeta(accounts.tokenMint),
      getAccountMeta(accounts.recipientTokenAccount),
      getAccountMeta(accounts.mintAuthority),
      getAccountMeta(accounts.minterUserPermissions),
      getAccountMeta(accounts.recipientPermissions),
      getAccountMeta(accounts.token2022Program),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getInitiateMintInstructionDataEncoder().encode(
      args as InitiateMintInstructionDataArgs,
    ),
    programAddress,
  } as InitiateMintInstruction<
    TProgramAddress,
    TAccountCaller,
    TAccountMinterConfig,
    TAccountDailyLimit,
    TAccountMintOperation,
    TAccountCallerPermissions,
    TAccountSpikoTokenProgram,
    TAccountTokenConfig,
    TAccountTokenMint,
    TAccountRecipientTokenAccount,
    TAccountMintAuthority,
    TAccountMinterUserPermissions,
    TAccountRecipientPermissions,
    TAccountToken2022Program,
    TAccountSystemProgram
  >);
}

export type ParsedInitiateMintInstruction<
  TProgram extends string = typeof MINTER_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Caller (must have ROLE_MINT_INITIATOR) */
    caller: TAccountMetas[0];
    /** MinterConfig PDA */
    minterConfig: TAccountMetas[1];
    /** DailyLimit PDA for this token. Seeds: ["daily_limit", mint] */
    dailyLimit: TAccountMetas[2];
    /** MintOperation PDA. Seeds: ["mint_op", operation_id] */
    mintOperation: TAccountMetas[3];
    /** Caller's UserPermissions PDA (from permission_manager) */
    callerPermissions: TAccountMetas[4];
    /** Spiko Token program (for CPI if immediate mint) */
    spikoTokenProgram: TAccountMetas[5];
    /** TokenConfig PDA (on spiko-token, for CPI) */
    tokenConfig: TAccountMetas[6];
    /** Token-2022 Mint (for CPI) */
    tokenMint: TAccountMetas[7];
    /** Recipient's token account (for CPI) */
    recipientTokenAccount: TAccountMetas[8];
    /** Mint authority PDA (spiko-token, for CPI) */
    mintAuthority: TAccountMetas[9];
    /** Minter's UserPermissions PDA (MinterConfig has ROLE_MINTER) */
    minterUserPermissions: TAccountMetas[10];
    /** Recipient's UserPermissions PDA (whitelist check, for CPI) */
    recipientPermissions: TAccountMetas[11];
    token2022Program: TAccountMetas[12];
    systemProgram: TAccountMetas[13];
  };
  data: InitiateMintInstructionData;
};

export function parseInitiateMintInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedInitiateMintInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 14) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      caller: getNextAccount(),
      minterConfig: getNextAccount(),
      dailyLimit: getNextAccount(),
      mintOperation: getNextAccount(),
      callerPermissions: getNextAccount(),
      spikoTokenProgram: getNextAccount(),
      tokenConfig: getNextAccount(),
      tokenMint: getNextAccount(),
      recipientTokenAccount: getNextAccount(),
      mintAuthority: getNextAccount(),
      minterUserPermissions: getNextAccount(),
      recipientPermissions: getNextAccount(),
      token2022Program: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getInitiateMintInstructionDataDecoder().decode(instruction.data),
  };
}
