/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { MINTER_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const INITIALIZE_MINTER_DISCRIMINATOR = new Uint8Array([0]);

export function getInitializeMinterDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 1).encode(
    INITIALIZE_MINTER_DISCRIMINATOR,
  );
}

export type InitializeMinterInstruction<
  TProgram extends string = typeof MINTER_PROGRAM_ADDRESS,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountMinterConfig extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? WritableSignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountMinterConfig extends string
        ? WritableAccount<TAccountMinterConfig>
        : TAccountMinterConfig,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type InitializeMinterInstructionData = {
  discriminator: ReadonlyUint8Array;
  maxDelay: bigint;
  permissionManager: Address;
};

export type InitializeMinterInstructionDataArgs = {
  maxDelay: number | bigint;
  permissionManager: Address;
};

export function getInitializeMinterInstructionDataEncoder(): FixedSizeEncoder<InitializeMinterInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 1)],
      ["maxDelay", getI64Encoder()],
      ["permissionManager", getAddressEncoder()],
    ]),
    (value) => ({ ...value, discriminator: INITIALIZE_MINTER_DISCRIMINATOR }),
  );
}

export function getInitializeMinterInstructionDataDecoder(): FixedSizeDecoder<InitializeMinterInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 1)],
    ["maxDelay", getI64Decoder()],
    ["permissionManager", getAddressDecoder()],
  ]);
}

export function getInitializeMinterInstructionDataCodec(): FixedSizeCodec<
  InitializeMinterInstructionDataArgs,
  InitializeMinterInstructionData
> {
  return combineCodec(
    getInitializeMinterInstructionDataEncoder(),
    getInitializeMinterInstructionDataDecoder(),
  );
}

export type InitializeMinterInput<
  TAccountAdmin extends string = string,
  TAccountMinterConfig extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** Admin / deployer (payer for PDA creation) */
  admin: TransactionSigner<TAccountAdmin>;
  /** MinterConfig PDA. Seeds: ["minter_config"] */
  minterConfig: Address<TAccountMinterConfig>;
  systemProgram?: Address<TAccountSystemProgram>;
  maxDelay: InitializeMinterInstructionDataArgs["maxDelay"];
  permissionManager: InitializeMinterInstructionDataArgs["permissionManager"];
};

export function getInitializeMinterInstruction<
  TAccountAdmin extends string,
  TAccountMinterConfig extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof MINTER_PROGRAM_ADDRESS,
>(
  input: InitializeMinterInput<
    TAccountAdmin,
    TAccountMinterConfig,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): InitializeMinterInstruction<
  TProgramAddress,
  TAccountAdmin,
  TAccountMinterConfig,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? MINTER_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    minterConfig: { value: input.minterConfig ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.admin),
      getAccountMeta(accounts.minterConfig),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getInitializeMinterInstructionDataEncoder().encode(
      args as InitializeMinterInstructionDataArgs,
    ),
    programAddress,
  } as InitializeMinterInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountMinterConfig,
    TAccountSystemProgram
  >);
}

export type ParsedInitializeMinterInstruction<
  TProgram extends string = typeof MINTER_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Admin / deployer (payer for PDA creation) */
    admin: TAccountMetas[0];
    /** MinterConfig PDA. Seeds: ["minter_config"] */
    minterConfig: TAccountMetas[1];
    systemProgram: TAccountMetas[2];
  };
  data: InitializeMinterInstructionData;
};

export function parseInitializeMinterInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedInitializeMinterInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      admin: getNextAccount(),
      minterConfig: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getInitializeMinterInstructionDataDecoder().decode(instruction.data),
  };
}
