/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { MINTER_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const SET_DAILY_LIMIT_DISCRIMINATOR = new Uint8Array([4]);

export function getSetDailyLimitDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 1).encode(
    SET_DAILY_LIMIT_DISCRIMINATOR,
  );
}

export type SetDailyLimitInstruction<
  TProgram extends string = typeof MINTER_PROGRAM_ADDRESS,
  TAccountCaller extends string | AccountMeta<string> = string,
  TAccountMinterConfig extends string | AccountMeta<string> = string,
  TAccountPermissionConfig extends string | AccountMeta<string> = string,
  TAccountDailyLimit extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountCaller extends string
        ? WritableSignerAccount<TAccountCaller> &
            AccountSignerMeta<TAccountCaller>
        : TAccountCaller,
      TAccountMinterConfig extends string
        ? ReadonlyAccount<TAccountMinterConfig>
        : TAccountMinterConfig,
      TAccountPermissionConfig extends string
        ? ReadonlyAccount<TAccountPermissionConfig>
        : TAccountPermissionConfig,
      TAccountDailyLimit extends string
        ? WritableAccount<TAccountDailyLimit>
        : TAccountDailyLimit,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type SetDailyLimitInstructionData = {
  discriminator: ReadonlyUint8Array;
  tokenMintArg: Address;
  limit: bigint;
};

export type SetDailyLimitInstructionDataArgs = {
  tokenMintArg: Address;
  limit: number | bigint;
};

export function getSetDailyLimitInstructionDataEncoder(): FixedSizeEncoder<SetDailyLimitInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 1)],
      ["tokenMintArg", getAddressEncoder()],
      ["limit", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: SET_DAILY_LIMIT_DISCRIMINATOR }),
  );
}

export function getSetDailyLimitInstructionDataDecoder(): FixedSizeDecoder<SetDailyLimitInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 1)],
    ["tokenMintArg", getAddressDecoder()],
    ["limit", getU64Decoder()],
  ]);
}

export function getSetDailyLimitInstructionDataCodec(): FixedSizeCodec<
  SetDailyLimitInstructionDataArgs,
  SetDailyLimitInstructionData
> {
  return combineCodec(
    getSetDailyLimitInstructionDataEncoder(),
    getSetDailyLimitInstructionDataDecoder(),
  );
}

export type SetDailyLimitInput<
  TAccountCaller extends string = string,
  TAccountMinterConfig extends string = string,
  TAccountPermissionConfig extends string = string,
  TAccountDailyLimit extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** Admin caller (payer if creating DailyLimit PDA) */
  caller: TransactionSigner<TAccountCaller>;
  /** MinterConfig PDA (to read permission_manager) */
  minterConfig: Address<TAccountMinterConfig>;
  /** PermissionConfig PDA (from permission_manager, for admin check) */
  permissionConfig: Address<TAccountPermissionConfig>;
  /** DailyLimit PDA for the token (created if needed). Seeds: ["daily_limit", mint] */
  dailyLimit: Address<TAccountDailyLimit>;
  systemProgram?: Address<TAccountSystemProgram>;
  tokenMintArg: SetDailyLimitInstructionDataArgs["tokenMintArg"];
  limit: SetDailyLimitInstructionDataArgs["limit"];
};

export function getSetDailyLimitInstruction<
  TAccountCaller extends string,
  TAccountMinterConfig extends string,
  TAccountPermissionConfig extends string,
  TAccountDailyLimit extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof MINTER_PROGRAM_ADDRESS,
>(
  input: SetDailyLimitInput<
    TAccountCaller,
    TAccountMinterConfig,
    TAccountPermissionConfig,
    TAccountDailyLimit,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): SetDailyLimitInstruction<
  TProgramAddress,
  TAccountCaller,
  TAccountMinterConfig,
  TAccountPermissionConfig,
  TAccountDailyLimit,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? MINTER_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    caller: { value: input.caller ?? null, isWritable: true },
    minterConfig: { value: input.minterConfig ?? null, isWritable: false },
    permissionConfig: {
      value: input.permissionConfig ?? null,
      isWritable: false,
    },
    dailyLimit: { value: input.dailyLimit ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.caller),
      getAccountMeta(accounts.minterConfig),
      getAccountMeta(accounts.permissionConfig),
      getAccountMeta(accounts.dailyLimit),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getSetDailyLimitInstructionDataEncoder().encode(
      args as SetDailyLimitInstructionDataArgs,
    ),
    programAddress,
  } as SetDailyLimitInstruction<
    TProgramAddress,
    TAccountCaller,
    TAccountMinterConfig,
    TAccountPermissionConfig,
    TAccountDailyLimit,
    TAccountSystemProgram
  >);
}

export type ParsedSetDailyLimitInstruction<
  TProgram extends string = typeof MINTER_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Admin caller (payer if creating DailyLimit PDA) */
    caller: TAccountMetas[0];
    /** MinterConfig PDA (to read permission_manager) */
    minterConfig: TAccountMetas[1];
    /** PermissionConfig PDA (from permission_manager, for admin check) */
    permissionConfig: TAccountMetas[2];
    /** DailyLimit PDA for the token (created if needed). Seeds: ["daily_limit", mint] */
    dailyLimit: TAccountMetas[3];
    systemProgram: TAccountMetas[4];
  };
  data: SetDailyLimitInstructionData;
};

export function parseSetDailyLimitInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedSetDailyLimitInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      caller: getNextAccount(),
      minterConfig: getNextAccount(),
      permissionConfig: getNextAccount(),
      dailyLimit: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getSetDailyLimitInstructionDataDecoder().decode(instruction.data),
  };
}
