/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import { MINTER_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const SET_MAX_DELAY_DISCRIMINATOR = new Uint8Array([5]);

export function getSetMaxDelayDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 1).encode(
    SET_MAX_DELAY_DISCRIMINATOR,
  );
}

export type SetMaxDelayInstruction<
  TProgram extends string = typeof MINTER_PROGRAM_ADDRESS,
  TAccountCaller extends string | AccountMeta<string> = string,
  TAccountMinterConfig extends string | AccountMeta<string> = string,
  TAccountPermissionConfig extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountCaller extends string
        ? ReadonlySignerAccount<TAccountCaller> &
            AccountSignerMeta<TAccountCaller>
        : TAccountCaller,
      TAccountMinterConfig extends string
        ? WritableAccount<TAccountMinterConfig>
        : TAccountMinterConfig,
      TAccountPermissionConfig extends string
        ? ReadonlyAccount<TAccountPermissionConfig>
        : TAccountPermissionConfig,
      ...TRemainingAccounts,
    ]
  >;

export type SetMaxDelayInstructionData = {
  discriminator: ReadonlyUint8Array;
  maxDelay: bigint;
};

export type SetMaxDelayInstructionDataArgs = { maxDelay: number | bigint };

export function getSetMaxDelayInstructionDataEncoder(): FixedSizeEncoder<SetMaxDelayInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 1)],
      ["maxDelay", getI64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: SET_MAX_DELAY_DISCRIMINATOR }),
  );
}

export function getSetMaxDelayInstructionDataDecoder(): FixedSizeDecoder<SetMaxDelayInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 1)],
    ["maxDelay", getI64Decoder()],
  ]);
}

export function getSetMaxDelayInstructionDataCodec(): FixedSizeCodec<
  SetMaxDelayInstructionDataArgs,
  SetMaxDelayInstructionData
> {
  return combineCodec(
    getSetMaxDelayInstructionDataEncoder(),
    getSetMaxDelayInstructionDataDecoder(),
  );
}

export type SetMaxDelayInput<
  TAccountCaller extends string = string,
  TAccountMinterConfig extends string = string,
  TAccountPermissionConfig extends string = string,
> = {
  /** Admin caller */
  caller: TransactionSigner<TAccountCaller>;
  /** MinterConfig PDA */
  minterConfig: Address<TAccountMinterConfig>;
  /** PermissionConfig PDA (from permission_manager, for admin check) */
  permissionConfig: Address<TAccountPermissionConfig>;
  maxDelay: SetMaxDelayInstructionDataArgs["maxDelay"];
};

export function getSetMaxDelayInstruction<
  TAccountCaller extends string,
  TAccountMinterConfig extends string,
  TAccountPermissionConfig extends string,
  TProgramAddress extends Address = typeof MINTER_PROGRAM_ADDRESS,
>(
  input: SetMaxDelayInput<
    TAccountCaller,
    TAccountMinterConfig,
    TAccountPermissionConfig
  >,
  config?: { programAddress?: TProgramAddress },
): SetMaxDelayInstruction<
  TProgramAddress,
  TAccountCaller,
  TAccountMinterConfig,
  TAccountPermissionConfig
> {
  // Program address.
  const programAddress = config?.programAddress ?? MINTER_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    caller: { value: input.caller ?? null, isWritable: false },
    minterConfig: { value: input.minterConfig ?? null, isWritable: true },
    permissionConfig: {
      value: input.permissionConfig ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.caller),
      getAccountMeta(accounts.minterConfig),
      getAccountMeta(accounts.permissionConfig),
    ],
    data: getSetMaxDelayInstructionDataEncoder().encode(
      args as SetMaxDelayInstructionDataArgs,
    ),
    programAddress,
  } as SetMaxDelayInstruction<
    TProgramAddress,
    TAccountCaller,
    TAccountMinterConfig,
    TAccountPermissionConfig
  >);
}

export type ParsedSetMaxDelayInstruction<
  TProgram extends string = typeof MINTER_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Admin caller */
    caller: TAccountMetas[0];
    /** MinterConfig PDA */
    minterConfig: TAccountMetas[1];
    /** PermissionConfig PDA (from permission_manager, for admin check) */
    permissionConfig: TAccountMetas[2];
  };
  data: SetMaxDelayInstructionData;
};

export function parseSetMaxDelayInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedSetMaxDelayInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      caller: getNextAccount(),
      minterConfig: getNextAccount(),
      permissionConfig: getNextAccount(),
    },
    data: getSetMaxDelayInstructionDataDecoder().decode(instruction.data),
  };
}
