[toolchain]
anchor_version = "1.0.2"
solana_version = "2.1.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
custodial_gatekeeper = "5Y7mJuJRdBFTXBrXG3rCUZTjRtNKhrRjCA3vKnVX2Zb6"
minter = "Hygpx48FpJyDjW1uW8fykwb94Jmak4CaWvihRREsJyFX"
redemption = "B3ustaVazAzqwbgkxARcsL9KKKaNKT6o6FFQyo4b4EBr"
transfer_hook = "Fzyd28cVXwzaqoU9bqU8hLpcYqhQQtSyJVaGCgcGFEjq"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "echo 'No tests configured yet'"

[hooks]
