[workspace]
resolver = "2"
members = ["programs/minter"]

[workspace.dependencies]
anchor-lang = { version = "1.0.2", features = ["init-if-needed"] }
anchor-spl = "1.0.2"
spl-token-2022-interface = "2.1.0"

[workspace.metadata.cli]
solana = "3.1.10"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
opt-level = 3
incremental = false
