[workspace]
resolver = "2"
members = [
    "programs/permission-manager",
    "programs/spiko-token",
    "programs/spiko-transfer-hook",
    "programs/minter",
    "programs/redemption",
    "programs/custodial-gatekeeper",
]

[workspace.dependencies]
anchor-lang = { version = "1.0.2", features = ["event-cpi"] }
anchor-spl = "1.0.2"
spl-transfer-hook-interface = "2.1.0"
spl-tlv-account-resolution = "0.11.1"
solana-sha256-hasher = "3"
litesvm = "0.11.0"
blake3 = "=1.5.5"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
opt-level = 3
incremental = false
