[workspace]
resolver = "2"
members = [
    "programs/permission-manager",
    "programs/spiko-token",
    "programs/spiko-transfer-hook",
    "programs/minter",
    "programs/redemption",
    "programs/custodial-gatekeeper",
]

[workspace.dependencies]
anchor-lang = "0.31.1"
anchor-spl = "0.31.1"
spl-transfer-hook-interface = "0.8"
spl-tlv-account-resolution = "0.8"
blake3 = "=1.5.5"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
opt-level = 3
incremental = false
