/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertIsInstructionWithAccounts,
  containsBytes,
  fixEncoderSize,
  getBytesEncoder,
  type Address,
  type Instruction,
  type InstructionWithData,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  parseInitExtraAccountMetasInstruction,
  parseTransferHookExecuteInstruction,
  type ParsedInitExtraAccountMetasInstruction,
  type ParsedTransferHookExecuteInstruction,
} from "../instructions";

export const SPIKO_TRANSFER_HOOK_PROGRAM_ADDRESS =
  "GMpqabVyd98sefjUB3fLhy6HA77xTnGpWy9e7vJs2vtJ" as Address<"GMpqabVyd98sefjUB3fLhy6HA77xTnGpWy9e7vJs2vtJ">;

export enum SpikoTransferHookInstruction {
  InitExtraAccountMetas,
  TransferHookExecute,
}

export function identifySpikoTransferHookInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): SpikoTransferHookInstruction {
  const data = "data" in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 1).encode(new Uint8Array([0])),
      0,
    )
  ) {
    return SpikoTransferHookInstruction.InitExtraAccountMetas;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([105, 37, 101, 197, 75, 251, 102, 26]),
      ),
      0,
    )
  ) {
    return SpikoTransferHookInstruction.TransferHookExecute;
  }
  throw new Error(
    "The provided instruction could not be identified as a spikoTransferHook instruction.",
  );
}

export type ParsedSpikoTransferHookInstruction<
  TProgram extends string = "GMpqabVyd98sefjUB3fLhy6HA77xTnGpWy9e7vJs2vtJ",
> =
  | ({
      instructionType: SpikoTransferHookInstruction.InitExtraAccountMetas;
    } & ParsedInitExtraAccountMetasInstruction<TProgram>)
  | ({
      instructionType: SpikoTransferHookInstruction.TransferHookExecute;
    } & ParsedTransferHookExecuteInstruction<TProgram>);

export function parseSpikoTransferHookInstruction<TProgram extends string>(
  instruction: Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array>,
): ParsedSpikoTransferHookInstruction<TProgram> {
  const instructionType = identifySpikoTransferHookInstruction(instruction);
  switch (instructionType) {
    case SpikoTransferHookInstruction.InitExtraAccountMetas: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SpikoTransferHookInstruction.InitExtraAccountMetas,
        ...parseInitExtraAccountMetasInstruction(instruction),
      };
    }
    case SpikoTransferHookInstruction.TransferHookExecute: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SpikoTransferHookInstruction.TransferHookExecute,
        ...parseTransferHookExecuteInstruction(instruction),
      };
    }
    default:
      throw new Error(
        `Unrecognized instruction type: ${instructionType as string}`,
      );
  }
}
