[package]
name = "spiko-token"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build", "permission-manager/idl-build", "redemption/idl-build", "spiko-transfer-hook/idl-build"]

[dependencies]
anchor-lang = { workspace = true }
anchor-spl = { workspace = true }
permission-manager = { path = "../permission-manager", features = ["cpi"] }
redemption = { path = "../redemption", features = ["cpi"] }
spiko-transfer-hook = { path = "../spiko-transfer-hook", features = ["cpi"] }
spl-token-2022-interface = "2.1.0"
solana-sha256-hasher = { workspace = true }

[dev-dependencies]
litesvm = { workspace = true }
solana-sdk = "3"
solana-sdk-ids = "3"
solana-system-interface = "2"
solana-program-pack = "3"
spl-token-2022-interface = "2.1.0"
spl-associated-token-account = "8"

[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(feature, values("custom-heap", "custom-allocator", "anchor-debug"))'] }