pub const CONFIG_SEED: &[u8] = b"config";
pub const PERMISSION_MANAGER_CONFIG_SEED: &[u8] = CONFIG_SEED;
pub const USER_PERMISSION_SEED: &[u8] = b"user_permission";

pub const ROLE_MINTER: u16 = 1;
pub const ROLE_PAUSER: u16 = 2;
pub const ROLE_BURNER: u16 = 4;
pub const ROLE_WHITELISTER: u16 = 8;
pub const ROLE_WHITELISTED: u16 = 16;
pub const ROLE_REDEMPTION_EXECUTOR: u16 = 32;
pub const ROLE_MINT_APPROVER: u16 = 64;
pub const ROLE_MINT_INITIATOR: u16 = 128;
pub const ROLE_WHITELISTED_EXT: u16 = 256;
pub const ROLE_CUSTODIAL_GATEKEEPER_APPROVER: u16 = 512;

pub const VALID_ROLES_BITMASK: u16 = ROLE_MINTER
    | ROLE_PAUSER
    | ROLE_BURNER
    | ROLE_WHITELISTER
    | ROLE_WHITELISTED
    | ROLE_REDEMPTION_EXECUTOR
    | ROLE_MINT_APPROVER
    | ROLE_MINT_INITIATOR
    | ROLE_WHITELISTED_EXT
    | ROLE_CUSTODIAL_GATEKEEPER_APPROVER;
