/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type RedemptionExecuted = {
  operator: Address;
  user: Address;
  mint: Address;
  amount: bigint;
  salt: bigint;
};

export type RedemptionExecutedArgs = {
  operator: Address;
  user: Address;
  mint: Address;
  amount: number | bigint;
  salt: number | bigint;
};

export function getRedemptionExecutedEncoder(): FixedSizeEncoder<RedemptionExecutedArgs> {
  return getStructEncoder([
    ["operator", getAddressEncoder()],
    ["user", getAddressEncoder()],
    ["mint", getAddressEncoder()],
    ["amount", getU64Encoder()],
    ["salt", getU64Encoder()],
  ]);
}

export function getRedemptionExecutedDecoder(): FixedSizeDecoder<RedemptionExecuted> {
  return getStructDecoder([
    ["operator", getAddressDecoder()],
    ["user", getAddressDecoder()],
    ["mint", getAddressDecoder()],
    ["amount", getU64Decoder()],
    ["salt", getU64Decoder()],
  ]);
}

export function getRedemptionExecutedCodec(): FixedSizeCodec<
  RedemptionExecutedArgs,
  RedemptionExecuted
> {
  return combineCodec(
    getRedemptionExecutedEncoder(),
    getRedemptionExecutedDecoder(),
  );
}
