/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type RedemptionInitialized = { admin: Address };

export type RedemptionInitializedArgs = RedemptionInitialized;

export function getRedemptionInitializedEncoder(): FixedSizeEncoder<RedemptionInitializedArgs> {
  return getStructEncoder([["admin", getAddressEncoder()]]);
}

export function getRedemptionInitializedDecoder(): FixedSizeDecoder<RedemptionInitialized> {
  return getStructDecoder([["admin", getAddressDecoder()]]);
}

export function getRedemptionInitializedCodec(): FixedSizeCodec<
  RedemptionInitializedArgs,
  RedemptionInitialized
> {
  return combineCodec(
    getRedemptionInitializedEncoder(),
    getRedemptionInitializedDecoder(),
  );
}
