/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type RedemptionInitiated = {
  user: Address;
  mint: Address;
  amount: bigint;
  salt: bigint;
  deadline: bigint;
};

export type RedemptionInitiatedArgs = {
  user: Address;
  mint: Address;
  amount: number | bigint;
  salt: number | bigint;
  deadline: number | bigint;
};

export function getRedemptionInitiatedEncoder(): FixedSizeEncoder<RedemptionInitiatedArgs> {
  return getStructEncoder([
    ["user", getAddressEncoder()],
    ["mint", getAddressEncoder()],
    ["amount", getU64Encoder()],
    ["salt", getU64Encoder()],
    ["deadline", getI64Encoder()],
  ]);
}

export function getRedemptionInitiatedDecoder(): FixedSizeDecoder<RedemptionInitiated> {
  return getStructDecoder([
    ["user", getAddressDecoder()],
    ["mint", getAddressDecoder()],
    ["amount", getU64Decoder()],
    ["salt", getU64Decoder()],
    ["deadline", getI64Decoder()],
  ]);
}

export function getRedemptionInitiatedCodec(): FixedSizeCodec<
  RedemptionInitiatedArgs,
  RedemptionInitiated
> {
  return combineCodec(
    getRedemptionInitiatedEncoder(),
    getRedemptionInitiatedDecoder(),
  );
}
