/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type TokenMinimumUpdated = {
  caller: Address;
  mint: Address;
  minimum: bigint;
};

export type TokenMinimumUpdatedArgs = {
  caller: Address;
  mint: Address;
  minimum: number | bigint;
};

export function getTokenMinimumUpdatedEncoder(): FixedSizeEncoder<TokenMinimumUpdatedArgs> {
  return getStructEncoder([
    ["caller", getAddressEncoder()],
    ["mint", getAddressEncoder()],
    ["minimum", getU64Encoder()],
  ]);
}

export function getTokenMinimumUpdatedDecoder(): FixedSizeDecoder<TokenMinimumUpdated> {
  return getStructDecoder([
    ["caller", getAddressDecoder()],
    ["mint", getAddressDecoder()],
    ["minimum", getU64Decoder()],
  ]);
}

export function getTokenMinimumUpdatedCodec(): FixedSizeCodec<
  TokenMinimumUpdatedArgs,
  TokenMinimumUpdated
> {
  return combineCodec(
    getTokenMinimumUpdatedEncoder(),
    getTokenMinimumUpdatedDecoder(),
  );
}
