/**
 * Shared helpers for the E2E test.
 *
 * Uses Codama-generated PDA helpers and program addresses where available.
 * Hand-written helpers are only used for PDAs that Codama did not generate
 * (mint authority, extra account metas, vault authority, event authorities).
 */

import {
  type Address,
  type KeyPairSigner,
  type Rpc,
  type SolanaRpcApi,
  type RpcSubscriptions,
  type SolanaRpcSubscriptionsApi,
  type ReadonlyUint8Array,
  address,
  AccountRole,
  createSolanaRpc,
  createSolanaRpcSubscriptions,
  createKeyPairSignerFromBytes,
  getAddressEncoder,
  getProgramDerivedAddress,
  pipe,
  createTransactionMessage,
  setTransactionMessageFeePayerSigner,
  setTransactionMessageLifetimeUsingBlockhash,
  appendTransactionMessageInstructions,
  signTransactionMessageWithSigners,
  sendAndConfirmTransactionFactory,
  getSignatureFromTransaction,
} from "@solana/kit";

import fs from "fs";
import path from "path";

// ── Codama-generated program addresses ──────────────────────────
import { PERMISSION_MANAGER_PROGRAM_ADDRESS } from "../../clients/ts/permission-manager/src/generated/programs/index.js";
import { SPIKO_TOKEN_PROGRAM_ADDRESS } from "../../clients/ts/spiko-token/src/generated/programs/index.js";
import { MINTER_PROGRAM_ADDRESS } from "../../clients/ts/minter/src/generated/programs/index.js";
import { REDEMPTION_PROGRAM_ADDRESS } from "../../clients/ts/redemption/src/generated/programs/index.js";
import { SPIKO_TRANSFER_HOOK_PROGRAM_ADDRESS } from "../../clients/ts/spiko-transfer-hook/src/generated/programs/index.js";
import { CUSTODIAL_GATEKEEPER_PROGRAM_ADDRESS } from "../../clients/ts/custodial-gatekeeper/src/generated/programs/index.js";

// ── Codama-generated PDA helpers ────────────────────────────────
import { findPermissionConfigPda, findUserPermissionsPda } from "../../clients/ts/permission-manager/src/generated/pdas/index.js";
import { findTokenConfigPda } from "../../clients/ts/spiko-token/src/generated/pdas/index.js";
import { findMinterConfigPda, findDailyLimitPda, findMintOperationPda } from "../../clients/ts/minter/src/generated/pdas/index.js";
import { findRedemptionConfigPda, findRedemptionOperationPda, findTokenMinimumPda } from "../../clients/ts/redemption/src/generated/pdas/index.js";
import { findGatekeeperConfigPda, findWithdrawalDailyLimitPda, findWithdrawalOperationPda } from "../../clients/ts/custodial-gatekeeper/src/generated/pdas/index.js";

// Re-export everything the E2E test needs
export {
  PERMISSION_MANAGER_PROGRAM_ADDRESS,
  SPIKO_TOKEN_PROGRAM_ADDRESS,
  MINTER_PROGRAM_ADDRESS,
  REDEMPTION_PROGRAM_ADDRESS,
  SPIKO_TRANSFER_HOOK_PROGRAM_ADDRESS,
  CUSTODIAL_GATEKEEPER_PROGRAM_ADDRESS,
  findPermissionConfigPda,
  findUserPermissionsPda,
  findTokenConfigPda,
  findMinterConfigPda,
  findDailyLimitPda,
  findMintOperationPda,
  findRedemptionConfigPda,
  findRedemptionOperationPda,
  findTokenMinimumPda,
  findGatekeeperConfigPda,
  findWithdrawalDailyLimitPda,
  findWithdrawalOperationPda,
};

// =================================================================
// Well-known program addresses
// =================================================================

export const TOKEN_2022_PROGRAM_ID: Address =
  address("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb");

export const SYSTEM_PROGRAM_ID: Address =
  address("11111111111111111111111111111111");

export const ASSOCIATED_TOKEN_PROGRAM_ID: Address =
  address("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL");

// =================================================================
// Role Bits
// =================================================================

export const ROLE_MINTER = 0;
export const ROLE_PAUSER = 1;
export const ROLE_BURNER = 2;
export const ROLE_WHITELISTER = 3;
export const ROLE_WHITELISTED = 4;
export const ROLE_REDEMPTION_EXECUTOR = 5;
export const ROLE_MINT_APPROVER = 6;
export const ROLE_MINT_INITIATOR = 7;
export const ROLE_WHITELISTED_EXT = 8;
export const ROLE_CUSTODIAL_GATEKEEPER_APPROVER = 9;

export const ROLE_NAMES: Record<number, string> = {
  [ROLE_MINTER]: "MINTER",
  [ROLE_PAUSER]: "PAUSER",
  [ROLE_BURNER]: "BURNER",
  [ROLE_WHITELISTER]: "WHITELISTER",
  [ROLE_WHITELISTED]: "WHITELISTED",
  [ROLE_REDEMPTION_EXECUTOR]: "REDEMPTION_EXECUTOR",
  [ROLE_MINT_APPROVER]: "MINT_APPROVER",
  [ROLE_MINT_INITIATOR]: "MINT_INITIATOR",
  [ROLE_WHITELISTED_EXT]: "WHITELISTED_EXT",
  [ROLE_CUSTODIAL_GATEKEEPER_APPROVER]: "CUSTODIAL_GATEKEEPER_APPROVER",
};

// =================================================================
// Hand-written PDA helpers (not generated by Codama)
// =================================================================

const enc = new TextEncoder();
const addressEncoder = getAddressEncoder();

const MINT_AUTHORITY_SEED = enc.encode("mint_authority");
const EXTRA_ACCOUNT_METAS_SEED = enc.encode("extra-account-metas");
const VAULT_SEED = enc.encode("vault");
const EVENT_AUTHORITY_SEED = enc.encode("event_authority");

export async function mintAuthorityPda(mint: Address): Promise<readonly [Address, number]> {
  return getProgramDerivedAddress({
    programAddress: SPIKO_TOKEN_PROGRAM_ADDRESS,
    seeds: [MINT_AUTHORITY_SEED, addressEncoder.encode(mint)],
  });
}

export async function extraAccountMetaListPda(mint: Address): Promise<readonly [Address, number]> {
  return getProgramDerivedAddress({
    programAddress: SPIKO_TRANSFER_HOOK_PROGRAM_ADDRESS,
    seeds: [EXTRA_ACCOUNT_METAS_SEED, addressEncoder.encode(mint)],
  });
}

export async function vaultAuthorityPda(): Promise<readonly [Address, number]> {
  return getProgramDerivedAddress({
    programAddress: REDEMPTION_PROGRAM_ADDRESS,
    seeds: [VAULT_SEED],
  });
}

// ── Event Authority PDAs (self-CPI event emission) ──

export async function permissionManagerEventAuthorityPda(): Promise<readonly [Address, number]> {
  return getProgramDerivedAddress({
    programAddress: PERMISSION_MANAGER_PROGRAM_ADDRESS,
    seeds: [EVENT_AUTHORITY_SEED],
  });
}

export async function spikoTokenEventAuthorityPda(): Promise<readonly [Address, number]> {
  return getProgramDerivedAddress({
    programAddress: SPIKO_TOKEN_PROGRAM_ADDRESS,
    seeds: [EVENT_AUTHORITY_SEED],
  });
}

export async function transferHookEventAuthorityPda(): Promise<readonly [Address, number]> {
  return getProgramDerivedAddress({
    programAddress: SPIKO_TRANSFER_HOOK_PROGRAM_ADDRESS,
    seeds: [EVENT_AUTHORITY_SEED],
  });
}

export async function minterEventAuthorityPda(): Promise<readonly [Address, number]> {
  return getProgramDerivedAddress({
    programAddress: MINTER_PROGRAM_ADDRESS,
    seeds: [EVENT_AUTHORITY_SEED],
  });
}

export async function redemptionEventAuthorityPda(): Promise<readonly [Address, number]> {
  return getProgramDerivedAddress({
    programAddress: REDEMPTION_PROGRAM_ADDRESS,
    seeds: [EVENT_AUTHORITY_SEED],
  });
}

export async function custodialGatekeeperEventAuthorityPda(): Promise<readonly [Address, number]> {
  return getProgramDerivedAddress({
    programAddress: CUSTODIAL_GATEKEEPER_PROGRAM_ADDRESS,
    seeds: [EVENT_AUTHORITY_SEED],
  });
}

export async function custodialGatekeeperVaultAuthorityPda(): Promise<readonly [Address, number]> {
  return getProgramDerivedAddress({
    programAddress: CUSTODIAL_GATEKEEPER_PROGRAM_ADDRESS,
    seeds: [VAULT_SEED],
  });
}

// =================================================================
// Solana CLI config loading
// =================================================================

export function loadSolanaConfig(): { rpcUrl: string; keypairPath: string } {
  const configPath = path.join(
    process.env.HOME || "~",
    ".config/solana/cli/config.yml"
  );
  const content = fs.readFileSync(configPath, "utf-8");

  let rpcUrl = "https://api.devnet.solana.com";
  let keypairPath = path.join(
    process.env.HOME || "~",
    ".config/solana/id.json"
  );

  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (trimmed.startsWith("json_rpc_url:")) {
      rpcUrl = trimmed.split("json_rpc_url:")[1].trim().replace(/"/g, "");
    }
    if (trimmed.startsWith("keypair_path:")) {
      keypairPath = trimmed.split("keypair_path:")[1].trim().replace(/"/g, "");
    }
  }

  return { rpcUrl, keypairPath };
}

function rpcUrlToWsUrl(rpcUrl: string): string {
  return rpcUrl.replace("https://", "wss://").replace("http://", "ws://");
}

// =================================================================
// Keypair + RPC helpers
// =================================================================

export async function loadKeypair(filePath: string): Promise<KeyPairSigner> {
  const bytes = new Uint8Array(
    JSON.parse(fs.readFileSync(filePath, "utf-8"))
  );
  return createKeyPairSignerFromBytes(bytes);
}

export async function accountExists(
  rpc: Rpc<SolanaRpcApi>,
  addr: Address
): Promise<boolean> {
  const { value } = await rpc
    .getAccountInfo(addr, { encoding: "base64" })
    .send();
  return value !== null;
}

export async function sendTx(
  rpc: Rpc<SolanaRpcApi>,
  rpcSubscriptions: RpcSubscriptions<SolanaRpcSubscriptionsApi>,
  payer: KeyPairSigner,
  instructions: Parameters<typeof appendTransactionMessageInstructions>[0],
  label: string
): Promise<string> {
  const { value: latestBlockhash } = await rpc.getLatestBlockhash().send();

  const txMessage = pipe(
    createTransactionMessage({ version: 0 }),
    (tx) => setTransactionMessageFeePayerSigner(payer, tx),
    (tx) => setTransactionMessageLifetimeUsingBlockhash(latestBlockhash, tx),
    (tx) => appendTransactionMessageInstructions(instructions, tx)
  );

  const signedTx = await signTransactionMessageWithSigners(txMessage);
  const sendAndConfirm = sendAndConfirmTransactionFactory({
    rpc,
    rpcSubscriptions,
  });
  await sendAndConfirm(signedTx, { commitment: "confirmed" });

  const sig = getSignatureFromTransaction(signedTx);
  console.log(`  ${label}: ${sig}`);
  return sig;
}

// =================================================================
// Setup — loads config, creates RPC, loads admin keypair
// =================================================================

export async function setup() {
  const config = loadSolanaConfig();
  const rpc = createSolanaRpc(config.rpcUrl);
  const rpcSub = createSolanaRpcSubscriptions(rpcUrlToWsUrl(config.rpcUrl));
  const admin = await loadKeypair(config.keypairPath);

  console.log(`RPC:      ${config.rpcUrl}`);
  console.log(`Wallet:   ${admin.address}\n`);

  return { rpc, rpcSub, admin };
}

// =================================================================
// ATA (Associated Token Account) helpers
// =================================================================

export async function getAssociatedTokenAddress(
  wallet: Address,
  mint: Address
): Promise<Address> {
  const [ata] = await getProgramDerivedAddress({
    programAddress: ASSOCIATED_TOKEN_PROGRAM_ID,
    seeds: [
      addressEncoder.encode(wallet),
      addressEncoder.encode(TOKEN_2022_PROGRAM_ID),
      addressEncoder.encode(mint),
    ],
  });
  return ata;
}

/**
 * Build a CreateAssociatedTokenAccountIdempotent instruction for Token-2022.
 * ATA program instruction index 1 = CreateIdempotent.
 */
export function createAssociatedTokenAccountIdempotent(
  payer: { address: Address; [key: string]: any },
  ata: Address,
  wallet: Address,
  mint: Address
) {
  return {
    programAddress: ASSOCIATED_TOKEN_PROGRAM_ID,
    accounts: [
      { address: payer.address, role: AccountRole.WRITABLE_SIGNER as const, signer: payer },
      { address: ata, role: AccountRole.WRITABLE as const },
      { address: wallet, role: AccountRole.READONLY as const },
      { address: mint, role: AccountRole.READONLY as const },
      { address: SYSTEM_PROGRAM_ID, role: AccountRole.READONLY as const },
      { address: TOKEN_2022_PROGRAM_ID, role: AccountRole.READONLY as const },
    ],
    data: new Uint8Array([1]) as ReadonlyUint8Array,
  };
}

// =================================================================
// SHA-256 helper for operation_id
// =================================================================

/**
 * Compute operation_id = SHA256(user(32) || mint(32) || amount_le(8) || salt_le(8))
 * Uses Web Crypto API (available in Node.js 18+).
 */
export async function computeOperationId(
  user: Address,
  mint: Address,
  amount: bigint,
  salt: bigint
): Promise<Uint8Array> {
  const input = new Uint8Array(80);
  input.set(addressEncoder.encode(user), 0);
  input.set(addressEncoder.encode(mint), 32);

  const amountBuf = new ArrayBuffer(8);
  new DataView(amountBuf).setBigUint64(0, amount, true);
  input.set(new Uint8Array(amountBuf), 64);

  const saltBuf = new ArrayBuffer(8);
  new DataView(saltBuf).setBigUint64(0, salt, true);
  input.set(new Uint8Array(saltBuf), 72);

  const hash = await crypto.subtle.digest("SHA-256", input);
  return new Uint8Array(hash);
}

// =================================================================
// Token-2022 mint creation helpers
// =================================================================

/**
 * Compute the required account space for a Token-2022 mint with
 * TransferHook + PermanentDelegate + MetadataPointer + inline metadata.
 *
 * Layout:
 *   BASE_MINT (82) + padding to multisig boundary (83) = 165
 *   + ACCOUNT_TYPE (1) = 166
 *   + each extension: TYPE_u16(2) + LENGTH_u16(2) + data
 *
 * Extensions:
 *   TransferHook:     2+2 + 64 (authority 32 + programId 32) = 68
 *   PermanentDelegate: 2+2 + 32 (delegate) = 36
 *   MetadataPointer:  2+2 + 64 (authority 32 + metadataAddress 32) = 68
 *   TokenMetadata:    2+2 + variable
 *     update_authority(32) + mint(32) + name(4+len) + symbol(4+len) + uri(4+len)
 *     + additional_metadata_len(4) = variable
 */
/**
 * Fixed extensions size: base mint + TransferHook + PermanentDelegate + MetadataPointer.
 * Token-2022 InitializeMint2 validates against this exact size.
 * Metadata is added later by TokenMetadataInitialize which reallocs the account.
 */
export const MINT_FIXED_EXTENSIONS_SIZE = 338; // 166 + 68 + 36 + 68

/**
 * Full account size including TokenMetadata extension (used for rent calculation).
 * Token-2022's TokenMetadataInitialize will realloc the account to this size.
 */
export function getMintAccountSpace(
  name: string,
  symbol: string,
  uri: string
): number {
  // TokenMetadata extension: type(2) + len(2) + data
  //   data = update_authority(32) + mint(32)
  //        + name_len(4) + name_bytes + symbol_len(4) + symbol_bytes + uri_len(4) + uri_bytes
  //        + additional_metadata_count(4)
  const metadataDataLen =
    32 + 32 + (4 + name.length) + (4 + symbol.length) + (4 + uri.length) + 4;
  const TOKEN_METADATA = 4 + metadataDataLen;

  return MINT_FIXED_EXTENSIONS_SIZE + TOKEN_METADATA;
}

/**
 * Build a SystemProgram::CreateAccount instruction to allocate the mint account.
 * The mint keypair must sign the transaction.
 */
export function buildCreateAccountInstruction(
  payer: KeyPairSigner,
  newAccount: KeyPairSigner,
  lamports: bigint,
  space: number,
  owner: Address
) {
  // SystemProgram CreateAccount instruction data:
  //   index(4 LE) = 0 + lamports(8 LE) + space(8 LE) + owner(32)
  const data = new Uint8Array(4 + 8 + 8 + 32);
  const view = new DataView(data.buffer);
  view.setUint32(0, 0, true); // CreateAccount instruction index
  view.setBigUint64(4, lamports, true);
  view.setBigUint64(12, BigInt(space), true);
  data.set(addressEncoder.encode(owner), 20);

  return {
    programAddress: SYSTEM_PROGRAM_ID,
    accounts: [
      { address: payer.address, role: AccountRole.WRITABLE_SIGNER as const, signer: payer },
      { address: newAccount.address, role: AccountRole.WRITABLE_SIGNER as const, signer: newAccount },
    ],
    data: data as ReadonlyUint8Array,
  };
}

// =================================================================
// buildTransferChecked (Path A: direct Token-2022 TransferChecked)
//
// This is NOT a Spiko program instruction — it's a raw Token-2022
// TransferChecked with extra accounts for the transfer hook.
// Stays hand-written since Codama only generates Spiko program clients.
// =================================================================

export function buildTransferChecked(
  sender: KeyPairSigner,
  sourceAta: Address,
  destinationAta: Address,
  mint: Address,
  tokenConfigAddr: Address,
  senderPermsAddr: Address,
  recipientPermsAddr: Address,
  extraAccountMetaListAddr: Address,
  amount: bigint,
  decimals: number,
  transferHookEventAuthority: Address,
) {
  // Data: opcode(1) + amount(u64 LE) + decimals(u8) = 10 bytes
  const data = new Uint8Array(10);
  data[0] = 12; // TransferChecked opcode
  new DataView(data.buffer).setBigUint64(1, amount, true);
  data[9] = decimals;

  return {
    programAddress: TOKEN_2022_PROGRAM_ID,
    accounts: [
      { address: sourceAta, role: AccountRole.WRITABLE as const },
      { address: mint, role: AccountRole.READONLY as const },
      { address: destinationAta, role: AccountRole.WRITABLE as const },
      { address: sender.address, role: AccountRole.WRITABLE_SIGNER as const, signer: sender },
      // Transfer hook extra accounts (order must match ExtraAccountMetaList)
      { address: extraAccountMetaListAddr, role: AccountRole.READONLY as const },
      { address: PERMISSION_MANAGER_PROGRAM_ADDRESS as Address, role: AccountRole.READONLY as const },
      { address: SPIKO_TOKEN_PROGRAM_ADDRESS as Address, role: AccountRole.READONLY as const },
      { address: tokenConfigAddr, role: AccountRole.READONLY as const },
      { address: senderPermsAddr, role: AccountRole.READONLY as const },
      { address: recipientPermsAddr, role: AccountRole.READONLY as const },
      { address: transferHookEventAuthority, role: AccountRole.READONLY as const },
      { address: SPIKO_TRANSFER_HOOK_PROGRAM_ADDRESS as Address, role: AccountRole.READONLY as const },
    ],
    data: data as ReadonlyUint8Array,
  };
}
