/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type DailyLimitUpdated = {
  caller: Address;
  mint: Address;
  limit: bigint;
};

export type DailyLimitUpdatedArgs = {
  caller: Address;
  mint: Address;
  limit: number | bigint;
};

export function getDailyLimitUpdatedEncoder(): FixedSizeEncoder<DailyLimitUpdatedArgs> {
  return getStructEncoder([
    ["caller", getAddressEncoder()],
    ["mint", getAddressEncoder()],
    ["limit", getU64Encoder()],
  ]);
}

export function getDailyLimitUpdatedDecoder(): FixedSizeDecoder<DailyLimitUpdated> {
  return getStructDecoder([
    ["caller", getAddressDecoder()],
    ["mint", getAddressDecoder()],
    ["limit", getU64Decoder()],
  ]);
}

export function getDailyLimitUpdatedCodec(): FixedSizeCodec<
  DailyLimitUpdatedArgs,
  DailyLimitUpdated
> {
  return combineCodec(
    getDailyLimitUpdatedEncoder(),
    getDailyLimitUpdatedDecoder(),
  );
}
