/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type MaxDelayUpdated = { caller: Address; maxDelay: bigint };

export type MaxDelayUpdatedArgs = {
  caller: Address;
  maxDelay: number | bigint;
};

export function getMaxDelayUpdatedEncoder(): FixedSizeEncoder<MaxDelayUpdatedArgs> {
  return getStructEncoder([
    ["caller", getAddressEncoder()],
    ["maxDelay", getI64Encoder()],
  ]);
}

export function getMaxDelayUpdatedDecoder(): FixedSizeDecoder<MaxDelayUpdated> {
  return getStructDecoder([
    ["caller", getAddressDecoder()],
    ["maxDelay", getI64Decoder()],
  ]);
}

export function getMaxDelayUpdatedCodec(): FixedSizeCodec<
  MaxDelayUpdatedArgs,
  MaxDelayUpdated
> {
  return combineCodec(getMaxDelayUpdatedEncoder(), getMaxDelayUpdatedDecoder());
}
