/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type MintApproved = {
  approver: Address;
  user: Address;
  mint: Address;
  amount: bigint;
  salt: bigint;
};

export type MintApprovedArgs = {
  approver: Address;
  user: Address;
  mint: Address;
  amount: number | bigint;
  salt: number | bigint;
};

export function getMintApprovedEncoder(): FixedSizeEncoder<MintApprovedArgs> {
  return getStructEncoder([
    ["approver", getAddressEncoder()],
    ["user", getAddressEncoder()],
    ["mint", getAddressEncoder()],
    ["amount", getU64Encoder()],
    ["salt", getU64Encoder()],
  ]);
}

export function getMintApprovedDecoder(): FixedSizeDecoder<MintApproved> {
  return getStructDecoder([
    ["approver", getAddressDecoder()],
    ["user", getAddressDecoder()],
    ["mint", getAddressDecoder()],
    ["amount", getU64Decoder()],
    ["salt", getU64Decoder()],
  ]);
}

export function getMintApprovedCodec(): FixedSizeCodec<
  MintApprovedArgs,
  MintApproved
> {
  return combineCodec(getMintApprovedEncoder(), getMintApprovedDecoder());
}
