/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type MinterInitialized = { admin: Address; maxDelay: bigint };

export type MinterInitializedArgs = {
  admin: Address;
  maxDelay: number | bigint;
};

export function getMinterInitializedEncoder(): FixedSizeEncoder<MinterInitializedArgs> {
  return getStructEncoder([
    ["admin", getAddressEncoder()],
    ["maxDelay", getI64Encoder()],
  ]);
}

export function getMinterInitializedDecoder(): FixedSizeDecoder<MinterInitialized> {
  return getStructDecoder([
    ["admin", getAddressDecoder()],
    ["maxDelay", getI64Decoder()],
  ]);
}

export function getMinterInitializedCodec(): FixedSizeCodec<
  MinterInitializedArgs,
  MinterInitialized
> {
  return combineCodec(
    getMinterInitializedEncoder(),
    getMinterInitializedDecoder(),
  );
}
