/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const DAILY_LIMIT_DISCRIMINATOR = new Uint8Array([2]);

export function getDailyLimitDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 1).encode(DAILY_LIMIT_DISCRIMINATOR);
}

export type DailyLimit = {
  discriminator: ReadonlyUint8Array;
  bump: number;
  limit: bigint;
  usedAmount: bigint;
  lastDay: bigint;
};

export type DailyLimitArgs = {
  bump: number;
  limit: number | bigint;
  usedAmount: number | bigint;
  lastDay: number | bigint;
};

/** Gets the encoder for {@link DailyLimitArgs} account data. */
export function getDailyLimitEncoder(): FixedSizeEncoder<DailyLimitArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 1)],
      ["bump", getU8Encoder()],
      ["limit", getU64Encoder()],
      ["usedAmount", getU64Encoder()],
      ["lastDay", getI64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: DAILY_LIMIT_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link DailyLimit} account data. */
export function getDailyLimitDecoder(): FixedSizeDecoder<DailyLimit> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 1)],
    ["bump", getU8Decoder()],
    ["limit", getU64Decoder()],
    ["usedAmount", getU64Decoder()],
    ["lastDay", getI64Decoder()],
  ]);
}

/** Gets the codec for {@link DailyLimit} account data. */
export function getDailyLimitCodec(): FixedSizeCodec<
  DailyLimitArgs,
  DailyLimit
> {
  return combineCodec(getDailyLimitEncoder(), getDailyLimitDecoder());
}

export function decodeDailyLimit<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<DailyLimit, TAddress>;
export function decodeDailyLimit<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<DailyLimit, TAddress>;
export function decodeDailyLimit<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<DailyLimit, TAddress> | MaybeAccount<DailyLimit, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getDailyLimitDecoder(),
  );
}

export async function fetchDailyLimit<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<DailyLimit, TAddress>> {
  const maybeAccount = await fetchMaybeDailyLimit(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeDailyLimit<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<DailyLimit, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeDailyLimit(maybeAccount);
}

export async function fetchAllDailyLimit(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<DailyLimit>[]> {
  const maybeAccounts = await fetchAllMaybeDailyLimit(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeDailyLimit(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<DailyLimit>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeDailyLimit(maybeAccount));
}

export function getDailyLimitSize(): number {
  return 26;
}
