/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const MINT_OPERATION_DISCRIMINATOR = new Uint8Array([3]);

export function getMintOperationDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 1).encode(
    MINT_OPERATION_DISCRIMINATOR,
  );
}

export type MintOperation = {
  discriminator: ReadonlyUint8Array;
  bump: number;
  status: number;
  deadline: bigint;
};

export type MintOperationArgs = {
  bump: number;
  status: number;
  deadline: number | bigint;
};

/** Gets the encoder for {@link MintOperationArgs} account data. */
export function getMintOperationEncoder(): FixedSizeEncoder<MintOperationArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 1)],
      ["bump", getU8Encoder()],
      ["status", getU8Encoder()],
      ["deadline", getI64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: MINT_OPERATION_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link MintOperation} account data. */
export function getMintOperationDecoder(): FixedSizeDecoder<MintOperation> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 1)],
    ["bump", getU8Decoder()],
    ["status", getU8Decoder()],
    ["deadline", getI64Decoder()],
  ]);
}

/** Gets the codec for {@link MintOperation} account data. */
export function getMintOperationCodec(): FixedSizeCodec<
  MintOperationArgs,
  MintOperation
> {
  return combineCodec(getMintOperationEncoder(), getMintOperationDecoder());
}

export function decodeMintOperation<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<MintOperation, TAddress>;
export function decodeMintOperation<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<MintOperation, TAddress>;
export function decodeMintOperation<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<MintOperation, TAddress> | MaybeAccount<MintOperation, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getMintOperationDecoder(),
  );
}

export async function fetchMintOperation<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<MintOperation, TAddress>> {
  const maybeAccount = await fetchMaybeMintOperation(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeMintOperation<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<MintOperation, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeMintOperation(maybeAccount);
}

export async function fetchAllMintOperation(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<MintOperation>[]> {
  const maybeAccounts = await fetchAllMaybeMintOperation(
    rpc,
    addresses,
    config,
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeMintOperation(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<MintOperation>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeMintOperation(maybeAccount));
}

export function getMintOperationSize(): number {
  return 11;
}
