/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import { REDEMPTION_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const CANCEL_REDEMPTION_DISCRIMINATOR = new Uint8Array([2]);

export function getCancelRedemptionDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 1).encode(
    CANCEL_REDEMPTION_DISCRIMINATOR,
  );
}

export type CancelRedemptionInstruction<
  TProgram extends string = typeof REDEMPTION_PROGRAM_ADDRESS,
  TAccountCaller extends string | AccountMeta<string> = string,
  TAccountRedemptionConfig extends string | AccountMeta<string> = string,
  TAccountRedemptionOperation extends string | AccountMeta<string> = string,
  TAccountVault extends string | AccountMeta<string> = string,
  TAccountUserTokenAccount extends string | AccountMeta<string> = string,
  TAccountVaultAuthority extends string | AccountMeta<string> = string,
  TAccountTokenMint extends string | AccountMeta<string> = string,
  TAccountToken2022Program extends string | AccountMeta<string> =
    "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb",
  TAccountExtraAccountMetaList extends string | AccountMeta<string> = string,
  TAccountPermissionManagerProgram extends string | AccountMeta<string> =
    string,
  TAccountSpikoTokenProgram extends string | AccountMeta<string> = string,
  TAccountTokenConfig extends string | AccountMeta<string> = string,
  TAccountVaultAuthorityPermissions extends string | AccountMeta<string> =
    string,
  TAccountUserPermissions extends string | AccountMeta<string> = string,
  TAccountHookProgram extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountCaller extends string
        ? ReadonlySignerAccount<TAccountCaller> &
            AccountSignerMeta<TAccountCaller>
        : TAccountCaller,
      TAccountRedemptionConfig extends string
        ? ReadonlyAccount<TAccountRedemptionConfig>
        : TAccountRedemptionConfig,
      TAccountRedemptionOperation extends string
        ? WritableAccount<TAccountRedemptionOperation>
        : TAccountRedemptionOperation,
      TAccountVault extends string
        ? WritableAccount<TAccountVault>
        : TAccountVault,
      TAccountUserTokenAccount extends string
        ? WritableAccount<TAccountUserTokenAccount>
        : TAccountUserTokenAccount,
      TAccountVaultAuthority extends string
        ? ReadonlyAccount<TAccountVaultAuthority>
        : TAccountVaultAuthority,
      TAccountTokenMint extends string
        ? ReadonlyAccount<TAccountTokenMint>
        : TAccountTokenMint,
      TAccountToken2022Program extends string
        ? ReadonlyAccount<TAccountToken2022Program>
        : TAccountToken2022Program,
      TAccountExtraAccountMetaList extends string
        ? ReadonlyAccount<TAccountExtraAccountMetaList>
        : TAccountExtraAccountMetaList,
      TAccountPermissionManagerProgram extends string
        ? ReadonlyAccount<TAccountPermissionManagerProgram>
        : TAccountPermissionManagerProgram,
      TAccountSpikoTokenProgram extends string
        ? ReadonlyAccount<TAccountSpikoTokenProgram>
        : TAccountSpikoTokenProgram,
      TAccountTokenConfig extends string
        ? ReadonlyAccount<TAccountTokenConfig>
        : TAccountTokenConfig,
      TAccountVaultAuthorityPermissions extends string
        ? ReadonlyAccount<TAccountVaultAuthorityPermissions>
        : TAccountVaultAuthorityPermissions,
      TAccountUserPermissions extends string
        ? ReadonlyAccount<TAccountUserPermissions>
        : TAccountUserPermissions,
      TAccountHookProgram extends string
        ? ReadonlyAccount<TAccountHookProgram>
        : TAccountHookProgram,
      ...TRemainingAccounts,
    ]
  >;

export type CancelRedemptionInstructionData = {
  discriminator: ReadonlyUint8Array;
  user: Address;
  amount: bigint;
  salt: bigint;
};

export type CancelRedemptionInstructionDataArgs = {
  user: Address;
  amount: number | bigint;
  salt: number | bigint;
};

export function getCancelRedemptionInstructionDataEncoder(): FixedSizeEncoder<CancelRedemptionInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 1)],
      ["user", getAddressEncoder()],
      ["amount", getU64Encoder()],
      ["salt", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: CANCEL_REDEMPTION_DISCRIMINATOR }),
  );
}

export function getCancelRedemptionInstructionDataDecoder(): FixedSizeDecoder<CancelRedemptionInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 1)],
    ["user", getAddressDecoder()],
    ["amount", getU64Decoder()],
    ["salt", getU64Decoder()],
  ]);
}

export function getCancelRedemptionInstructionDataCodec(): FixedSizeCodec<
  CancelRedemptionInstructionDataArgs,
  CancelRedemptionInstructionData
> {
  return combineCodec(
    getCancelRedemptionInstructionDataEncoder(),
    getCancelRedemptionInstructionDataDecoder(),
  );
}

export type CancelRedemptionInput<
  TAccountCaller extends string = string,
  TAccountRedemptionConfig extends string = string,
  TAccountRedemptionOperation extends string = string,
  TAccountVault extends string = string,
  TAccountUserTokenAccount extends string = string,
  TAccountVaultAuthority extends string = string,
  TAccountTokenMint extends string = string,
  TAccountToken2022Program extends string = string,
  TAccountExtraAccountMetaList extends string = string,
  TAccountPermissionManagerProgram extends string = string,
  TAccountSpikoTokenProgram extends string = string,
  TAccountTokenConfig extends string = string,
  TAccountVaultAuthorityPermissions extends string = string,
  TAccountUserPermissions extends string = string,
  TAccountHookProgram extends string = string,
> = {
  /** Anyone (no permission check, deadline must have passed) */
  caller: TransactionSigner<TAccountCaller>;
  /** RedemptionConfig PDA */
  redemptionConfig: Address<TAccountRedemptionConfig>;
  /** RedemptionOperation PDA */
  redemptionOperation: Address<TAccountRedemptionOperation>;
  /** Vault token account (source for refund) */
  vault: Address<TAccountVault>;
  /** User's token account (destination for refund) */
  userTokenAccount: Address<TAccountUserTokenAccount>;
  /** Vault authority PDA. Seeds: ["vault"] */
  vaultAuthority: Address<TAccountVaultAuthority>;
  /** Token-2022 Mint */
  tokenMint: Address<TAccountTokenMint>;
  token2022Program?: Address<TAccountToken2022Program>;
  /** ExtraAccountMetaList PDA (Transfer Hook) */
  extraAccountMetaList: Address<TAccountExtraAccountMetaList>;
  /** PermissionManager program */
  permissionManagerProgram: Address<TAccountPermissionManagerProgram>;
  /** SpikoToken program */
  spikoTokenProgram: Address<TAccountSpikoTokenProgram>;
  /** TokenConfig PDA (spiko-token) */
  tokenConfig: Address<TAccountTokenConfig>;
  /** Vault authority's UserPermissions PDA (sender perms) */
  vaultAuthorityPermissions: Address<TAccountVaultAuthorityPermissions>;
  /** User's UserPermissions PDA (recipient perms) */
  userPermissions: Address<TAccountUserPermissions>;
  /** Hook program (spiko-transfer-hook) */
  hookProgram: Address<TAccountHookProgram>;
  user: CancelRedemptionInstructionDataArgs["user"];
  amount: CancelRedemptionInstructionDataArgs["amount"];
  salt: CancelRedemptionInstructionDataArgs["salt"];
};

export function getCancelRedemptionInstruction<
  TAccountCaller extends string,
  TAccountRedemptionConfig extends string,
  TAccountRedemptionOperation extends string,
  TAccountVault extends string,
  TAccountUserTokenAccount extends string,
  TAccountVaultAuthority extends string,
  TAccountTokenMint extends string,
  TAccountToken2022Program extends string,
  TAccountExtraAccountMetaList extends string,
  TAccountPermissionManagerProgram extends string,
  TAccountSpikoTokenProgram extends string,
  TAccountTokenConfig extends string,
  TAccountVaultAuthorityPermissions extends string,
  TAccountUserPermissions extends string,
  TAccountHookProgram extends string,
  TProgramAddress extends Address = typeof REDEMPTION_PROGRAM_ADDRESS,
>(
  input: CancelRedemptionInput<
    TAccountCaller,
    TAccountRedemptionConfig,
    TAccountRedemptionOperation,
    TAccountVault,
    TAccountUserTokenAccount,
    TAccountVaultAuthority,
    TAccountTokenMint,
    TAccountToken2022Program,
    TAccountExtraAccountMetaList,
    TAccountPermissionManagerProgram,
    TAccountSpikoTokenProgram,
    TAccountTokenConfig,
    TAccountVaultAuthorityPermissions,
    TAccountUserPermissions,
    TAccountHookProgram
  >,
  config?: { programAddress?: TProgramAddress },
): CancelRedemptionInstruction<
  TProgramAddress,
  TAccountCaller,
  TAccountRedemptionConfig,
  TAccountRedemptionOperation,
  TAccountVault,
  TAccountUserTokenAccount,
  TAccountVaultAuthority,
  TAccountTokenMint,
  TAccountToken2022Program,
  TAccountExtraAccountMetaList,
  TAccountPermissionManagerProgram,
  TAccountSpikoTokenProgram,
  TAccountTokenConfig,
  TAccountVaultAuthorityPermissions,
  TAccountUserPermissions,
  TAccountHookProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? REDEMPTION_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    caller: { value: input.caller ?? null, isWritable: false },
    redemptionConfig: {
      value: input.redemptionConfig ?? null,
      isWritable: false,
    },
    redemptionOperation: {
      value: input.redemptionOperation ?? null,
      isWritable: true,
    },
    vault: { value: input.vault ?? null, isWritable: true },
    userTokenAccount: {
      value: input.userTokenAccount ?? null,
      isWritable: true,
    },
    vaultAuthority: { value: input.vaultAuthority ?? null, isWritable: false },
    tokenMint: { value: input.tokenMint ?? null, isWritable: false },
    token2022Program: {
      value: input.token2022Program ?? null,
      isWritable: false,
    },
    extraAccountMetaList: {
      value: input.extraAccountMetaList ?? null,
      isWritable: false,
    },
    permissionManagerProgram: {
      value: input.permissionManagerProgram ?? null,
      isWritable: false,
    },
    spikoTokenProgram: {
      value: input.spikoTokenProgram ?? null,
      isWritable: false,
    },
    tokenConfig: { value: input.tokenConfig ?? null, isWritable: false },
    vaultAuthorityPermissions: {
      value: input.vaultAuthorityPermissions ?? null,
      isWritable: false,
    },
    userPermissions: {
      value: input.userPermissions ?? null,
      isWritable: false,
    },
    hookProgram: { value: input.hookProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.token2022Program.value) {
    accounts.token2022Program.value =
      "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb" as Address<"TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.caller),
      getAccountMeta(accounts.redemptionConfig),
      getAccountMeta(accounts.redemptionOperation),
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.userTokenAccount),
      getAccountMeta(accounts.vaultAuthority),
      getAccountMeta(accounts.tokenMint),
      getAccountMeta(accounts.token2022Program),
      getAccountMeta(accounts.extraAccountMetaList),
      getAccountMeta(accounts.permissionManagerProgram),
      getAccountMeta(accounts.spikoTokenProgram),
      getAccountMeta(accounts.tokenConfig),
      getAccountMeta(accounts.vaultAuthorityPermissions),
      getAccountMeta(accounts.userPermissions),
      getAccountMeta(accounts.hookProgram),
    ],
    data: getCancelRedemptionInstructionDataEncoder().encode(
      args as CancelRedemptionInstructionDataArgs,
    ),
    programAddress,
  } as CancelRedemptionInstruction<
    TProgramAddress,
    TAccountCaller,
    TAccountRedemptionConfig,
    TAccountRedemptionOperation,
    TAccountVault,
    TAccountUserTokenAccount,
    TAccountVaultAuthority,
    TAccountTokenMint,
    TAccountToken2022Program,
    TAccountExtraAccountMetaList,
    TAccountPermissionManagerProgram,
    TAccountSpikoTokenProgram,
    TAccountTokenConfig,
    TAccountVaultAuthorityPermissions,
    TAccountUserPermissions,
    TAccountHookProgram
  >);
}

export type ParsedCancelRedemptionInstruction<
  TProgram extends string = typeof REDEMPTION_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Anyone (no permission check, deadline must have passed) */
    caller: TAccountMetas[0];
    /** RedemptionConfig PDA */
    redemptionConfig: TAccountMetas[1];
    /** RedemptionOperation PDA */
    redemptionOperation: TAccountMetas[2];
    /** Vault token account (source for refund) */
    vault: TAccountMetas[3];
    /** User's token account (destination for refund) */
    userTokenAccount: TAccountMetas[4];
    /** Vault authority PDA. Seeds: ["vault"] */
    vaultAuthority: TAccountMetas[5];
    /** Token-2022 Mint */
    tokenMint: TAccountMetas[6];
    token2022Program: TAccountMetas[7];
    /** ExtraAccountMetaList PDA (Transfer Hook) */
    extraAccountMetaList: TAccountMetas[8];
    /** PermissionManager program */
    permissionManagerProgram: TAccountMetas[9];
    /** SpikoToken program */
    spikoTokenProgram: TAccountMetas[10];
    /** TokenConfig PDA (spiko-token) */
    tokenConfig: TAccountMetas[11];
    /** Vault authority's UserPermissions PDA (sender perms) */
    vaultAuthorityPermissions: TAccountMetas[12];
    /** User's UserPermissions PDA (recipient perms) */
    userPermissions: TAccountMetas[13];
    /** Hook program (spiko-transfer-hook) */
    hookProgram: TAccountMetas[14];
  };
  data: CancelRedemptionInstructionData;
};

export function parseCancelRedemptionInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedCancelRedemptionInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 15) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      caller: getNextAccount(),
      redemptionConfig: getNextAccount(),
      redemptionOperation: getNextAccount(),
      vault: getNextAccount(),
      userTokenAccount: getNextAccount(),
      vaultAuthority: getNextAccount(),
      tokenMint: getNextAccount(),
      token2022Program: getNextAccount(),
      extraAccountMetaList: getNextAccount(),
      permissionManagerProgram: getNextAccount(),
      spikoTokenProgram: getNextAccount(),
      tokenConfig: getNextAccount(),
      vaultAuthorityPermissions: getNextAccount(),
      userPermissions: getNextAccount(),
      hookProgram: getNextAccount(),
    },
    data: getCancelRedemptionInstructionDataDecoder().decode(instruction.data),
  };
}
