/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import { REDEMPTION_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const EXECUTE_REDEMPTION_DISCRIMINATOR = new Uint8Array([1]);

export function getExecuteRedemptionDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 1).encode(
    EXECUTE_REDEMPTION_DISCRIMINATOR,
  );
}

export type ExecuteRedemptionInstruction<
  TProgram extends string = typeof REDEMPTION_PROGRAM_ADDRESS,
  TAccountOperator extends string | AccountMeta<string> = string,
  TAccountRedemptionConfig extends string | AccountMeta<string> = string,
  TAccountRedemptionOperation extends string | AccountMeta<string> = string,
  TAccountOperatorPermissions extends string | AccountMeta<string> = string,
  TAccountSpikoTokenProgram extends string | AccountMeta<string> = string,
  TAccountTokenConfig extends string | AccountMeta<string> = string,
  TAccountTokenMint extends string | AccountMeta<string> = string,
  TAccountVault extends string | AccountMeta<string> = string,
  TAccountMintAuthority extends string | AccountMeta<string> = string,
  TAccountVaultAuthority extends string | AccountMeta<string> = string,
  TAccountVaultAuthorityPermissions extends string | AccountMeta<string> =
    string,
  TAccountToken2022Program extends string | AccountMeta<string> =
    "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountOperator extends string
        ? ReadonlySignerAccount<TAccountOperator> &
            AccountSignerMeta<TAccountOperator>
        : TAccountOperator,
      TAccountRedemptionConfig extends string
        ? ReadonlyAccount<TAccountRedemptionConfig>
        : TAccountRedemptionConfig,
      TAccountRedemptionOperation extends string
        ? WritableAccount<TAccountRedemptionOperation>
        : TAccountRedemptionOperation,
      TAccountOperatorPermissions extends string
        ? ReadonlyAccount<TAccountOperatorPermissions>
        : TAccountOperatorPermissions,
      TAccountSpikoTokenProgram extends string
        ? ReadonlyAccount<TAccountSpikoTokenProgram>
        : TAccountSpikoTokenProgram,
      TAccountTokenConfig extends string
        ? ReadonlyAccount<TAccountTokenConfig>
        : TAccountTokenConfig,
      TAccountTokenMint extends string
        ? WritableAccount<TAccountTokenMint>
        : TAccountTokenMint,
      TAccountVault extends string
        ? WritableAccount<TAccountVault>
        : TAccountVault,
      TAccountMintAuthority extends string
        ? ReadonlyAccount<TAccountMintAuthority>
        : TAccountMintAuthority,
      TAccountVaultAuthority extends string
        ? WritableAccount<TAccountVaultAuthority>
        : TAccountVaultAuthority,
      TAccountVaultAuthorityPermissions extends string
        ? ReadonlyAccount<TAccountVaultAuthorityPermissions>
        : TAccountVaultAuthorityPermissions,
      TAccountToken2022Program extends string
        ? ReadonlyAccount<TAccountToken2022Program>
        : TAccountToken2022Program,
      ...TRemainingAccounts,
    ]
  >;

export type ExecuteRedemptionInstructionData = {
  discriminator: ReadonlyUint8Array;
  user: Address;
  amount: bigint;
  salt: bigint;
};

export type ExecuteRedemptionInstructionDataArgs = {
  user: Address;
  amount: number | bigint;
  salt: number | bigint;
};

export function getExecuteRedemptionInstructionDataEncoder(): FixedSizeEncoder<ExecuteRedemptionInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 1)],
      ["user", getAddressEncoder()],
      ["amount", getU64Encoder()],
      ["salt", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: EXECUTE_REDEMPTION_DISCRIMINATOR }),
  );
}

export function getExecuteRedemptionInstructionDataDecoder(): FixedSizeDecoder<ExecuteRedemptionInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 1)],
    ["user", getAddressDecoder()],
    ["amount", getU64Decoder()],
    ["salt", getU64Decoder()],
  ]);
}

export function getExecuteRedemptionInstructionDataCodec(): FixedSizeCodec<
  ExecuteRedemptionInstructionDataArgs,
  ExecuteRedemptionInstructionData
> {
  return combineCodec(
    getExecuteRedemptionInstructionDataEncoder(),
    getExecuteRedemptionInstructionDataDecoder(),
  );
}

export type ExecuteRedemptionInput<
  TAccountOperator extends string = string,
  TAccountRedemptionConfig extends string = string,
  TAccountRedemptionOperation extends string = string,
  TAccountOperatorPermissions extends string = string,
  TAccountSpikoTokenProgram extends string = string,
  TAccountTokenConfig extends string = string,
  TAccountTokenMint extends string = string,
  TAccountVault extends string = string,
  TAccountMintAuthority extends string = string,
  TAccountVaultAuthority extends string = string,
  TAccountVaultAuthorityPermissions extends string = string,
  TAccountToken2022Program extends string = string,
> = {
  /** Operator (must have ROLE_REDEMPTION_EXECUTOR) */
  operator: TransactionSigner<TAccountOperator>;
  /** RedemptionConfig PDA */
  redemptionConfig: Address<TAccountRedemptionConfig>;
  /** RedemptionOperation PDA */
  redemptionOperation: Address<TAccountRedemptionOperation>;
  /** Operator's UserPermissions PDA (from permission_manager) */
  operatorPermissions: Address<TAccountOperatorPermissions>;
  /** Spiko Token program (for CPI: burn) */
  spikoTokenProgram: Address<TAccountSpikoTokenProgram>;
  /** TokenConfig PDA (on spiko-token) */
  tokenConfig: Address<TAccountTokenConfig>;
  /** Token-2022 Mint */
  tokenMint: Address<TAccountTokenMint>;
  /** Vault token account (source for burn) */
  vault: Address<TAccountVault>;
  /** Mint authority PDA (spiko-token) */
  mintAuthority: Address<TAccountMintAuthority>;
  /** Vault authority PDA. Seeds: ["vault"] */
  vaultAuthority: Address<TAccountVaultAuthority>;
  /** Vault authority's UserPermissions PDA (ROLE_BURNER) */
  vaultAuthorityPermissions: Address<TAccountVaultAuthorityPermissions>;
  token2022Program?: Address<TAccountToken2022Program>;
  user: ExecuteRedemptionInstructionDataArgs["user"];
  amount: ExecuteRedemptionInstructionDataArgs["amount"];
  salt: ExecuteRedemptionInstructionDataArgs["salt"];
};

export function getExecuteRedemptionInstruction<
  TAccountOperator extends string,
  TAccountRedemptionConfig extends string,
  TAccountRedemptionOperation extends string,
  TAccountOperatorPermissions extends string,
  TAccountSpikoTokenProgram extends string,
  TAccountTokenConfig extends string,
  TAccountTokenMint extends string,
  TAccountVault extends string,
  TAccountMintAuthority extends string,
  TAccountVaultAuthority extends string,
  TAccountVaultAuthorityPermissions extends string,
  TAccountToken2022Program extends string,
  TProgramAddress extends Address = typeof REDEMPTION_PROGRAM_ADDRESS,
>(
  input: ExecuteRedemptionInput<
    TAccountOperator,
    TAccountRedemptionConfig,
    TAccountRedemptionOperation,
    TAccountOperatorPermissions,
    TAccountSpikoTokenProgram,
    TAccountTokenConfig,
    TAccountTokenMint,
    TAccountVault,
    TAccountMintAuthority,
    TAccountVaultAuthority,
    TAccountVaultAuthorityPermissions,
    TAccountToken2022Program
  >,
  config?: { programAddress?: TProgramAddress },
): ExecuteRedemptionInstruction<
  TProgramAddress,
  TAccountOperator,
  TAccountRedemptionConfig,
  TAccountRedemptionOperation,
  TAccountOperatorPermissions,
  TAccountSpikoTokenProgram,
  TAccountTokenConfig,
  TAccountTokenMint,
  TAccountVault,
  TAccountMintAuthority,
  TAccountVaultAuthority,
  TAccountVaultAuthorityPermissions,
  TAccountToken2022Program
> {
  // Program address.
  const programAddress = config?.programAddress ?? REDEMPTION_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    operator: { value: input.operator ?? null, isWritable: false },
    redemptionConfig: {
      value: input.redemptionConfig ?? null,
      isWritable: false,
    },
    redemptionOperation: {
      value: input.redemptionOperation ?? null,
      isWritable: true,
    },
    operatorPermissions: {
      value: input.operatorPermissions ?? null,
      isWritable: false,
    },
    spikoTokenProgram: {
      value: input.spikoTokenProgram ?? null,
      isWritable: false,
    },
    tokenConfig: { value: input.tokenConfig ?? null, isWritable: false },
    tokenMint: { value: input.tokenMint ?? null, isWritable: true },
    vault: { value: input.vault ?? null, isWritable: true },
    mintAuthority: { value: input.mintAuthority ?? null, isWritable: false },
    vaultAuthority: { value: input.vaultAuthority ?? null, isWritable: true },
    vaultAuthorityPermissions: {
      value: input.vaultAuthorityPermissions ?? null,
      isWritable: false,
    },
    token2022Program: {
      value: input.token2022Program ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.token2022Program.value) {
    accounts.token2022Program.value =
      "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb" as Address<"TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.operator),
      getAccountMeta(accounts.redemptionConfig),
      getAccountMeta(accounts.redemptionOperation),
      getAccountMeta(accounts.operatorPermissions),
      getAccountMeta(accounts.spikoTokenProgram),
      getAccountMeta(accounts.tokenConfig),
      getAccountMeta(accounts.tokenMint),
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.mintAuthority),
      getAccountMeta(accounts.vaultAuthority),
      getAccountMeta(accounts.vaultAuthorityPermissions),
      getAccountMeta(accounts.token2022Program),
    ],
    data: getExecuteRedemptionInstructionDataEncoder().encode(
      args as ExecuteRedemptionInstructionDataArgs,
    ),
    programAddress,
  } as ExecuteRedemptionInstruction<
    TProgramAddress,
    TAccountOperator,
    TAccountRedemptionConfig,
    TAccountRedemptionOperation,
    TAccountOperatorPermissions,
    TAccountSpikoTokenProgram,
    TAccountTokenConfig,
    TAccountTokenMint,
    TAccountVault,
    TAccountMintAuthority,
    TAccountVaultAuthority,
    TAccountVaultAuthorityPermissions,
    TAccountToken2022Program
  >);
}

export type ParsedExecuteRedemptionInstruction<
  TProgram extends string = typeof REDEMPTION_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Operator (must have ROLE_REDEMPTION_EXECUTOR) */
    operator: TAccountMetas[0];
    /** RedemptionConfig PDA */
    redemptionConfig: TAccountMetas[1];
    /** RedemptionOperation PDA */
    redemptionOperation: TAccountMetas[2];
    /** Operator's UserPermissions PDA (from permission_manager) */
    operatorPermissions: TAccountMetas[3];
    /** Spiko Token program (for CPI: burn) */
    spikoTokenProgram: TAccountMetas[4];
    /** TokenConfig PDA (on spiko-token) */
    tokenConfig: TAccountMetas[5];
    /** Token-2022 Mint */
    tokenMint: TAccountMetas[6];
    /** Vault token account (source for burn) */
    vault: TAccountMetas[7];
    /** Mint authority PDA (spiko-token) */
    mintAuthority: TAccountMetas[8];
    /** Vault authority PDA. Seeds: ["vault"] */
    vaultAuthority: TAccountMetas[9];
    /** Vault authority's UserPermissions PDA (ROLE_BURNER) */
    vaultAuthorityPermissions: TAccountMetas[10];
    token2022Program: TAccountMetas[11];
  };
  data: ExecuteRedemptionInstructionData;
};

export function parseExecuteRedemptionInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedExecuteRedemptionInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 12) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      operator: getNextAccount(),
      redemptionConfig: getNextAccount(),
      redemptionOperation: getNextAccount(),
      operatorPermissions: getNextAccount(),
      spikoTokenProgram: getNextAccount(),
      tokenConfig: getNextAccount(),
      tokenMint: getNextAccount(),
      vault: getNextAccount(),
      mintAuthority: getNextAccount(),
      vaultAuthority: getNextAccount(),
      vaultAuthorityPermissions: getNextAccount(),
      token2022Program: getNextAccount(),
    },
    data: getExecuteRedemptionInstructionDataDecoder().decode(instruction.data),
  };
}
