/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { REDEMPTION_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const INITIALIZE_REDEMPTION_DISCRIMINATOR = new Uint8Array([0]);

export function getInitializeRedemptionDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 1).encode(
    INITIALIZE_REDEMPTION_DISCRIMINATOR,
  );
}

export type InitializeRedemptionInstruction<
  TProgram extends string = typeof REDEMPTION_PROGRAM_ADDRESS,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountRedemptionConfig extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? WritableSignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountRedemptionConfig extends string
        ? WritableAccount<TAccountRedemptionConfig>
        : TAccountRedemptionConfig,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type InitializeRedemptionInstructionData = {
  discriminator: ReadonlyUint8Array;
  permissionManager: Address;
};

export type InitializeRedemptionInstructionDataArgs = {
  permissionManager: Address;
};

export function getInitializeRedemptionInstructionDataEncoder(): FixedSizeEncoder<InitializeRedemptionInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 1)],
      ["permissionManager", getAddressEncoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: INITIALIZE_REDEMPTION_DISCRIMINATOR,
    }),
  );
}

export function getInitializeRedemptionInstructionDataDecoder(): FixedSizeDecoder<InitializeRedemptionInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 1)],
    ["permissionManager", getAddressDecoder()],
  ]);
}

export function getInitializeRedemptionInstructionDataCodec(): FixedSizeCodec<
  InitializeRedemptionInstructionDataArgs,
  InitializeRedemptionInstructionData
> {
  return combineCodec(
    getInitializeRedemptionInstructionDataEncoder(),
    getInitializeRedemptionInstructionDataDecoder(),
  );
}

export type InitializeRedemptionInput<
  TAccountAdmin extends string = string,
  TAccountRedemptionConfig extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** Admin / deployer (payer for PDA creation) */
  admin: TransactionSigner<TAccountAdmin>;
  /** RedemptionConfig PDA. Seeds: ["redemption_config"] */
  redemptionConfig: Address<TAccountRedemptionConfig>;
  systemProgram?: Address<TAccountSystemProgram>;
  permissionManager: InitializeRedemptionInstructionDataArgs["permissionManager"];
};

export function getInitializeRedemptionInstruction<
  TAccountAdmin extends string,
  TAccountRedemptionConfig extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof REDEMPTION_PROGRAM_ADDRESS,
>(
  input: InitializeRedemptionInput<
    TAccountAdmin,
    TAccountRedemptionConfig,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): InitializeRedemptionInstruction<
  TProgramAddress,
  TAccountAdmin,
  TAccountRedemptionConfig,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? REDEMPTION_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    redemptionConfig: {
      value: input.redemptionConfig ?? null,
      isWritable: true,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.admin),
      getAccountMeta(accounts.redemptionConfig),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getInitializeRedemptionInstructionDataEncoder().encode(
      args as InitializeRedemptionInstructionDataArgs,
    ),
    programAddress,
  } as InitializeRedemptionInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountRedemptionConfig,
    TAccountSystemProgram
  >);
}

export type ParsedInitializeRedemptionInstruction<
  TProgram extends string = typeof REDEMPTION_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Admin / deployer (payer for PDA creation) */
    admin: TAccountMetas[0];
    /** RedemptionConfig PDA. Seeds: ["redemption_config"] */
    redemptionConfig: TAccountMetas[1];
    systemProgram: TAccountMetas[2];
  };
  data: InitializeRedemptionInstructionData;
};

export function parseInitializeRedemptionInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedInitializeRedemptionInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      admin: getNextAccount(),
      redemptionConfig: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getInitializeRedemptionInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
