/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { REDEMPTION_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const ON_REDEEM_DISCRIMINATOR = new Uint8Array([4]);

export function getOnRedeemDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 1).encode(ON_REDEEM_DISCRIMINATOR);
}

export type OnRedeemInstruction<
  TProgram extends string = typeof REDEMPTION_PROGRAM_ADDRESS,
  TAccountTokenConfig extends string | AccountMeta<string> = string,
  TAccountUser extends string | AccountMeta<string> = string,
  TAccountRedemptionConfig extends string | AccountMeta<string> = string,
  TAccountRedemptionOperation extends string | AccountMeta<string> = string,
  TAccountTokenMinimum extends string | AccountMeta<string> = string,
  TAccountTokenMint extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountTokenConfig extends string
        ? ReadonlySignerAccount<TAccountTokenConfig> &
            AccountSignerMeta<TAccountTokenConfig>
        : TAccountTokenConfig,
      TAccountUser extends string
        ? WritableSignerAccount<TAccountUser> & AccountSignerMeta<TAccountUser>
        : TAccountUser,
      TAccountRedemptionConfig extends string
        ? ReadonlyAccount<TAccountRedemptionConfig>
        : TAccountRedemptionConfig,
      TAccountRedemptionOperation extends string
        ? WritableAccount<TAccountRedemptionOperation>
        : TAccountRedemptionOperation,
      TAccountTokenMinimum extends string
        ? ReadonlyAccount<TAccountTokenMinimum>
        : TAccountTokenMinimum,
      TAccountTokenMint extends string
        ? ReadonlyAccount<TAccountTokenMint>
        : TAccountTokenMint,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type OnRedeemInstructionData = {
  discriminator: ReadonlyUint8Array;
  userAddress: Address;
  amount: bigint;
  salt: bigint;
};

export type OnRedeemInstructionDataArgs = {
  userAddress: Address;
  amount: number | bigint;
  salt: number | bigint;
};

export function getOnRedeemInstructionDataEncoder(): FixedSizeEncoder<OnRedeemInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 1)],
      ["userAddress", getAddressEncoder()],
      ["amount", getU64Encoder()],
      ["salt", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: ON_REDEEM_DISCRIMINATOR }),
  );
}

export function getOnRedeemInstructionDataDecoder(): FixedSizeDecoder<OnRedeemInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 1)],
    ["userAddress", getAddressDecoder()],
    ["amount", getU64Decoder()],
    ["salt", getU64Decoder()],
  ]);
}

export function getOnRedeemInstructionDataCodec(): FixedSizeCodec<
  OnRedeemInstructionDataArgs,
  OnRedeemInstructionData
> {
  return combineCodec(
    getOnRedeemInstructionDataEncoder(),
    getOnRedeemInstructionDataDecoder(),
  );
}

export type OnRedeemInput<
  TAccountTokenConfig extends string = string,
  TAccountUser extends string = string,
  TAccountRedemptionConfig extends string = string,
  TAccountRedemptionOperation extends string = string,
  TAccountTokenMinimum extends string = string,
  TAccountTokenMint extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** TokenConfig PDA (from spiko_token, proves CPI origin) */
  tokenConfig: TransactionSigner<TAccountTokenConfig>;
  /** User (payer for PDA creation) */
  user: TransactionSigner<TAccountUser>;
  /** RedemptionConfig PDA */
  redemptionConfig: Address<TAccountRedemptionConfig>;
  /** RedemptionOperation PDA (to be created). Seeds: ["redemption_op", operation_id] */
  redemptionOperation: Address<TAccountRedemptionOperation>;
  /** TokenMinimum PDA */
  tokenMinimum: Address<TAccountTokenMinimum>;
  /** Token-2022 Mint */
  tokenMint: Address<TAccountTokenMint>;
  systemProgram?: Address<TAccountSystemProgram>;
  userAddress: OnRedeemInstructionDataArgs["userAddress"];
  amount: OnRedeemInstructionDataArgs["amount"];
  salt: OnRedeemInstructionDataArgs["salt"];
};

export function getOnRedeemInstruction<
  TAccountTokenConfig extends string,
  TAccountUser extends string,
  TAccountRedemptionConfig extends string,
  TAccountRedemptionOperation extends string,
  TAccountTokenMinimum extends string,
  TAccountTokenMint extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof REDEMPTION_PROGRAM_ADDRESS,
>(
  input: OnRedeemInput<
    TAccountTokenConfig,
    TAccountUser,
    TAccountRedemptionConfig,
    TAccountRedemptionOperation,
    TAccountTokenMinimum,
    TAccountTokenMint,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): OnRedeemInstruction<
  TProgramAddress,
  TAccountTokenConfig,
  TAccountUser,
  TAccountRedemptionConfig,
  TAccountRedemptionOperation,
  TAccountTokenMinimum,
  TAccountTokenMint,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? REDEMPTION_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    tokenConfig: { value: input.tokenConfig ?? null, isWritable: false },
    user: { value: input.user ?? null, isWritable: true },
    redemptionConfig: {
      value: input.redemptionConfig ?? null,
      isWritable: false,
    },
    redemptionOperation: {
      value: input.redemptionOperation ?? null,
      isWritable: true,
    },
    tokenMinimum: { value: input.tokenMinimum ?? null, isWritable: false },
    tokenMint: { value: input.tokenMint ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.tokenConfig),
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.redemptionConfig),
      getAccountMeta(accounts.redemptionOperation),
      getAccountMeta(accounts.tokenMinimum),
      getAccountMeta(accounts.tokenMint),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getOnRedeemInstructionDataEncoder().encode(
      args as OnRedeemInstructionDataArgs,
    ),
    programAddress,
  } as OnRedeemInstruction<
    TProgramAddress,
    TAccountTokenConfig,
    TAccountUser,
    TAccountRedemptionConfig,
    TAccountRedemptionOperation,
    TAccountTokenMinimum,
    TAccountTokenMint,
    TAccountSystemProgram
  >);
}

export type ParsedOnRedeemInstruction<
  TProgram extends string = typeof REDEMPTION_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** TokenConfig PDA (from spiko_token, proves CPI origin) */
    tokenConfig: TAccountMetas[0];
    /** User (payer for PDA creation) */
    user: TAccountMetas[1];
    /** RedemptionConfig PDA */
    redemptionConfig: TAccountMetas[2];
    /** RedemptionOperation PDA (to be created). Seeds: ["redemption_op", operation_id] */
    redemptionOperation: TAccountMetas[3];
    /** TokenMinimum PDA */
    tokenMinimum: TAccountMetas[4];
    /** Token-2022 Mint */
    tokenMint: TAccountMetas[5];
    systemProgram: TAccountMetas[6];
  };
  data: OnRedeemInstructionData;
};

export function parseOnRedeemInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedOnRedeemInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 7) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      tokenConfig: getNextAccount(),
      user: getNextAccount(),
      redemptionConfig: getNextAccount(),
      redemptionOperation: getNextAccount(),
      tokenMinimum: getNextAccount(),
      tokenMint: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getOnRedeemInstructionDataDecoder().decode(instruction.data),
  };
}
