/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { REDEMPTION_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const SET_MINIMUM_DISCRIMINATOR = new Uint8Array([3]);

export function getSetMinimumDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 1).encode(SET_MINIMUM_DISCRIMINATOR);
}

export type SetMinimumInstruction<
  TProgram extends string = typeof REDEMPTION_PROGRAM_ADDRESS,
  TAccountCaller extends string | AccountMeta<string> = string,
  TAccountRedemptionConfig extends string | AccountMeta<string> = string,
  TAccountPermissionConfig extends string | AccountMeta<string> = string,
  TAccountTokenMinimum extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountCaller extends string
        ? WritableSignerAccount<TAccountCaller> &
            AccountSignerMeta<TAccountCaller>
        : TAccountCaller,
      TAccountRedemptionConfig extends string
        ? ReadonlyAccount<TAccountRedemptionConfig>
        : TAccountRedemptionConfig,
      TAccountPermissionConfig extends string
        ? ReadonlyAccount<TAccountPermissionConfig>
        : TAccountPermissionConfig,
      TAccountTokenMinimum extends string
        ? WritableAccount<TAccountTokenMinimum>
        : TAccountTokenMinimum,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type SetMinimumInstructionData = {
  discriminator: ReadonlyUint8Array;
  tokenMintArg: Address;
  minimum: bigint;
};

export type SetMinimumInstructionDataArgs = {
  tokenMintArg: Address;
  minimum: number | bigint;
};

export function getSetMinimumInstructionDataEncoder(): FixedSizeEncoder<SetMinimumInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 1)],
      ["tokenMintArg", getAddressEncoder()],
      ["minimum", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: SET_MINIMUM_DISCRIMINATOR }),
  );
}

export function getSetMinimumInstructionDataDecoder(): FixedSizeDecoder<SetMinimumInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 1)],
    ["tokenMintArg", getAddressDecoder()],
    ["minimum", getU64Decoder()],
  ]);
}

export function getSetMinimumInstructionDataCodec(): FixedSizeCodec<
  SetMinimumInstructionDataArgs,
  SetMinimumInstructionData
> {
  return combineCodec(
    getSetMinimumInstructionDataEncoder(),
    getSetMinimumInstructionDataDecoder(),
  );
}

export type SetMinimumInput<
  TAccountCaller extends string = string,
  TAccountRedemptionConfig extends string = string,
  TAccountPermissionConfig extends string = string,
  TAccountTokenMinimum extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** Admin caller (payer if creating TokenMinimum PDA) */
  caller: TransactionSigner<TAccountCaller>;
  /** RedemptionConfig PDA (to read permission_manager) */
  redemptionConfig: Address<TAccountRedemptionConfig>;
  /** PermissionConfig PDA (from permission_manager, for admin check) */
  permissionConfig: Address<TAccountPermissionConfig>;
  /** TokenMinimum PDA (created if needed). Seeds: ["minimum", mint] */
  tokenMinimum: Address<TAccountTokenMinimum>;
  systemProgram?: Address<TAccountSystemProgram>;
  tokenMintArg: SetMinimumInstructionDataArgs["tokenMintArg"];
  minimum: SetMinimumInstructionDataArgs["minimum"];
};

export function getSetMinimumInstruction<
  TAccountCaller extends string,
  TAccountRedemptionConfig extends string,
  TAccountPermissionConfig extends string,
  TAccountTokenMinimum extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof REDEMPTION_PROGRAM_ADDRESS,
>(
  input: SetMinimumInput<
    TAccountCaller,
    TAccountRedemptionConfig,
    TAccountPermissionConfig,
    TAccountTokenMinimum,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): SetMinimumInstruction<
  TProgramAddress,
  TAccountCaller,
  TAccountRedemptionConfig,
  TAccountPermissionConfig,
  TAccountTokenMinimum,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? REDEMPTION_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    caller: { value: input.caller ?? null, isWritable: true },
    redemptionConfig: {
      value: input.redemptionConfig ?? null,
      isWritable: false,
    },
    permissionConfig: {
      value: input.permissionConfig ?? null,
      isWritable: false,
    },
    tokenMinimum: { value: input.tokenMinimum ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.caller),
      getAccountMeta(accounts.redemptionConfig),
      getAccountMeta(accounts.permissionConfig),
      getAccountMeta(accounts.tokenMinimum),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getSetMinimumInstructionDataEncoder().encode(
      args as SetMinimumInstructionDataArgs,
    ),
    programAddress,
  } as SetMinimumInstruction<
    TProgramAddress,
    TAccountCaller,
    TAccountRedemptionConfig,
    TAccountPermissionConfig,
    TAccountTokenMinimum,
    TAccountSystemProgram
  >);
}

export type ParsedSetMinimumInstruction<
  TProgram extends string = typeof REDEMPTION_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Admin caller (payer if creating TokenMinimum PDA) */
    caller: TAccountMetas[0];
    /** RedemptionConfig PDA (to read permission_manager) */
    redemptionConfig: TAccountMetas[1];
    /** PermissionConfig PDA (from permission_manager, for admin check) */
    permissionConfig: TAccountMetas[2];
    /** TokenMinimum PDA (created if needed). Seeds: ["minimum", mint] */
    tokenMinimum: TAccountMetas[3];
    systemProgram: TAccountMetas[4];
  };
  data: SetMinimumInstructionData;
};

export function parseSetMinimumInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedSetMinimumInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      caller: getNextAccount(),
      redemptionConfig: getNextAccount(),
      permissionConfig: getNextAccount(),
      tokenMinimum: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getSetMinimumInstructionDataDecoder().decode(instruction.data),
  };
}
