/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const REDEMPTION_CONFIG_DISCRIMINATOR = new Uint8Array([1]);

export function getRedemptionConfigDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 1).encode(
    REDEMPTION_CONFIG_DISCRIMINATOR,
  );
}

export type RedemptionConfig = {
  discriminator: ReadonlyUint8Array;
  bump: number;
  permissionManager: Address;
};

export type RedemptionConfigArgs = { bump: number; permissionManager: Address };

/** Gets the encoder for {@link RedemptionConfigArgs} account data. */
export function getRedemptionConfigEncoder(): FixedSizeEncoder<RedemptionConfigArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 1)],
      ["bump", getU8Encoder()],
      ["permissionManager", getAddressEncoder()],
    ]),
    (value) => ({ ...value, discriminator: REDEMPTION_CONFIG_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link RedemptionConfig} account data. */
export function getRedemptionConfigDecoder(): FixedSizeDecoder<RedemptionConfig> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 1)],
    ["bump", getU8Decoder()],
    ["permissionManager", getAddressDecoder()],
  ]);
}

/** Gets the codec for {@link RedemptionConfig} account data. */
export function getRedemptionConfigCodec(): FixedSizeCodec<
  RedemptionConfigArgs,
  RedemptionConfig
> {
  return combineCodec(
    getRedemptionConfigEncoder(),
    getRedemptionConfigDecoder(),
  );
}

export function decodeRedemptionConfig<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<RedemptionConfig, TAddress>;
export function decodeRedemptionConfig<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<RedemptionConfig, TAddress>;
export function decodeRedemptionConfig<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
):
  | Account<RedemptionConfig, TAddress>
  | MaybeAccount<RedemptionConfig, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getRedemptionConfigDecoder(),
  );
}

export async function fetchRedemptionConfig<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<RedemptionConfig, TAddress>> {
  const maybeAccount = await fetchMaybeRedemptionConfig(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeRedemptionConfig<
  TAddress extends string = string,
>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<RedemptionConfig, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeRedemptionConfig(maybeAccount);
}

export async function fetchAllRedemptionConfig(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<RedemptionConfig>[]> {
  const maybeAccounts = await fetchAllMaybeRedemptionConfig(
    rpc,
    addresses,
    config,
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeRedemptionConfig(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<RedemptionConfig>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) =>
    decodeRedemptionConfig(maybeAccount),
  );
}

export function getRedemptionConfigSize(): number {
  return 34;
}
