/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const REDEMPTION_OPERATION_DISCRIMINATOR = new Uint8Array([4]);

export function getRedemptionOperationDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 1).encode(
    REDEMPTION_OPERATION_DISCRIMINATOR,
  );
}

export type RedemptionOperation = {
  discriminator: ReadonlyUint8Array;
  bump: number;
  status: number;
  deadline: bigint;
  user: Address;
};

export type RedemptionOperationArgs = {
  bump: number;
  status: number;
  deadline: number | bigint;
  user: Address;
};

/** Gets the encoder for {@link RedemptionOperationArgs} account data. */
export function getRedemptionOperationEncoder(): FixedSizeEncoder<RedemptionOperationArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 1)],
      ["bump", getU8Encoder()],
      ["status", getU8Encoder()],
      ["deadline", getI64Encoder()],
      ["user", getAddressEncoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: REDEMPTION_OPERATION_DISCRIMINATOR,
    }),
  );
}

/** Gets the decoder for {@link RedemptionOperation} account data. */
export function getRedemptionOperationDecoder(): FixedSizeDecoder<RedemptionOperation> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 1)],
    ["bump", getU8Decoder()],
    ["status", getU8Decoder()],
    ["deadline", getI64Decoder()],
    ["user", getAddressDecoder()],
  ]);
}

/** Gets the codec for {@link RedemptionOperation} account data. */
export function getRedemptionOperationCodec(): FixedSizeCodec<
  RedemptionOperationArgs,
  RedemptionOperation
> {
  return combineCodec(
    getRedemptionOperationEncoder(),
    getRedemptionOperationDecoder(),
  );
}

export function decodeRedemptionOperation<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<RedemptionOperation, TAddress>;
export function decodeRedemptionOperation<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<RedemptionOperation, TAddress>;
export function decodeRedemptionOperation<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
):
  | Account<RedemptionOperation, TAddress>
  | MaybeAccount<RedemptionOperation, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getRedemptionOperationDecoder(),
  );
}

export async function fetchRedemptionOperation<
  TAddress extends string = string,
>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<RedemptionOperation, TAddress>> {
  const maybeAccount = await fetchMaybeRedemptionOperation(
    rpc,
    address,
    config,
  );
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeRedemptionOperation<
  TAddress extends string = string,
>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<RedemptionOperation, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeRedemptionOperation(maybeAccount);
}

export async function fetchAllRedemptionOperation(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<RedemptionOperation>[]> {
  const maybeAccounts = await fetchAllMaybeRedemptionOperation(
    rpc,
    addresses,
    config,
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeRedemptionOperation(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<RedemptionOperation>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) =>
    decodeRedemptionOperation(maybeAccount),
  );
}

export function getRedemptionOperationSize(): number {
  return 43;
}
