/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const TOKEN_MINIMUM_DISCRIMINATOR = new Uint8Array([2]);

export function getTokenMinimumDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 1).encode(
    TOKEN_MINIMUM_DISCRIMINATOR,
  );
}

export type TokenMinimum = {
  discriminator: ReadonlyUint8Array;
  bump: number;
  minimumAmount: bigint;
};

export type TokenMinimumArgs = { bump: number; minimumAmount: number | bigint };

/** Gets the encoder for {@link TokenMinimumArgs} account data. */
export function getTokenMinimumEncoder(): FixedSizeEncoder<TokenMinimumArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 1)],
      ["bump", getU8Encoder()],
      ["minimumAmount", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: TOKEN_MINIMUM_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link TokenMinimum} account data. */
export function getTokenMinimumDecoder(): FixedSizeDecoder<TokenMinimum> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 1)],
    ["bump", getU8Decoder()],
    ["minimumAmount", getU64Decoder()],
  ]);
}

/** Gets the codec for {@link TokenMinimum} account data. */
export function getTokenMinimumCodec(): FixedSizeCodec<
  TokenMinimumArgs,
  TokenMinimum
> {
  return combineCodec(getTokenMinimumEncoder(), getTokenMinimumDecoder());
}

export function decodeTokenMinimum<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<TokenMinimum, TAddress>;
export function decodeTokenMinimum<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<TokenMinimum, TAddress>;
export function decodeTokenMinimum<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<TokenMinimum, TAddress> | MaybeAccount<TokenMinimum, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getTokenMinimumDecoder(),
  );
}

export async function fetchTokenMinimum<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<TokenMinimum, TAddress>> {
  const maybeAccount = await fetchMaybeTokenMinimum(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeTokenMinimum<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<TokenMinimum, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeTokenMinimum(maybeAccount);
}

export async function fetchAllTokenMinimum(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<TokenMinimum>[]> {
  const maybeAccounts = await fetchAllMaybeTokenMinimum(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeTokenMinimum(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<TokenMinimum>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeTokenMinimum(maybeAccount));
}

export function getTokenMinimumSize(): number {
  return 10;
}
