/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const TOKEN_CONFIG_DISCRIMINATOR = new Uint8Array([1]);

export function getTokenConfigDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 1).encode(
    TOKEN_CONFIG_DISCRIMINATOR,
  );
}

export type TokenConfig = {
  discriminator: ReadonlyUint8Array;
  bump: number;
  paused: number;
  mintAuthorityBump: number;
  permissionManager: Address;
  splMint: Address;
  redemptionContract: Address;
};

export type TokenConfigArgs = {
  bump: number;
  paused: number;
  mintAuthorityBump: number;
  permissionManager: Address;
  splMint: Address;
  redemptionContract: Address;
};

/** Gets the encoder for {@link TokenConfigArgs} account data. */
export function getTokenConfigEncoder(): FixedSizeEncoder<TokenConfigArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 1)],
      ["bump", getU8Encoder()],
      ["paused", getU8Encoder()],
      ["mintAuthorityBump", getU8Encoder()],
      ["permissionManager", getAddressEncoder()],
      ["splMint", getAddressEncoder()],
      ["redemptionContract", getAddressEncoder()],
    ]),
    (value) => ({ ...value, discriminator: TOKEN_CONFIG_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link TokenConfig} account data. */
export function getTokenConfigDecoder(): FixedSizeDecoder<TokenConfig> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 1)],
    ["bump", getU8Decoder()],
    ["paused", getU8Decoder()],
    ["mintAuthorityBump", getU8Decoder()],
    ["permissionManager", getAddressDecoder()],
    ["splMint", getAddressDecoder()],
    ["redemptionContract", getAddressDecoder()],
  ]);
}

/** Gets the codec for {@link TokenConfig} account data. */
export function getTokenConfigCodec(): FixedSizeCodec<
  TokenConfigArgs,
  TokenConfig
> {
  return combineCodec(getTokenConfigEncoder(), getTokenConfigDecoder());
}

export function decodeTokenConfig<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<TokenConfig, TAddress>;
export function decodeTokenConfig<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<TokenConfig, TAddress>;
export function decodeTokenConfig<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<TokenConfig, TAddress> | MaybeAccount<TokenConfig, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getTokenConfigDecoder(),
  );
}

export async function fetchTokenConfig<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<TokenConfig, TAddress>> {
  const maybeAccount = await fetchMaybeTokenConfig(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeTokenConfig<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<TokenConfig, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeTokenConfig(maybeAccount);
}

export async function fetchAllTokenConfig(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<TokenConfig>[]> {
  const maybeAccounts = await fetchAllMaybeTokenConfig(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeTokenConfig(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<TokenConfig>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeTokenConfig(maybeAccount));
}

export function getTokenConfigSize(): number {
  return 100;
}
