[package]
name = "minter"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build", "permission-manager/idl-build", "spiko-token/idl-build"]

[dependencies]
anchor-lang = { workspace = true, features = ["init-if-needed"] }
anchor-spl = { workspace = true }
permission-manager = { path = "../permission-manager", features = ["cpi"] }
spiko-token = { path = "../spiko-token", features = ["cpi"] }
solana-sha256-hasher = { workspace = true }

[dev-dependencies]
litesvm = { workspace = true }
solana-sdk = "3"
solana-sdk-ids = "3"
solana-system-interface = "2"
spl-token-2022-interface = "2.1.0"
solana-program-pack = "3"
permission-manager = { path = "../permission-manager", features = ["no-entrypoint"] }
spiko-token = { path = "../spiko-token", features = ["no-entrypoint"] }

[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(feature, values("custom-heap", "custom-allocator", "anchor-debug"))'] }