/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertIsInstructionWithAccounts,
  containsBytes,
  fixEncoderSize,
  getBytesEncoder,
  type Address,
  type Instruction,
  type InstructionWithData,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  parseBurnFromInstruction,
  parseBurnTokenInstruction,
  parseInitializeTokenInstruction,
  parseMintTokenInstruction,
  parsePauseInstruction,
  parseRedeemTokenInstruction,
  parseSetRedemptionContractInstruction,
  parseTransferTokenInstruction,
  parseUnpauseInstruction,
  type ParsedBurnFromInstruction,
  type ParsedBurnTokenInstruction,
  type ParsedInitializeTokenInstruction,
  type ParsedMintTokenInstruction,
  type ParsedPauseInstruction,
  type ParsedRedeemTokenInstruction,
  type ParsedSetRedemptionContractInstruction,
  type ParsedTransferTokenInstruction,
  type ParsedUnpauseInstruction,
} from "../instructions";

export const SPIKO_TOKEN_PROGRAM_ADDRESS =
  "2LKr4wYMkx75hCbrmRCR2iESCWmeDViuSDLxZaZnC4aP" as Address<"2LKr4wYMkx75hCbrmRCR2iESCWmeDViuSDLxZaZnC4aP">;

export enum SpikoTokenAccount {
  TokenConfig,
}

export function identifySpikoTokenAccount(
  account: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): SpikoTokenAccount {
  const data = "data" in account ? account.data : account;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 1).encode(new Uint8Array([1])),
      0,
    )
  ) {
    return SpikoTokenAccount.TokenConfig;
  }
  throw new Error(
    "The provided account could not be identified as a spikoToken account.",
  );
}

export enum SpikoTokenInstruction {
  InitializeToken,
  MintToken,
  BurnToken,
  TransferToken,
  Pause,
  Unpause,
  RedeemToken,
  SetRedemptionContract,
  BurnFrom,
}

export function identifySpikoTokenInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): SpikoTokenInstruction {
  const data = "data" in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 1).encode(new Uint8Array([0])),
      0,
    )
  ) {
    return SpikoTokenInstruction.InitializeToken;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 1).encode(new Uint8Array([1])),
      0,
    )
  ) {
    return SpikoTokenInstruction.MintToken;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 1).encode(new Uint8Array([2])),
      0,
    )
  ) {
    return SpikoTokenInstruction.BurnToken;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 1).encode(new Uint8Array([3])),
      0,
    )
  ) {
    return SpikoTokenInstruction.TransferToken;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 1).encode(new Uint8Array([4])),
      0,
    )
  ) {
    return SpikoTokenInstruction.Pause;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 1).encode(new Uint8Array([5])),
      0,
    )
  ) {
    return SpikoTokenInstruction.Unpause;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 1).encode(new Uint8Array([6])),
      0,
    )
  ) {
    return SpikoTokenInstruction.RedeemToken;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 1).encode(new Uint8Array([7])),
      0,
    )
  ) {
    return SpikoTokenInstruction.SetRedemptionContract;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 1).encode(new Uint8Array([8])),
      0,
    )
  ) {
    return SpikoTokenInstruction.BurnFrom;
  }
  throw new Error(
    "The provided instruction could not be identified as a spikoToken instruction.",
  );
}

export type ParsedSpikoTokenInstruction<
  TProgram extends string = "2LKr4wYMkx75hCbrmRCR2iESCWmeDViuSDLxZaZnC4aP",
> =
  | ({
      instructionType: SpikoTokenInstruction.InitializeToken;
    } & ParsedInitializeTokenInstruction<TProgram>)
  | ({
      instructionType: SpikoTokenInstruction.MintToken;
    } & ParsedMintTokenInstruction<TProgram>)
  | ({
      instructionType: SpikoTokenInstruction.BurnToken;
    } & ParsedBurnTokenInstruction<TProgram>)
  | ({
      instructionType: SpikoTokenInstruction.TransferToken;
    } & ParsedTransferTokenInstruction<TProgram>)
  | ({
      instructionType: SpikoTokenInstruction.Pause;
    } & ParsedPauseInstruction<TProgram>)
  | ({
      instructionType: SpikoTokenInstruction.Unpause;
    } & ParsedUnpauseInstruction<TProgram>)
  | ({
      instructionType: SpikoTokenInstruction.RedeemToken;
    } & ParsedRedeemTokenInstruction<TProgram>)
  | ({
      instructionType: SpikoTokenInstruction.SetRedemptionContract;
    } & ParsedSetRedemptionContractInstruction<TProgram>)
  | ({
      instructionType: SpikoTokenInstruction.BurnFrom;
    } & ParsedBurnFromInstruction<TProgram>);

export function parseSpikoTokenInstruction<TProgram extends string>(
  instruction: Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array>,
): ParsedSpikoTokenInstruction<TProgram> {
  const instructionType = identifySpikoTokenInstruction(instruction);
  switch (instructionType) {
    case SpikoTokenInstruction.InitializeToken: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SpikoTokenInstruction.InitializeToken,
        ...parseInitializeTokenInstruction(instruction),
      };
    }
    case SpikoTokenInstruction.MintToken: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SpikoTokenInstruction.MintToken,
        ...parseMintTokenInstruction(instruction),
      };
    }
    case SpikoTokenInstruction.BurnToken: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SpikoTokenInstruction.BurnToken,
        ...parseBurnTokenInstruction(instruction),
      };
    }
    case SpikoTokenInstruction.TransferToken: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SpikoTokenInstruction.TransferToken,
        ...parseTransferTokenInstruction(instruction),
      };
    }
    case SpikoTokenInstruction.Pause: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SpikoTokenInstruction.Pause,
        ...parsePauseInstruction(instruction),
      };
    }
    case SpikoTokenInstruction.Unpause: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SpikoTokenInstruction.Unpause,
        ...parseUnpauseInstruction(instruction),
      };
    }
    case SpikoTokenInstruction.RedeemToken: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SpikoTokenInstruction.RedeemToken,
        ...parseRedeemTokenInstruction(instruction),
      };
    }
    case SpikoTokenInstruction.SetRedemptionContract: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SpikoTokenInstruction.SetRedemptionContract,
        ...parseSetRedemptionContractInstruction(instruction),
      };
    }
    case SpikoTokenInstruction.BurnFrom: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: SpikoTokenInstruction.BurnFrom,
        ...parseBurnFromInstruction(instruction),
      };
    }
    default:
      throw new Error(
        `Unrecognized instruction type: ${instructionType as string}`,
      );
  }
}
