/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type Burn = {
  caller: Address;
  mint: Address;
  sourceAta: Address;
  amount: bigint;
};

export type BurnArgs = {
  caller: Address;
  mint: Address;
  sourceAta: Address;
  amount: number | bigint;
};

export function getBurnEncoder(): FixedSizeEncoder<BurnArgs> {
  return getStructEncoder([
    ["caller", getAddressEncoder()],
    ["mint", getAddressEncoder()],
    ["sourceAta", getAddressEncoder()],
    ["amount", getU64Encoder()],
  ]);
}

export function getBurnDecoder(): FixedSizeDecoder<Burn> {
  return getStructDecoder([
    ["caller", getAddressDecoder()],
    ["mint", getAddressDecoder()],
    ["sourceAta", getAddressDecoder()],
    ["amount", getU64Decoder()],
  ]);
}

export function getBurnCodec(): FixedSizeCodec<BurnArgs, Burn> {
  return combineCodec(getBurnEncoder(), getBurnDecoder());
}
