/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type Mint = {
  caller: Address;
  mint: Address;
  recipientAta: Address;
  amount: bigint;
};

export type MintArgs = {
  caller: Address;
  mint: Address;
  recipientAta: Address;
  amount: number | bigint;
};

export function getMintEncoder(): FixedSizeEncoder<MintArgs> {
  return getStructEncoder([
    ["caller", getAddressEncoder()],
    ["mint", getAddressEncoder()],
    ["recipientAta", getAddressEncoder()],
    ["amount", getU64Encoder()],
  ]);
}

export function getMintDecoder(): FixedSizeDecoder<Mint> {
  return getStructDecoder([
    ["caller", getAddressDecoder()],
    ["mint", getAddressDecoder()],
    ["recipientAta", getAddressDecoder()],
    ["amount", getU64Decoder()],
  ]);
}

export function getMintCodec(): FixedSizeCodec<MintArgs, Mint> {
  return combineCodec(getMintEncoder(), getMintDecoder());
}
