/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type RedemptionContractSet = {
  caller: Address;
  config: Address;
  contract: Address;
};

export type RedemptionContractSetArgs = RedemptionContractSet;

export function getRedemptionContractSetEncoder(): FixedSizeEncoder<RedemptionContractSetArgs> {
  return getStructEncoder([
    ["caller", getAddressEncoder()],
    ["config", getAddressEncoder()],
    ["contract", getAddressEncoder()],
  ]);
}

export function getRedemptionContractSetDecoder(): FixedSizeDecoder<RedemptionContractSet> {
  return getStructDecoder([
    ["caller", getAddressDecoder()],
    ["config", getAddressDecoder()],
    ["contract", getAddressDecoder()],
  ]);
}

export function getRedemptionContractSetCodec(): FixedSizeCodec<
  RedemptionContractSetArgs,
  RedemptionContractSet
> {
  return combineCodec(
    getRedemptionContractSetEncoder(),
    getRedemptionContractSetDecoder(),
  );
}
