/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type RedeemInitiated = {
  user: Address;
  mint: Address;
  amount: bigint;
  salt: bigint;
};

export type RedeemInitiatedArgs = {
  user: Address;
  mint: Address;
  amount: number | bigint;
  salt: number | bigint;
};

export function getRedeemInitiatedEncoder(): FixedSizeEncoder<RedeemInitiatedArgs> {
  return getStructEncoder([
    ["user", getAddressEncoder()],
    ["mint", getAddressEncoder()],
    ["amount", getU64Encoder()],
    ["salt", getU64Encoder()],
  ]);
}

export function getRedeemInitiatedDecoder(): FixedSizeDecoder<RedeemInitiated> {
  return getStructDecoder([
    ["user", getAddressDecoder()],
    ["mint", getAddressDecoder()],
    ["amount", getU64Decoder()],
    ["salt", getU64Decoder()],
  ]);
}

export function getRedeemInitiatedCodec(): FixedSizeCodec<
  RedeemInitiatedArgs,
  RedeemInitiated
> {
  return combineCodec(getRedeemInitiatedEncoder(), getRedeemInitiatedDecoder());
}
