/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type TokenInitialized = { admin: Address; mint: Address };

export type TokenInitializedArgs = TokenInitialized;

export function getTokenInitializedEncoder(): FixedSizeEncoder<TokenInitializedArgs> {
  return getStructEncoder([
    ["admin", getAddressEncoder()],
    ["mint", getAddressEncoder()],
  ]);
}

export function getTokenInitializedDecoder(): FixedSizeDecoder<TokenInitialized> {
  return getStructDecoder([
    ["admin", getAddressDecoder()],
    ["mint", getAddressDecoder()],
  ]);
}

export function getTokenInitializedCodec(): FixedSizeCodec<
  TokenInitializedArgs,
  TokenInitialized
> {
  return combineCodec(
    getTokenInitializedEncoder(),
    getTokenInitializedDecoder(),
  );
}
