/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type TokenPaused = { caller: Address; config: Address };

export type TokenPausedArgs = TokenPaused;

export function getTokenPausedEncoder(): FixedSizeEncoder<TokenPausedArgs> {
  return getStructEncoder([
    ["caller", getAddressEncoder()],
    ["config", getAddressEncoder()],
  ]);
}

export function getTokenPausedDecoder(): FixedSizeDecoder<TokenPaused> {
  return getStructDecoder([
    ["caller", getAddressDecoder()],
    ["config", getAddressDecoder()],
  ]);
}

export function getTokenPausedCodec(): FixedSizeCodec<
  TokenPausedArgs,
  TokenPaused
> {
  return combineCodec(getTokenPausedEncoder(), getTokenPausedDecoder());
}
