/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type TokenUnpaused = { caller: Address; config: Address };

export type TokenUnpausedArgs = TokenUnpaused;

export function getTokenUnpausedEncoder(): FixedSizeEncoder<TokenUnpausedArgs> {
  return getStructEncoder([
    ["caller", getAddressEncoder()],
    ["config", getAddressEncoder()],
  ]);
}

export function getTokenUnpausedDecoder(): FixedSizeDecoder<TokenUnpaused> {
  return getStructDecoder([
    ["caller", getAddressDecoder()],
    ["config", getAddressDecoder()],
  ]);
}

export function getTokenUnpausedCodec(): FixedSizeCodec<
  TokenUnpausedArgs,
  TokenUnpaused
> {
  return combineCodec(getTokenUnpausedEncoder(), getTokenUnpausedDecoder());
}
