/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertIsInstructionWithAccounts,
  containsBytes,
  fixEncoderSize,
  getBytesEncoder,
  type Address,
  type Instruction,
  type InstructionWithData,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  parseAcceptOwnershipInstruction,
  parseGrantRoleInstruction,
  parseInitializeInstruction,
  parseRevokeRoleInstruction,
  parseTransferOwnershipInstruction,
  type ParsedAcceptOwnershipInstruction,
  type ParsedGrantRoleInstruction,
  type ParsedInitializeInstruction,
  type ParsedRevokeRoleInstruction,
  type ParsedTransferOwnershipInstruction,
} from "../instructions";

export const PERMISSION_MANAGER_PROGRAM_ADDRESS =
  "BTZTjmY3i1ZPFkUvZAwD3WzwQFxxLXeaCYYBNjHKuRoz" as Address<"BTZTjmY3i1ZPFkUvZAwD3WzwQFxxLXeaCYYBNjHKuRoz">;

export enum PermissionManagerAccount {
  PermissionConfig,
  UserPermissions,
}

export function identifyPermissionManagerAccount(
  account: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): PermissionManagerAccount {
  const data = "data" in account ? account.data : account;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 1).encode(new Uint8Array([1])),
      0,
    )
  ) {
    return PermissionManagerAccount.PermissionConfig;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 1).encode(new Uint8Array([2])),
      0,
    )
  ) {
    return PermissionManagerAccount.UserPermissions;
  }
  throw new Error(
    "The provided account could not be identified as a permissionManager account.",
  );
}

export enum PermissionManagerInstruction {
  Initialize,
  GrantRole,
  RevokeRole,
  TransferOwnership,
  AcceptOwnership,
}

export function identifyPermissionManagerInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): PermissionManagerInstruction {
  const data = "data" in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 1).encode(new Uint8Array([0])),
      0,
    )
  ) {
    return PermissionManagerInstruction.Initialize;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 1).encode(new Uint8Array([1])),
      0,
    )
  ) {
    return PermissionManagerInstruction.GrantRole;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 1).encode(new Uint8Array([2])),
      0,
    )
  ) {
    return PermissionManagerInstruction.RevokeRole;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 1).encode(new Uint8Array([3])),
      0,
    )
  ) {
    return PermissionManagerInstruction.TransferOwnership;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 1).encode(new Uint8Array([4])),
      0,
    )
  ) {
    return PermissionManagerInstruction.AcceptOwnership;
  }
  throw new Error(
    "The provided instruction could not be identified as a permissionManager instruction.",
  );
}

export type ParsedPermissionManagerInstruction<
  TProgram extends string = "BTZTjmY3i1ZPFkUvZAwD3WzwQFxxLXeaCYYBNjHKuRoz",
> =
  | ({
      instructionType: PermissionManagerInstruction.Initialize;
    } & ParsedInitializeInstruction<TProgram>)
  | ({
      instructionType: PermissionManagerInstruction.GrantRole;
    } & ParsedGrantRoleInstruction<TProgram>)
  | ({
      instructionType: PermissionManagerInstruction.RevokeRole;
    } & ParsedRevokeRoleInstruction<TProgram>)
  | ({
      instructionType: PermissionManagerInstruction.TransferOwnership;
    } & ParsedTransferOwnershipInstruction<TProgram>)
  | ({
      instructionType: PermissionManagerInstruction.AcceptOwnership;
    } & ParsedAcceptOwnershipInstruction<TProgram>);

export function parsePermissionManagerInstruction<TProgram extends string>(
  instruction: Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array>,
): ParsedPermissionManagerInstruction<TProgram> {
  const instructionType = identifyPermissionManagerInstruction(instruction);
  switch (instructionType) {
    case PermissionManagerInstruction.Initialize: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: PermissionManagerInstruction.Initialize,
        ...parseInitializeInstruction(instruction),
      };
    }
    case PermissionManagerInstruction.GrantRole: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: PermissionManagerInstruction.GrantRole,
        ...parseGrantRoleInstruction(instruction),
      };
    }
    case PermissionManagerInstruction.RevokeRole: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: PermissionManagerInstruction.RevokeRole,
        ...parseRevokeRoleInstruction(instruction),
      };
    }
    case PermissionManagerInstruction.TransferOwnership: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: PermissionManagerInstruction.TransferOwnership,
        ...parseTransferOwnershipInstruction(instruction),
      };
    }
    case PermissionManagerInstruction.AcceptOwnership: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: PermissionManagerInstruction.AcceptOwnership,
        ...parseAcceptOwnershipInstruction(instruction),
      };
    }
    default:
      throw new Error(
        `Unrecognized instruction type: ${instructionType as string}`,
      );
  }
}
