/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type OwnershipTransferStarted = { admin: Address; newAdmin: Address };

export type OwnershipTransferStartedArgs = OwnershipTransferStarted;

export function getOwnershipTransferStartedEncoder(): FixedSizeEncoder<OwnershipTransferStartedArgs> {
  return getStructEncoder([
    ["admin", getAddressEncoder()],
    ["newAdmin", getAddressEncoder()],
  ]);
}

export function getOwnershipTransferStartedDecoder(): FixedSizeDecoder<OwnershipTransferStarted> {
  return getStructDecoder([
    ["admin", getAddressDecoder()],
    ["newAdmin", getAddressDecoder()],
  ]);
}

export function getOwnershipTransferStartedCodec(): FixedSizeCodec<
  OwnershipTransferStartedArgs,
  OwnershipTransferStarted
> {
  return combineCodec(
    getOwnershipTransferStartedEncoder(),
    getOwnershipTransferStartedDecoder(),
  );
}
