/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type OwnershipTransferred = { newAdmin: Address };

export type OwnershipTransferredArgs = OwnershipTransferred;

export function getOwnershipTransferredEncoder(): FixedSizeEncoder<OwnershipTransferredArgs> {
  return getStructEncoder([["newAdmin", getAddressEncoder()]]);
}

export function getOwnershipTransferredDecoder(): FixedSizeDecoder<OwnershipTransferred> {
  return getStructDecoder([["newAdmin", getAddressDecoder()]]);
}

export function getOwnershipTransferredCodec(): FixedSizeCodec<
  OwnershipTransferredArgs,
  OwnershipTransferred
> {
  return combineCodec(
    getOwnershipTransferredEncoder(),
    getOwnershipTransferredDecoder(),
  );
}
