/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type PermissionManagerInitialized = { admin: Address };

export type PermissionManagerInitializedArgs = PermissionManagerInitialized;

export function getPermissionManagerInitializedEncoder(): FixedSizeEncoder<PermissionManagerInitializedArgs> {
  return getStructEncoder([["admin", getAddressEncoder()]]);
}

export function getPermissionManagerInitializedDecoder(): FixedSizeDecoder<PermissionManagerInitialized> {
  return getStructDecoder([["admin", getAddressDecoder()]]);
}

export function getPermissionManagerInitializedCodec(): FixedSizeCodec<
  PermissionManagerInitializedArgs,
  PermissionManagerInitialized
> {
  return combineCodec(
    getPermissionManagerInitializedEncoder(),
    getPermissionManagerInitializedDecoder(),
  );
}
