/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type RoleRemoved = { caller: Address; target: Address; roleId: number };

export type RoleRemovedArgs = RoleRemoved;

export function getRoleRemovedEncoder(): FixedSizeEncoder<RoleRemovedArgs> {
  return getStructEncoder([
    ["caller", getAddressEncoder()],
    ["target", getAddressEncoder()],
    ["roleId", getU8Encoder()],
  ]);
}

export function getRoleRemovedDecoder(): FixedSizeDecoder<RoleRemoved> {
  return getStructDecoder([
    ["caller", getAddressDecoder()],
    ["target", getAddressDecoder()],
    ["roleId", getU8Decoder()],
  ]);
}

export function getRoleRemovedCodec(): FixedSizeCodec<
  RoleRemovedArgs,
  RoleRemoved
> {
  return combineCodec(getRoleRemovedEncoder(), getRoleRemovedDecoder());
}
