/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import { SPIKO_TOKEN_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const BURN_TOKEN_DISCRIMINATOR = new Uint8Array([2]);

export function getBurnTokenDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 1).encode(BURN_TOKEN_DISCRIMINATOR);
}

export type BurnTokenInstruction<
  TProgram extends string = typeof SPIKO_TOKEN_PROGRAM_ADDRESS,
  TAccountCaller extends string | AccountMeta<string> = string,
  TAccountTokenConfig extends string | AccountMeta<string> = string,
  TAccountMint extends string | AccountMeta<string> = string,
  TAccountSourceTokenAccount extends string | AccountMeta<string> = string,
  TAccountMintAuthority extends string | AccountMeta<string> = string,
  TAccountCallerPermissions extends string | AccountMeta<string> = string,
  TAccountToken2022Program extends string | AccountMeta<string> =
    "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountCaller extends string
        ? ReadonlySignerAccount<TAccountCaller> &
            AccountSignerMeta<TAccountCaller>
        : TAccountCaller,
      TAccountTokenConfig extends string
        ? ReadonlyAccount<TAccountTokenConfig>
        : TAccountTokenConfig,
      TAccountMint extends string
        ? WritableAccount<TAccountMint>
        : TAccountMint,
      TAccountSourceTokenAccount extends string
        ? WritableAccount<TAccountSourceTokenAccount>
        : TAccountSourceTokenAccount,
      TAccountMintAuthority extends string
        ? ReadonlyAccount<TAccountMintAuthority>
        : TAccountMintAuthority,
      TAccountCallerPermissions extends string
        ? ReadonlyAccount<TAccountCallerPermissions>
        : TAccountCallerPermissions,
      TAccountToken2022Program extends string
        ? ReadonlyAccount<TAccountToken2022Program>
        : TAccountToken2022Program,
      ...TRemainingAccounts,
    ]
  >;

export type BurnTokenInstructionData = {
  discriminator: ReadonlyUint8Array;
  amount: bigint;
};

export type BurnTokenInstructionDataArgs = { amount: number | bigint };

export function getBurnTokenInstructionDataEncoder(): FixedSizeEncoder<BurnTokenInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 1)],
      ["amount", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: BURN_TOKEN_DISCRIMINATOR }),
  );
}

export function getBurnTokenInstructionDataDecoder(): FixedSizeDecoder<BurnTokenInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 1)],
    ["amount", getU64Decoder()],
  ]);
}

export function getBurnTokenInstructionDataCodec(): FixedSizeCodec<
  BurnTokenInstructionDataArgs,
  BurnTokenInstructionData
> {
  return combineCodec(
    getBurnTokenInstructionDataEncoder(),
    getBurnTokenInstructionDataDecoder(),
  );
}

export type BurnTokenInput<
  TAccountCaller extends string = string,
  TAccountTokenConfig extends string = string,
  TAccountMint extends string = string,
  TAccountSourceTokenAccount extends string = string,
  TAccountMintAuthority extends string = string,
  TAccountCallerPermissions extends string = string,
  TAccountToken2022Program extends string = string,
> = {
  /** Caller (must have BURNER role) */
  caller: TransactionSigner<TAccountCaller>;
  /** TokenConfig PDA */
  tokenConfig: Address<TAccountTokenConfig>;
  /** Token-2022 Mint */
  mint: Address<TAccountMint>;
  /** Source token account */
  sourceTokenAccount: Address<TAccountSourceTokenAccount>;
  /** Mint authority PDA (acts as authority for burn) */
  mintAuthority: Address<TAccountMintAuthority>;
  /** Caller's UserPermissions PDA (from permission_manager) */
  callerPermissions: Address<TAccountCallerPermissions>;
  token2022Program?: Address<TAccountToken2022Program>;
  amount: BurnTokenInstructionDataArgs["amount"];
};

export function getBurnTokenInstruction<
  TAccountCaller extends string,
  TAccountTokenConfig extends string,
  TAccountMint extends string,
  TAccountSourceTokenAccount extends string,
  TAccountMintAuthority extends string,
  TAccountCallerPermissions extends string,
  TAccountToken2022Program extends string,
  TProgramAddress extends Address = typeof SPIKO_TOKEN_PROGRAM_ADDRESS,
>(
  input: BurnTokenInput<
    TAccountCaller,
    TAccountTokenConfig,
    TAccountMint,
    TAccountSourceTokenAccount,
    TAccountMintAuthority,
    TAccountCallerPermissions,
    TAccountToken2022Program
  >,
  config?: { programAddress?: TProgramAddress },
): BurnTokenInstruction<
  TProgramAddress,
  TAccountCaller,
  TAccountTokenConfig,
  TAccountMint,
  TAccountSourceTokenAccount,
  TAccountMintAuthority,
  TAccountCallerPermissions,
  TAccountToken2022Program
> {
  // Program address.
  const programAddress = config?.programAddress ?? SPIKO_TOKEN_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    caller: { value: input.caller ?? null, isWritable: false },
    tokenConfig: { value: input.tokenConfig ?? null, isWritable: false },
    mint: { value: input.mint ?? null, isWritable: true },
    sourceTokenAccount: {
      value: input.sourceTokenAccount ?? null,
      isWritable: true,
    },
    mintAuthority: { value: input.mintAuthority ?? null, isWritable: false },
    callerPermissions: {
      value: input.callerPermissions ?? null,
      isWritable: false,
    },
    token2022Program: {
      value: input.token2022Program ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.token2022Program.value) {
    accounts.token2022Program.value =
      "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb" as Address<"TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.caller),
      getAccountMeta(accounts.tokenConfig),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.sourceTokenAccount),
      getAccountMeta(accounts.mintAuthority),
      getAccountMeta(accounts.callerPermissions),
      getAccountMeta(accounts.token2022Program),
    ],
    data: getBurnTokenInstructionDataEncoder().encode(
      args as BurnTokenInstructionDataArgs,
    ),
    programAddress,
  } as BurnTokenInstruction<
    TProgramAddress,
    TAccountCaller,
    TAccountTokenConfig,
    TAccountMint,
    TAccountSourceTokenAccount,
    TAccountMintAuthority,
    TAccountCallerPermissions,
    TAccountToken2022Program
  >);
}

export type ParsedBurnTokenInstruction<
  TProgram extends string = typeof SPIKO_TOKEN_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Caller (must have BURNER role) */
    caller: TAccountMetas[0];
    /** TokenConfig PDA */
    tokenConfig: TAccountMetas[1];
    /** Token-2022 Mint */
    mint: TAccountMetas[2];
    /** Source token account */
    sourceTokenAccount: TAccountMetas[3];
    /** Mint authority PDA (acts as authority for burn) */
    mintAuthority: TAccountMetas[4];
    /** Caller's UserPermissions PDA (from permission_manager) */
    callerPermissions: TAccountMetas[5];
    token2022Program: TAccountMetas[6];
  };
  data: BurnTokenInstructionData;
};

export function parseBurnTokenInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedBurnTokenInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 7) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      caller: getNextAccount(),
      tokenConfig: getNextAccount(),
      mint: getNextAccount(),
      sourceTokenAccount: getNextAccount(),
      mintAuthority: getNextAccount(),
      callerPermissions: getNextAccount(),
      token2022Program: getNextAccount(),
    },
    data: getBurnTokenInstructionDataDecoder().decode(instruction.data),
  };
}
