/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { SPIKO_TOKEN_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const INITIALIZE_TOKEN_DISCRIMINATOR = new Uint8Array([0]);

export function getInitializeTokenDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 1).encode(
    INITIALIZE_TOKEN_DISCRIMINATOR,
  );
}

export type InitializeTokenInstruction<
  TProgram extends string = typeof SPIKO_TOKEN_PROGRAM_ADDRESS,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountTokenConfig extends string | AccountMeta<string> = string,
  TAccountMint extends string | AccountMeta<string> = string,
  TAccountMintAuthority extends string | AccountMeta<string> = string,
  TAccountPermissionManager extends string | AccountMeta<string> = string,
  TAccountToken2022Program extends string | AccountMeta<string> =
    "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb",
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TAccountTransferHookProgram extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? WritableSignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountTokenConfig extends string
        ? WritableAccount<TAccountTokenConfig>
        : TAccountTokenConfig,
      TAccountMint extends string
        ? WritableAccount<TAccountMint>
        : TAccountMint,
      TAccountMintAuthority extends string
        ? ReadonlyAccount<TAccountMintAuthority>
        : TAccountMintAuthority,
      TAccountPermissionManager extends string
        ? ReadonlyAccount<TAccountPermissionManager>
        : TAccountPermissionManager,
      TAccountToken2022Program extends string
        ? ReadonlyAccount<TAccountToken2022Program>
        : TAccountToken2022Program,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountTransferHookProgram extends string
        ? ReadonlyAccount<TAccountTransferHookProgram>
        : TAccountTransferHookProgram,
      ...TRemainingAccounts,
    ]
  >;

export type InitializeTokenInstructionData = {
  discriminator: ReadonlyUint8Array;
  decimals: number;
  nameLen: number;
};

export type InitializeTokenInstructionDataArgs = {
  decimals: number;
  nameLen: number;
};

export function getInitializeTokenInstructionDataEncoder(): FixedSizeEncoder<InitializeTokenInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 1)],
      ["decimals", getU8Encoder()],
      ["nameLen", getU32Encoder()],
    ]),
    (value) => ({ ...value, discriminator: INITIALIZE_TOKEN_DISCRIMINATOR }),
  );
}

export function getInitializeTokenInstructionDataDecoder(): FixedSizeDecoder<InitializeTokenInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 1)],
    ["decimals", getU8Decoder()],
    ["nameLen", getU32Decoder()],
  ]);
}

export function getInitializeTokenInstructionDataCodec(): FixedSizeCodec<
  InitializeTokenInstructionDataArgs,
  InitializeTokenInstructionData
> {
  return combineCodec(
    getInitializeTokenInstructionDataEncoder(),
    getInitializeTokenInstructionDataDecoder(),
  );
}

export type InitializeTokenInput<
  TAccountAdmin extends string = string,
  TAccountTokenConfig extends string = string,
  TAccountMint extends string = string,
  TAccountMintAuthority extends string = string,
  TAccountPermissionManager extends string = string,
  TAccountToken2022Program extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTransferHookProgram extends string = string,
> = {
  /** Admin / deployer (payer) */
  admin: TransactionSigner<TAccountAdmin>;
  /** TokenConfig PDA. Seeds: ["token_config", mint] */
  tokenConfig: Address<TAccountTokenConfig>;
  /** Token-2022 Mint account (pre-allocated with extension space) */
  mint: Address<TAccountMint>;
  /** Mint authority PDA. Seeds: ["mint_authority", mint] */
  mintAuthority: Address<TAccountMintAuthority>;
  /** PermissionManager program ID */
  permissionManager: Address<TAccountPermissionManager>;
  token2022Program?: Address<TAccountToken2022Program>;
  systemProgram?: Address<TAccountSystemProgram>;
  /** Transfer Hook program (spiko-transfer-hook) */
  transferHookProgram: Address<TAccountTransferHookProgram>;
  decimals: InitializeTokenInstructionDataArgs["decimals"];
  nameLen: InitializeTokenInstructionDataArgs["nameLen"];
};

export function getInitializeTokenInstruction<
  TAccountAdmin extends string,
  TAccountTokenConfig extends string,
  TAccountMint extends string,
  TAccountMintAuthority extends string,
  TAccountPermissionManager extends string,
  TAccountToken2022Program extends string,
  TAccountSystemProgram extends string,
  TAccountTransferHookProgram extends string,
  TProgramAddress extends Address = typeof SPIKO_TOKEN_PROGRAM_ADDRESS,
>(
  input: InitializeTokenInput<
    TAccountAdmin,
    TAccountTokenConfig,
    TAccountMint,
    TAccountMintAuthority,
    TAccountPermissionManager,
    TAccountToken2022Program,
    TAccountSystemProgram,
    TAccountTransferHookProgram
  >,
  config?: { programAddress?: TProgramAddress },
): InitializeTokenInstruction<
  TProgramAddress,
  TAccountAdmin,
  TAccountTokenConfig,
  TAccountMint,
  TAccountMintAuthority,
  TAccountPermissionManager,
  TAccountToken2022Program,
  TAccountSystemProgram,
  TAccountTransferHookProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? SPIKO_TOKEN_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    tokenConfig: { value: input.tokenConfig ?? null, isWritable: true },
    mint: { value: input.mint ?? null, isWritable: true },
    mintAuthority: { value: input.mintAuthority ?? null, isWritable: false },
    permissionManager: {
      value: input.permissionManager ?? null,
      isWritable: false,
    },
    token2022Program: {
      value: input.token2022Program ?? null,
      isWritable: false,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    transferHookProgram: {
      value: input.transferHookProgram ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.token2022Program.value) {
    accounts.token2022Program.value =
      "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb" as Address<"TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.admin),
      getAccountMeta(accounts.tokenConfig),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.mintAuthority),
      getAccountMeta(accounts.permissionManager),
      getAccountMeta(accounts.token2022Program),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.transferHookProgram),
    ],
    data: getInitializeTokenInstructionDataEncoder().encode(
      args as InitializeTokenInstructionDataArgs,
    ),
    programAddress,
  } as InitializeTokenInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountTokenConfig,
    TAccountMint,
    TAccountMintAuthority,
    TAccountPermissionManager,
    TAccountToken2022Program,
    TAccountSystemProgram,
    TAccountTransferHookProgram
  >);
}

export type ParsedInitializeTokenInstruction<
  TProgram extends string = typeof SPIKO_TOKEN_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Admin / deployer (payer) */
    admin: TAccountMetas[0];
    /** TokenConfig PDA. Seeds: ["token_config", mint] */
    tokenConfig: TAccountMetas[1];
    /** Token-2022 Mint account (pre-allocated with extension space) */
    mint: TAccountMetas[2];
    /** Mint authority PDA. Seeds: ["mint_authority", mint] */
    mintAuthority: TAccountMetas[3];
    /** PermissionManager program ID */
    permissionManager: TAccountMetas[4];
    token2022Program: TAccountMetas[5];
    systemProgram: TAccountMetas[6];
    /** Transfer Hook program (spiko-transfer-hook) */
    transferHookProgram: TAccountMetas[7];
  };
  data: InitializeTokenInstructionData;
};

export function parseInitializeTokenInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedInitializeTokenInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 8) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      admin: getNextAccount(),
      tokenConfig: getNextAccount(),
      mint: getNextAccount(),
      mintAuthority: getNextAccount(),
      permissionManager: getNextAccount(),
      token2022Program: getNextAccount(),
      systemProgram: getNextAccount(),
      transferHookProgram: getNextAccount(),
    },
    data: getInitializeTokenInstructionDataDecoder().decode(instruction.data),
  };
}
