/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import { SPIKO_TOKEN_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const MINT_TOKEN_DISCRIMINATOR = new Uint8Array([1]);

export function getMintTokenDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 1).encode(MINT_TOKEN_DISCRIMINATOR);
}

export type MintTokenInstruction<
  TProgram extends string = typeof SPIKO_TOKEN_PROGRAM_ADDRESS,
  TAccountCaller extends string | AccountMeta<string> = string,
  TAccountTokenConfig extends string | AccountMeta<string> = string,
  TAccountMint extends string | AccountMeta<string> = string,
  TAccountRecipientTokenAccount extends string | AccountMeta<string> = string,
  TAccountMintAuthority extends string | AccountMeta<string> = string,
  TAccountCallerPermissions extends string | AccountMeta<string> = string,
  TAccountRecipientPermissions extends string | AccountMeta<string> = string,
  TAccountToken2022Program extends string | AccountMeta<string> =
    "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountCaller extends string
        ? ReadonlySignerAccount<TAccountCaller> &
            AccountSignerMeta<TAccountCaller>
        : TAccountCaller,
      TAccountTokenConfig extends string
        ? ReadonlyAccount<TAccountTokenConfig>
        : TAccountTokenConfig,
      TAccountMint extends string
        ? WritableAccount<TAccountMint>
        : TAccountMint,
      TAccountRecipientTokenAccount extends string
        ? WritableAccount<TAccountRecipientTokenAccount>
        : TAccountRecipientTokenAccount,
      TAccountMintAuthority extends string
        ? ReadonlyAccount<TAccountMintAuthority>
        : TAccountMintAuthority,
      TAccountCallerPermissions extends string
        ? ReadonlyAccount<TAccountCallerPermissions>
        : TAccountCallerPermissions,
      TAccountRecipientPermissions extends string
        ? ReadonlyAccount<TAccountRecipientPermissions>
        : TAccountRecipientPermissions,
      TAccountToken2022Program extends string
        ? ReadonlyAccount<TAccountToken2022Program>
        : TAccountToken2022Program,
      ...TRemainingAccounts,
    ]
  >;

export type MintTokenInstructionData = {
  discriminator: ReadonlyUint8Array;
  amount: bigint;
};

export type MintTokenInstructionDataArgs = { amount: number | bigint };

export function getMintTokenInstructionDataEncoder(): FixedSizeEncoder<MintTokenInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 1)],
      ["amount", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: MINT_TOKEN_DISCRIMINATOR }),
  );
}

export function getMintTokenInstructionDataDecoder(): FixedSizeDecoder<MintTokenInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 1)],
    ["amount", getU64Decoder()],
  ]);
}

export function getMintTokenInstructionDataCodec(): FixedSizeCodec<
  MintTokenInstructionDataArgs,
  MintTokenInstructionData
> {
  return combineCodec(
    getMintTokenInstructionDataEncoder(),
    getMintTokenInstructionDataDecoder(),
  );
}

export type MintTokenInput<
  TAccountCaller extends string = string,
  TAccountTokenConfig extends string = string,
  TAccountMint extends string = string,
  TAccountRecipientTokenAccount extends string = string,
  TAccountMintAuthority extends string = string,
  TAccountCallerPermissions extends string = string,
  TAccountRecipientPermissions extends string = string,
  TAccountToken2022Program extends string = string,
> = {
  /** Caller (must have MINTER role) */
  caller: TransactionSigner<TAccountCaller>;
  /** TokenConfig PDA */
  tokenConfig: Address<TAccountTokenConfig>;
  /** Token-2022 Mint */
  mint: Address<TAccountMint>;
  /** Recipient's token account */
  recipientTokenAccount: Address<TAccountRecipientTokenAccount>;
  /** Mint authority PDA */
  mintAuthority: Address<TAccountMintAuthority>;
  /** Caller's UserPermissions PDA (from permission_manager) */
  callerPermissions: Address<TAccountCallerPermissions>;
  /** Recipient's UserPermissions PDA (whitelist check) */
  recipientPermissions: Address<TAccountRecipientPermissions>;
  token2022Program?: Address<TAccountToken2022Program>;
  amount: MintTokenInstructionDataArgs["amount"];
};

export function getMintTokenInstruction<
  TAccountCaller extends string,
  TAccountTokenConfig extends string,
  TAccountMint extends string,
  TAccountRecipientTokenAccount extends string,
  TAccountMintAuthority extends string,
  TAccountCallerPermissions extends string,
  TAccountRecipientPermissions extends string,
  TAccountToken2022Program extends string,
  TProgramAddress extends Address = typeof SPIKO_TOKEN_PROGRAM_ADDRESS,
>(
  input: MintTokenInput<
    TAccountCaller,
    TAccountTokenConfig,
    TAccountMint,
    TAccountRecipientTokenAccount,
    TAccountMintAuthority,
    TAccountCallerPermissions,
    TAccountRecipientPermissions,
    TAccountToken2022Program
  >,
  config?: { programAddress?: TProgramAddress },
): MintTokenInstruction<
  TProgramAddress,
  TAccountCaller,
  TAccountTokenConfig,
  TAccountMint,
  TAccountRecipientTokenAccount,
  TAccountMintAuthority,
  TAccountCallerPermissions,
  TAccountRecipientPermissions,
  TAccountToken2022Program
> {
  // Program address.
  const programAddress = config?.programAddress ?? SPIKO_TOKEN_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    caller: { value: input.caller ?? null, isWritable: false },
    tokenConfig: { value: input.tokenConfig ?? null, isWritable: false },
    mint: { value: input.mint ?? null, isWritable: true },
    recipientTokenAccount: {
      value: input.recipientTokenAccount ?? null,
      isWritable: true,
    },
    mintAuthority: { value: input.mintAuthority ?? null, isWritable: false },
    callerPermissions: {
      value: input.callerPermissions ?? null,
      isWritable: false,
    },
    recipientPermissions: {
      value: input.recipientPermissions ?? null,
      isWritable: false,
    },
    token2022Program: {
      value: input.token2022Program ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.token2022Program.value) {
    accounts.token2022Program.value =
      "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb" as Address<"TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.caller),
      getAccountMeta(accounts.tokenConfig),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.recipientTokenAccount),
      getAccountMeta(accounts.mintAuthority),
      getAccountMeta(accounts.callerPermissions),
      getAccountMeta(accounts.recipientPermissions),
      getAccountMeta(accounts.token2022Program),
    ],
    data: getMintTokenInstructionDataEncoder().encode(
      args as MintTokenInstructionDataArgs,
    ),
    programAddress,
  } as MintTokenInstruction<
    TProgramAddress,
    TAccountCaller,
    TAccountTokenConfig,
    TAccountMint,
    TAccountRecipientTokenAccount,
    TAccountMintAuthority,
    TAccountCallerPermissions,
    TAccountRecipientPermissions,
    TAccountToken2022Program
  >);
}

export type ParsedMintTokenInstruction<
  TProgram extends string = typeof SPIKO_TOKEN_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Caller (must have MINTER role) */
    caller: TAccountMetas[0];
    /** TokenConfig PDA */
    tokenConfig: TAccountMetas[1];
    /** Token-2022 Mint */
    mint: TAccountMetas[2];
    /** Recipient's token account */
    recipientTokenAccount: TAccountMetas[3];
    /** Mint authority PDA */
    mintAuthority: TAccountMetas[4];
    /** Caller's UserPermissions PDA (from permission_manager) */
    callerPermissions: TAccountMetas[5];
    /** Recipient's UserPermissions PDA (whitelist check) */
    recipientPermissions: TAccountMetas[6];
    token2022Program: TAccountMetas[7];
  };
  data: MintTokenInstructionData;
};

export function parseMintTokenInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedMintTokenInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 8) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      caller: getNextAccount(),
      tokenConfig: getNextAccount(),
      mint: getNextAccount(),
      recipientTokenAccount: getNextAccount(),
      mintAuthority: getNextAccount(),
      callerPermissions: getNextAccount(),
      recipientPermissions: getNextAccount(),
      token2022Program: getNextAccount(),
    },
    data: getMintTokenInstructionDataDecoder().decode(instruction.data),
  };
}
