/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { SPIKO_TOKEN_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const REDEEM_TOKEN_DISCRIMINATOR = new Uint8Array([6]);

export function getRedeemTokenDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 1).encode(
    REDEEM_TOKEN_DISCRIMINATOR,
  );
}

export type RedeemTokenInstruction<
  TProgram extends string = typeof SPIKO_TOKEN_PROGRAM_ADDRESS,
  TAccountUser extends string | AccountMeta<string> = string,
  TAccountTokenConfig extends string | AccountMeta<string> = string,
  TAccountUserSource extends string | AccountMeta<string> = string,
  TAccountVault extends string | AccountMeta<string> = string,
  TAccountMint extends string | AccountMeta<string> = string,
  TAccountUserPermissions extends string | AccountMeta<string> = string,
  TAccountVaultAuthorityPermissions extends string | AccountMeta<string> =
    string,
  TAccountToken2022Program extends string | AccountMeta<string> =
    "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb",
  TAccountRedemptionProgram extends string | AccountMeta<string> = string,
  TAccountRedemptionConfig extends string | AccountMeta<string> = string,
  TAccountRedemptionOperation extends string | AccountMeta<string> = string,
  TAccountTokenMinimum extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TAccountExtraAccountMetaList extends string | AccountMeta<string> = string,
  TAccountPermissionManagerProgram extends string | AccountMeta<string> =
    string,
  TAccountSpikoTokenProgram extends string | AccountMeta<string> = string,
  TAccountHookProgram extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountUser extends string
        ? WritableSignerAccount<TAccountUser> & AccountSignerMeta<TAccountUser>
        : TAccountUser,
      TAccountTokenConfig extends string
        ? ReadonlyAccount<TAccountTokenConfig>
        : TAccountTokenConfig,
      TAccountUserSource extends string
        ? WritableAccount<TAccountUserSource>
        : TAccountUserSource,
      TAccountVault extends string
        ? WritableAccount<TAccountVault>
        : TAccountVault,
      TAccountMint extends string
        ? ReadonlyAccount<TAccountMint>
        : TAccountMint,
      TAccountUserPermissions extends string
        ? ReadonlyAccount<TAccountUserPermissions>
        : TAccountUserPermissions,
      TAccountVaultAuthorityPermissions extends string
        ? ReadonlyAccount<TAccountVaultAuthorityPermissions>
        : TAccountVaultAuthorityPermissions,
      TAccountToken2022Program extends string
        ? ReadonlyAccount<TAccountToken2022Program>
        : TAccountToken2022Program,
      TAccountRedemptionProgram extends string
        ? ReadonlyAccount<TAccountRedemptionProgram>
        : TAccountRedemptionProgram,
      TAccountRedemptionConfig extends string
        ? ReadonlyAccount<TAccountRedemptionConfig>
        : TAccountRedemptionConfig,
      TAccountRedemptionOperation extends string
        ? WritableAccount<TAccountRedemptionOperation>
        : TAccountRedemptionOperation,
      TAccountTokenMinimum extends string
        ? ReadonlyAccount<TAccountTokenMinimum>
        : TAccountTokenMinimum,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountExtraAccountMetaList extends string
        ? ReadonlyAccount<TAccountExtraAccountMetaList>
        : TAccountExtraAccountMetaList,
      TAccountPermissionManagerProgram extends string
        ? ReadonlyAccount<TAccountPermissionManagerProgram>
        : TAccountPermissionManagerProgram,
      TAccountSpikoTokenProgram extends string
        ? ReadonlyAccount<TAccountSpikoTokenProgram>
        : TAccountSpikoTokenProgram,
      TAccountHookProgram extends string
        ? ReadonlyAccount<TAccountHookProgram>
        : TAccountHookProgram,
      ...TRemainingAccounts,
    ]
  >;

export type RedeemTokenInstructionData = {
  discriminator: ReadonlyUint8Array;
  amount: bigint;
  salt: bigint;
};

export type RedeemTokenInstructionDataArgs = {
  amount: number | bigint;
  salt: number | bigint;
};

export function getRedeemTokenInstructionDataEncoder(): FixedSizeEncoder<RedeemTokenInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 1)],
      ["amount", getU64Encoder()],
      ["salt", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: REDEEM_TOKEN_DISCRIMINATOR }),
  );
}

export function getRedeemTokenInstructionDataDecoder(): FixedSizeDecoder<RedeemTokenInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 1)],
    ["amount", getU64Decoder()],
    ["salt", getU64Decoder()],
  ]);
}

export function getRedeemTokenInstructionDataCodec(): FixedSizeCodec<
  RedeemTokenInstructionDataArgs,
  RedeemTokenInstructionData
> {
  return combineCodec(
    getRedeemTokenInstructionDataEncoder(),
    getRedeemTokenInstructionDataDecoder(),
  );
}

export type RedeemTokenInput<
  TAccountUser extends string = string,
  TAccountTokenConfig extends string = string,
  TAccountUserSource extends string = string,
  TAccountVault extends string = string,
  TAccountMint extends string = string,
  TAccountUserPermissions extends string = string,
  TAccountVaultAuthorityPermissions extends string = string,
  TAccountToken2022Program extends string = string,
  TAccountRedemptionProgram extends string = string,
  TAccountRedemptionConfig extends string = string,
  TAccountRedemptionOperation extends string = string,
  TAccountTokenMinimum extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountExtraAccountMetaList extends string = string,
  TAccountPermissionManagerProgram extends string = string,
  TAccountSpikoTokenProgram extends string = string,
  TAccountHookProgram extends string = string,
> = {
  /** User (token holder) */
  user: TransactionSigner<TAccountUser>;
  /** TokenConfig PDA */
  tokenConfig: Address<TAccountTokenConfig>;
  /** User's source token account */
  userSource: Address<TAccountUserSource>;
  /** Vault token account (destination for transfer) */
  vault: Address<TAccountVault>;
  /** Token-2022 Mint */
  mint: Address<TAccountMint>;
  /** User's UserPermissions PDA (whitelist check) */
  userPermissions: Address<TAccountUserPermissions>;
  /** Vault authority's UserPermissions PDA (whitelist check) */
  vaultAuthorityPermissions: Address<TAccountVaultAuthorityPermissions>;
  token2022Program?: Address<TAccountToken2022Program>;
  /** Redemption program */
  redemptionProgram: Address<TAccountRedemptionProgram>;
  /** RedemptionConfig PDA (from redemption program) */
  redemptionConfig: Address<TAccountRedemptionConfig>;
  /** RedemptionOperation PDA (to be created by redemption) */
  redemptionOperation: Address<TAccountRedemptionOperation>;
  /** TokenMinimum PDA (from redemption program) */
  tokenMinimum: Address<TAccountTokenMinimum>;
  systemProgram?: Address<TAccountSystemProgram>;
  /** ExtraAccountMetaList PDA (Transfer Hook) */
  extraAccountMetaList: Address<TAccountExtraAccountMetaList>;
  /** PermissionManager program */
  permissionManagerProgram: Address<TAccountPermissionManagerProgram>;
  /** SpikoToken program (this program, for hook resolution) */
  spikoTokenProgram: Address<TAccountSpikoTokenProgram>;
  /** Transfer Hook program (spiko-transfer-hook) */
  hookProgram: Address<TAccountHookProgram>;
  amount: RedeemTokenInstructionDataArgs["amount"];
  salt: RedeemTokenInstructionDataArgs["salt"];
};

export function getRedeemTokenInstruction<
  TAccountUser extends string,
  TAccountTokenConfig extends string,
  TAccountUserSource extends string,
  TAccountVault extends string,
  TAccountMint extends string,
  TAccountUserPermissions extends string,
  TAccountVaultAuthorityPermissions extends string,
  TAccountToken2022Program extends string,
  TAccountRedemptionProgram extends string,
  TAccountRedemptionConfig extends string,
  TAccountRedemptionOperation extends string,
  TAccountTokenMinimum extends string,
  TAccountSystemProgram extends string,
  TAccountExtraAccountMetaList extends string,
  TAccountPermissionManagerProgram extends string,
  TAccountSpikoTokenProgram extends string,
  TAccountHookProgram extends string,
  TProgramAddress extends Address = typeof SPIKO_TOKEN_PROGRAM_ADDRESS,
>(
  input: RedeemTokenInput<
    TAccountUser,
    TAccountTokenConfig,
    TAccountUserSource,
    TAccountVault,
    TAccountMint,
    TAccountUserPermissions,
    TAccountVaultAuthorityPermissions,
    TAccountToken2022Program,
    TAccountRedemptionProgram,
    TAccountRedemptionConfig,
    TAccountRedemptionOperation,
    TAccountTokenMinimum,
    TAccountSystemProgram,
    TAccountExtraAccountMetaList,
    TAccountPermissionManagerProgram,
    TAccountSpikoTokenProgram,
    TAccountHookProgram
  >,
  config?: { programAddress?: TProgramAddress },
): RedeemTokenInstruction<
  TProgramAddress,
  TAccountUser,
  TAccountTokenConfig,
  TAccountUserSource,
  TAccountVault,
  TAccountMint,
  TAccountUserPermissions,
  TAccountVaultAuthorityPermissions,
  TAccountToken2022Program,
  TAccountRedemptionProgram,
  TAccountRedemptionConfig,
  TAccountRedemptionOperation,
  TAccountTokenMinimum,
  TAccountSystemProgram,
  TAccountExtraAccountMetaList,
  TAccountPermissionManagerProgram,
  TAccountSpikoTokenProgram,
  TAccountHookProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? SPIKO_TOKEN_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    user: { value: input.user ?? null, isWritable: true },
    tokenConfig: { value: input.tokenConfig ?? null, isWritable: false },
    userSource: { value: input.userSource ?? null, isWritable: true },
    vault: { value: input.vault ?? null, isWritable: true },
    mint: { value: input.mint ?? null, isWritable: false },
    userPermissions: {
      value: input.userPermissions ?? null,
      isWritable: false,
    },
    vaultAuthorityPermissions: {
      value: input.vaultAuthorityPermissions ?? null,
      isWritable: false,
    },
    token2022Program: {
      value: input.token2022Program ?? null,
      isWritable: false,
    },
    redemptionProgram: {
      value: input.redemptionProgram ?? null,
      isWritable: false,
    },
    redemptionConfig: {
      value: input.redemptionConfig ?? null,
      isWritable: false,
    },
    redemptionOperation: {
      value: input.redemptionOperation ?? null,
      isWritable: true,
    },
    tokenMinimum: { value: input.tokenMinimum ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    extraAccountMetaList: {
      value: input.extraAccountMetaList ?? null,
      isWritable: false,
    },
    permissionManagerProgram: {
      value: input.permissionManagerProgram ?? null,
      isWritable: false,
    },
    spikoTokenProgram: {
      value: input.spikoTokenProgram ?? null,
      isWritable: false,
    },
    hookProgram: { value: input.hookProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.token2022Program.value) {
    accounts.token2022Program.value =
      "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb" as Address<"TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.tokenConfig),
      getAccountMeta(accounts.userSource),
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.userPermissions),
      getAccountMeta(accounts.vaultAuthorityPermissions),
      getAccountMeta(accounts.token2022Program),
      getAccountMeta(accounts.redemptionProgram),
      getAccountMeta(accounts.redemptionConfig),
      getAccountMeta(accounts.redemptionOperation),
      getAccountMeta(accounts.tokenMinimum),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.extraAccountMetaList),
      getAccountMeta(accounts.permissionManagerProgram),
      getAccountMeta(accounts.spikoTokenProgram),
      getAccountMeta(accounts.hookProgram),
    ],
    data: getRedeemTokenInstructionDataEncoder().encode(
      args as RedeemTokenInstructionDataArgs,
    ),
    programAddress,
  } as RedeemTokenInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountTokenConfig,
    TAccountUserSource,
    TAccountVault,
    TAccountMint,
    TAccountUserPermissions,
    TAccountVaultAuthorityPermissions,
    TAccountToken2022Program,
    TAccountRedemptionProgram,
    TAccountRedemptionConfig,
    TAccountRedemptionOperation,
    TAccountTokenMinimum,
    TAccountSystemProgram,
    TAccountExtraAccountMetaList,
    TAccountPermissionManagerProgram,
    TAccountSpikoTokenProgram,
    TAccountHookProgram
  >);
}

export type ParsedRedeemTokenInstruction<
  TProgram extends string = typeof SPIKO_TOKEN_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** User (token holder) */
    user: TAccountMetas[0];
    /** TokenConfig PDA */
    tokenConfig: TAccountMetas[1];
    /** User's source token account */
    userSource: TAccountMetas[2];
    /** Vault token account (destination for transfer) */
    vault: TAccountMetas[3];
    /** Token-2022 Mint */
    mint: TAccountMetas[4];
    /** User's UserPermissions PDA (whitelist check) */
    userPermissions: TAccountMetas[5];
    /** Vault authority's UserPermissions PDA (whitelist check) */
    vaultAuthorityPermissions: TAccountMetas[6];
    token2022Program: TAccountMetas[7];
    /** Redemption program */
    redemptionProgram: TAccountMetas[8];
    /** RedemptionConfig PDA (from redemption program) */
    redemptionConfig: TAccountMetas[9];
    /** RedemptionOperation PDA (to be created by redemption) */
    redemptionOperation: TAccountMetas[10];
    /** TokenMinimum PDA (from redemption program) */
    tokenMinimum: TAccountMetas[11];
    systemProgram: TAccountMetas[12];
    /** ExtraAccountMetaList PDA (Transfer Hook) */
    extraAccountMetaList: TAccountMetas[13];
    /** PermissionManager program */
    permissionManagerProgram: TAccountMetas[14];
    /** SpikoToken program (this program, for hook resolution) */
    spikoTokenProgram: TAccountMetas[15];
    /** Transfer Hook program (spiko-transfer-hook) */
    hookProgram: TAccountMetas[16];
  };
  data: RedeemTokenInstructionData;
};

export function parseRedeemTokenInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedRedeemTokenInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 17) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      user: getNextAccount(),
      tokenConfig: getNextAccount(),
      userSource: getNextAccount(),
      vault: getNextAccount(),
      mint: getNextAccount(),
      userPermissions: getNextAccount(),
      vaultAuthorityPermissions: getNextAccount(),
      token2022Program: getNextAccount(),
      redemptionProgram: getNextAccount(),
      redemptionConfig: getNextAccount(),
      redemptionOperation: getNextAccount(),
      tokenMinimum: getNextAccount(),
      systemProgram: getNextAccount(),
      extraAccountMetaList: getNextAccount(),
      permissionManagerProgram: getNextAccount(),
      spikoTokenProgram: getNextAccount(),
      hookProgram: getNextAccount(),
    },
    data: getRedeemTokenInstructionDataDecoder().decode(instruction.data),
  };
}
