/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import { SPIKO_TOKEN_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const SET_REDEMPTION_CONTRACT_DISCRIMINATOR = new Uint8Array([7]);

export function getSetRedemptionContractDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 1).encode(
    SET_REDEMPTION_CONTRACT_DISCRIMINATOR,
  );
}

export type SetRedemptionContractInstruction<
  TProgram extends string = typeof SPIKO_TOKEN_PROGRAM_ADDRESS,
  TAccountCaller extends string | AccountMeta<string> = string,
  TAccountTokenConfig extends string | AccountMeta<string> = string,
  TAccountPermissionConfig extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountCaller extends string
        ? ReadonlySignerAccount<TAccountCaller> &
            AccountSignerMeta<TAccountCaller>
        : TAccountCaller,
      TAccountTokenConfig extends string
        ? WritableAccount<TAccountTokenConfig>
        : TAccountTokenConfig,
      TAccountPermissionConfig extends string
        ? ReadonlyAccount<TAccountPermissionConfig>
        : TAccountPermissionConfig,
      ...TRemainingAccounts,
    ]
  >;

export type SetRedemptionContractInstructionData = {
  discriminator: ReadonlyUint8Array;
  redemptionContract: Address;
};

export type SetRedemptionContractInstructionDataArgs = {
  redemptionContract: Address;
};

export function getSetRedemptionContractInstructionDataEncoder(): FixedSizeEncoder<SetRedemptionContractInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 1)],
      ["redemptionContract", getAddressEncoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: SET_REDEMPTION_CONTRACT_DISCRIMINATOR,
    }),
  );
}

export function getSetRedemptionContractInstructionDataDecoder(): FixedSizeDecoder<SetRedemptionContractInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 1)],
    ["redemptionContract", getAddressDecoder()],
  ]);
}

export function getSetRedemptionContractInstructionDataCodec(): FixedSizeCodec<
  SetRedemptionContractInstructionDataArgs,
  SetRedemptionContractInstructionData
> {
  return combineCodec(
    getSetRedemptionContractInstructionDataEncoder(),
    getSetRedemptionContractInstructionDataDecoder(),
  );
}

export type SetRedemptionContractInput<
  TAccountCaller extends string = string,
  TAccountTokenConfig extends string = string,
  TAccountPermissionConfig extends string = string,
> = {
  /** Admin caller */
  caller: TransactionSigner<TAccountCaller>;
  /** TokenConfig PDA */
  tokenConfig: Address<TAccountTokenConfig>;
  /** PermissionConfig PDA (from permission_manager, proves admin identity) */
  permissionConfig: Address<TAccountPermissionConfig>;
  redemptionContract: SetRedemptionContractInstructionDataArgs["redemptionContract"];
};

export function getSetRedemptionContractInstruction<
  TAccountCaller extends string,
  TAccountTokenConfig extends string,
  TAccountPermissionConfig extends string,
  TProgramAddress extends Address = typeof SPIKO_TOKEN_PROGRAM_ADDRESS,
>(
  input: SetRedemptionContractInput<
    TAccountCaller,
    TAccountTokenConfig,
    TAccountPermissionConfig
  >,
  config?: { programAddress?: TProgramAddress },
): SetRedemptionContractInstruction<
  TProgramAddress,
  TAccountCaller,
  TAccountTokenConfig,
  TAccountPermissionConfig
> {
  // Program address.
  const programAddress = config?.programAddress ?? SPIKO_TOKEN_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    caller: { value: input.caller ?? null, isWritable: false },
    tokenConfig: { value: input.tokenConfig ?? null, isWritable: true },
    permissionConfig: {
      value: input.permissionConfig ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.caller),
      getAccountMeta(accounts.tokenConfig),
      getAccountMeta(accounts.permissionConfig),
    ],
    data: getSetRedemptionContractInstructionDataEncoder().encode(
      args as SetRedemptionContractInstructionDataArgs,
    ),
    programAddress,
  } as SetRedemptionContractInstruction<
    TProgramAddress,
    TAccountCaller,
    TAccountTokenConfig,
    TAccountPermissionConfig
  >);
}

export type ParsedSetRedemptionContractInstruction<
  TProgram extends string = typeof SPIKO_TOKEN_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Admin caller */
    caller: TAccountMetas[0];
    /** TokenConfig PDA */
    tokenConfig: TAccountMetas[1];
    /** PermissionConfig PDA (from permission_manager, proves admin identity) */
    permissionConfig: TAccountMetas[2];
  };
  data: SetRedemptionContractInstructionData;
};

export function parseSetRedemptionContractInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedSetRedemptionContractInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      caller: getNextAccount(),
      tokenConfig: getNextAccount(),
      permissionConfig: getNextAccount(),
    },
    data: getSetRedemptionContractInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
