/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import { SPIKO_TOKEN_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const TRANSFER_TOKEN_DISCRIMINATOR = new Uint8Array([3]);

export function getTransferTokenDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 1).encode(
    TRANSFER_TOKEN_DISCRIMINATOR,
  );
}

export type TransferTokenInstruction<
  TProgram extends string = typeof SPIKO_TOKEN_PROGRAM_ADDRESS,
  TAccountSender extends string | AccountMeta<string> = string,
  TAccountTokenConfig extends string | AccountMeta<string> = string,
  TAccountSource extends string | AccountMeta<string> = string,
  TAccountDestination extends string | AccountMeta<string> = string,
  TAccountMint extends string | AccountMeta<string> = string,
  TAccountSenderPermissions extends string | AccountMeta<string> = string,
  TAccountRecipientPermissions extends string | AccountMeta<string> = string,
  TAccountToken2022Program extends string | AccountMeta<string> =
    "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb",
  TAccountExtraAccountMetaList extends string | AccountMeta<string> = string,
  TAccountPermissionManagerProgram extends string | AccountMeta<string> =
    string,
  TAccountSpikoTokenProgram extends string | AccountMeta<string> = string,
  TAccountHookProgram extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSender extends string
        ? ReadonlySignerAccount<TAccountSender> &
            AccountSignerMeta<TAccountSender>
        : TAccountSender,
      TAccountTokenConfig extends string
        ? ReadonlyAccount<TAccountTokenConfig>
        : TAccountTokenConfig,
      TAccountSource extends string
        ? WritableAccount<TAccountSource>
        : TAccountSource,
      TAccountDestination extends string
        ? WritableAccount<TAccountDestination>
        : TAccountDestination,
      TAccountMint extends string
        ? ReadonlyAccount<TAccountMint>
        : TAccountMint,
      TAccountSenderPermissions extends string
        ? ReadonlyAccount<TAccountSenderPermissions>
        : TAccountSenderPermissions,
      TAccountRecipientPermissions extends string
        ? ReadonlyAccount<TAccountRecipientPermissions>
        : TAccountRecipientPermissions,
      TAccountToken2022Program extends string
        ? ReadonlyAccount<TAccountToken2022Program>
        : TAccountToken2022Program,
      TAccountExtraAccountMetaList extends string
        ? ReadonlyAccount<TAccountExtraAccountMetaList>
        : TAccountExtraAccountMetaList,
      TAccountPermissionManagerProgram extends string
        ? ReadonlyAccount<TAccountPermissionManagerProgram>
        : TAccountPermissionManagerProgram,
      TAccountSpikoTokenProgram extends string
        ? ReadonlyAccount<TAccountSpikoTokenProgram>
        : TAccountSpikoTokenProgram,
      TAccountHookProgram extends string
        ? ReadonlyAccount<TAccountHookProgram>
        : TAccountHookProgram,
      ...TRemainingAccounts,
    ]
  >;

export type TransferTokenInstructionData = {
  discriminator: ReadonlyUint8Array;
  amount: bigint;
};

export type TransferTokenInstructionDataArgs = { amount: number | bigint };

export function getTransferTokenInstructionDataEncoder(): FixedSizeEncoder<TransferTokenInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 1)],
      ["amount", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: TRANSFER_TOKEN_DISCRIMINATOR }),
  );
}

export function getTransferTokenInstructionDataDecoder(): FixedSizeDecoder<TransferTokenInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 1)],
    ["amount", getU64Decoder()],
  ]);
}

export function getTransferTokenInstructionDataCodec(): FixedSizeCodec<
  TransferTokenInstructionDataArgs,
  TransferTokenInstructionData
> {
  return combineCodec(
    getTransferTokenInstructionDataEncoder(),
    getTransferTokenInstructionDataDecoder(),
  );
}

export type TransferTokenInput<
  TAccountSender extends string = string,
  TAccountTokenConfig extends string = string,
  TAccountSource extends string = string,
  TAccountDestination extends string = string,
  TAccountMint extends string = string,
  TAccountSenderPermissions extends string = string,
  TAccountRecipientPermissions extends string = string,
  TAccountToken2022Program extends string = string,
  TAccountExtraAccountMetaList extends string = string,
  TAccountPermissionManagerProgram extends string = string,
  TAccountSpikoTokenProgram extends string = string,
  TAccountHookProgram extends string = string,
> = {
  /** Sender (owner of source token account) */
  sender: TransactionSigner<TAccountSender>;
  /** TokenConfig PDA */
  tokenConfig: Address<TAccountTokenConfig>;
  /** Source token account */
  source: Address<TAccountSource>;
  /** Destination token account */
  destination: Address<TAccountDestination>;
  /** Token-2022 Mint */
  mint: Address<TAccountMint>;
  /** Sender's UserPermissions PDA (whitelist check) */
  senderPermissions: Address<TAccountSenderPermissions>;
  /** Recipient's UserPermissions PDA (whitelist check) */
  recipientPermissions: Address<TAccountRecipientPermissions>;
  token2022Program?: Address<TAccountToken2022Program>;
  /** ExtraAccountMetaList PDA (Transfer Hook) */
  extraAccountMetaList: Address<TAccountExtraAccountMetaList>;
  /** PermissionManager program */
  permissionManagerProgram: Address<TAccountPermissionManagerProgram>;
  /** SpikoToken program (this program, for hook resolution) */
  spikoTokenProgram: Address<TAccountSpikoTokenProgram>;
  /** Transfer Hook program (spiko-transfer-hook) */
  hookProgram: Address<TAccountHookProgram>;
  amount: TransferTokenInstructionDataArgs["amount"];
};

export function getTransferTokenInstruction<
  TAccountSender extends string,
  TAccountTokenConfig extends string,
  TAccountSource extends string,
  TAccountDestination extends string,
  TAccountMint extends string,
  TAccountSenderPermissions extends string,
  TAccountRecipientPermissions extends string,
  TAccountToken2022Program extends string,
  TAccountExtraAccountMetaList extends string,
  TAccountPermissionManagerProgram extends string,
  TAccountSpikoTokenProgram extends string,
  TAccountHookProgram extends string,
  TProgramAddress extends Address = typeof SPIKO_TOKEN_PROGRAM_ADDRESS,
>(
  input: TransferTokenInput<
    TAccountSender,
    TAccountTokenConfig,
    TAccountSource,
    TAccountDestination,
    TAccountMint,
    TAccountSenderPermissions,
    TAccountRecipientPermissions,
    TAccountToken2022Program,
    TAccountExtraAccountMetaList,
    TAccountPermissionManagerProgram,
    TAccountSpikoTokenProgram,
    TAccountHookProgram
  >,
  config?: { programAddress?: TProgramAddress },
): TransferTokenInstruction<
  TProgramAddress,
  TAccountSender,
  TAccountTokenConfig,
  TAccountSource,
  TAccountDestination,
  TAccountMint,
  TAccountSenderPermissions,
  TAccountRecipientPermissions,
  TAccountToken2022Program,
  TAccountExtraAccountMetaList,
  TAccountPermissionManagerProgram,
  TAccountSpikoTokenProgram,
  TAccountHookProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? SPIKO_TOKEN_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    sender: { value: input.sender ?? null, isWritable: false },
    tokenConfig: { value: input.tokenConfig ?? null, isWritable: false },
    source: { value: input.source ?? null, isWritable: true },
    destination: { value: input.destination ?? null, isWritable: true },
    mint: { value: input.mint ?? null, isWritable: false },
    senderPermissions: {
      value: input.senderPermissions ?? null,
      isWritable: false,
    },
    recipientPermissions: {
      value: input.recipientPermissions ?? null,
      isWritable: false,
    },
    token2022Program: {
      value: input.token2022Program ?? null,
      isWritable: false,
    },
    extraAccountMetaList: {
      value: input.extraAccountMetaList ?? null,
      isWritable: false,
    },
    permissionManagerProgram: {
      value: input.permissionManagerProgram ?? null,
      isWritable: false,
    },
    spikoTokenProgram: {
      value: input.spikoTokenProgram ?? null,
      isWritable: false,
    },
    hookProgram: { value: input.hookProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.token2022Program.value) {
    accounts.token2022Program.value =
      "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb" as Address<"TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.sender),
      getAccountMeta(accounts.tokenConfig),
      getAccountMeta(accounts.source),
      getAccountMeta(accounts.destination),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.senderPermissions),
      getAccountMeta(accounts.recipientPermissions),
      getAccountMeta(accounts.token2022Program),
      getAccountMeta(accounts.extraAccountMetaList),
      getAccountMeta(accounts.permissionManagerProgram),
      getAccountMeta(accounts.spikoTokenProgram),
      getAccountMeta(accounts.hookProgram),
    ],
    data: getTransferTokenInstructionDataEncoder().encode(
      args as TransferTokenInstructionDataArgs,
    ),
    programAddress,
  } as TransferTokenInstruction<
    TProgramAddress,
    TAccountSender,
    TAccountTokenConfig,
    TAccountSource,
    TAccountDestination,
    TAccountMint,
    TAccountSenderPermissions,
    TAccountRecipientPermissions,
    TAccountToken2022Program,
    TAccountExtraAccountMetaList,
    TAccountPermissionManagerProgram,
    TAccountSpikoTokenProgram,
    TAccountHookProgram
  >);
}

export type ParsedTransferTokenInstruction<
  TProgram extends string = typeof SPIKO_TOKEN_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Sender (owner of source token account) */
    sender: TAccountMetas[0];
    /** TokenConfig PDA */
    tokenConfig: TAccountMetas[1];
    /** Source token account */
    source: TAccountMetas[2];
    /** Destination token account */
    destination: TAccountMetas[3];
    /** Token-2022 Mint */
    mint: TAccountMetas[4];
    /** Sender's UserPermissions PDA (whitelist check) */
    senderPermissions: TAccountMetas[5];
    /** Recipient's UserPermissions PDA (whitelist check) */
    recipientPermissions: TAccountMetas[6];
    token2022Program: TAccountMetas[7];
    /** ExtraAccountMetaList PDA (Transfer Hook) */
    extraAccountMetaList: TAccountMetas[8];
    /** PermissionManager program */
    permissionManagerProgram: TAccountMetas[9];
    /** SpikoToken program (this program, for hook resolution) */
    spikoTokenProgram: TAccountMetas[10];
    /** Transfer Hook program (spiko-transfer-hook) */
    hookProgram: TAccountMetas[11];
  };
  data: TransferTokenInstructionData;
};

export function parseTransferTokenInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedTransferTokenInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 12) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      sender: getNextAccount(),
      tokenConfig: getNextAccount(),
      source: getNextAccount(),
      destination: getNextAccount(),
      mint: getNextAccount(),
      senderPermissions: getNextAccount(),
      recipientPermissions: getNextAccount(),
      token2022Program: getNextAccount(),
      extraAccountMetaList: getNextAccount(),
      permissionManagerProgram: getNextAccount(),
      spikoTokenProgram: getNextAccount(),
      hookProgram: getNextAccount(),
    },
    data: getTransferTokenInstructionDataDecoder().decode(instruction.data),
  };
}
