/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import { SPIKO_TOKEN_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const UNPAUSE_DISCRIMINATOR = new Uint8Array([5]);

export function getUnpauseDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 1).encode(UNPAUSE_DISCRIMINATOR);
}

export type UnpauseInstruction<
  TProgram extends string = typeof SPIKO_TOKEN_PROGRAM_ADDRESS,
  TAccountCaller extends string | AccountMeta<string> = string,
  TAccountTokenConfig extends string | AccountMeta<string> = string,
  TAccountCallerPermissions extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountCaller extends string
        ? ReadonlySignerAccount<TAccountCaller> &
            AccountSignerMeta<TAccountCaller>
        : TAccountCaller,
      TAccountTokenConfig extends string
        ? WritableAccount<TAccountTokenConfig>
        : TAccountTokenConfig,
      TAccountCallerPermissions extends string
        ? ReadonlyAccount<TAccountCallerPermissions>
        : TAccountCallerPermissions,
      ...TRemainingAccounts,
    ]
  >;

export type UnpauseInstructionData = { discriminator: ReadonlyUint8Array };

export type UnpauseInstructionDataArgs = {};

export function getUnpauseInstructionDataEncoder(): FixedSizeEncoder<UnpauseInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 1)]]),
    (value) => ({ ...value, discriminator: UNPAUSE_DISCRIMINATOR }),
  );
}

export function getUnpauseInstructionDataDecoder(): FixedSizeDecoder<UnpauseInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 1)],
  ]);
}

export function getUnpauseInstructionDataCodec(): FixedSizeCodec<
  UnpauseInstructionDataArgs,
  UnpauseInstructionData
> {
  return combineCodec(
    getUnpauseInstructionDataEncoder(),
    getUnpauseInstructionDataDecoder(),
  );
}

export type UnpauseInput<
  TAccountCaller extends string = string,
  TAccountTokenConfig extends string = string,
  TAccountCallerPermissions extends string = string,
> = {
  /** Caller (must have PAUSER role) */
  caller: TransactionSigner<TAccountCaller>;
  /** TokenConfig PDA */
  tokenConfig: Address<TAccountTokenConfig>;
  /** Caller's UserPermissions PDA (from permission_manager) */
  callerPermissions: Address<TAccountCallerPermissions>;
};

export function getUnpauseInstruction<
  TAccountCaller extends string,
  TAccountTokenConfig extends string,
  TAccountCallerPermissions extends string,
  TProgramAddress extends Address = typeof SPIKO_TOKEN_PROGRAM_ADDRESS,
>(
  input: UnpauseInput<
    TAccountCaller,
    TAccountTokenConfig,
    TAccountCallerPermissions
  >,
  config?: { programAddress?: TProgramAddress },
): UnpauseInstruction<
  TProgramAddress,
  TAccountCaller,
  TAccountTokenConfig,
  TAccountCallerPermissions
> {
  // Program address.
  const programAddress = config?.programAddress ?? SPIKO_TOKEN_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    caller: { value: input.caller ?? null, isWritable: false },
    tokenConfig: { value: input.tokenConfig ?? null, isWritable: true },
    callerPermissions: {
      value: input.callerPermissions ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.caller),
      getAccountMeta(accounts.tokenConfig),
      getAccountMeta(accounts.callerPermissions),
    ],
    data: getUnpauseInstructionDataEncoder().encode({}),
    programAddress,
  } as UnpauseInstruction<
    TProgramAddress,
    TAccountCaller,
    TAccountTokenConfig,
    TAccountCallerPermissions
  >);
}

export type ParsedUnpauseInstruction<
  TProgram extends string = typeof SPIKO_TOKEN_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Caller (must have PAUSER role) */
    caller: TAccountMetas[0];
    /** TokenConfig PDA */
    tokenConfig: TAccountMetas[1];
    /** Caller's UserPermissions PDA (from permission_manager) */
    callerPermissions: TAccountMetas[2];
  };
  data: UnpauseInstructionData;
};

export function parseUnpauseInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedUnpauseInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      caller: getNextAccount(),
      tokenConfig: getNextAccount(),
      callerPermissions: getNextAccount(),
    },
    data: getUnpauseInstructionDataDecoder().decode(instruction.data),
  };
}
