[package]
name = "redemption"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build", "permission-manager/idl-build"]

[dependencies]
anchor-lang = { workspace = true }
anchor-spl = { workspace = true }
permission-manager = { path = "../permission-manager", features = ["cpi"] }
spl-token-2022 = { version = "6", features = ["no-entrypoint"] }

[dev-dependencies]
solana-program-test = "2"
solana-sdk = "2"
spl-token-2022 = "6"
spl-associated-token-account = "6"

[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(feature, values("custom-heap", "custom-allocator", "anchor-debug"))'] }