/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import { PERMISSION_MANAGER_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const ACCEPT_OWNERSHIP_DISCRIMINATOR = new Uint8Array([4]);

export function getAcceptOwnershipDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 1).encode(
    ACCEPT_OWNERSHIP_DISCRIMINATOR,
  );
}

export type AcceptOwnershipInstruction<
  TProgram extends string = typeof PERMISSION_MANAGER_PROGRAM_ADDRESS,
  TAccountNewAdmin extends string | AccountMeta<string> = string,
  TAccountPermissionConfig extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountNewAdmin extends string
        ? ReadonlySignerAccount<TAccountNewAdmin> &
            AccountSignerMeta<TAccountNewAdmin>
        : TAccountNewAdmin,
      TAccountPermissionConfig extends string
        ? WritableAccount<TAccountPermissionConfig>
        : TAccountPermissionConfig,
      ...TRemainingAccounts,
    ]
  >;

export type AcceptOwnershipInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type AcceptOwnershipInstructionDataArgs = {};

export function getAcceptOwnershipInstructionDataEncoder(): FixedSizeEncoder<AcceptOwnershipInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 1)]]),
    (value) => ({ ...value, discriminator: ACCEPT_OWNERSHIP_DISCRIMINATOR }),
  );
}

export function getAcceptOwnershipInstructionDataDecoder(): FixedSizeDecoder<AcceptOwnershipInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 1)],
  ]);
}

export function getAcceptOwnershipInstructionDataCodec(): FixedSizeCodec<
  AcceptOwnershipInstructionDataArgs,
  AcceptOwnershipInstructionData
> {
  return combineCodec(
    getAcceptOwnershipInstructionDataEncoder(),
    getAcceptOwnershipInstructionDataDecoder(),
  );
}

export type AcceptOwnershipInput<
  TAccountNewAdmin extends string = string,
  TAccountPermissionConfig extends string = string,
> = {
  /** New admin (must be the pending_admin) */
  newAdmin: TransactionSigner<TAccountNewAdmin>;
  /** PermissionConfig PDA */
  permissionConfig: Address<TAccountPermissionConfig>;
};

export function getAcceptOwnershipInstruction<
  TAccountNewAdmin extends string,
  TAccountPermissionConfig extends string,
  TProgramAddress extends Address = typeof PERMISSION_MANAGER_PROGRAM_ADDRESS,
>(
  input: AcceptOwnershipInput<TAccountNewAdmin, TAccountPermissionConfig>,
  config?: { programAddress?: TProgramAddress },
): AcceptOwnershipInstruction<
  TProgramAddress,
  TAccountNewAdmin,
  TAccountPermissionConfig
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? PERMISSION_MANAGER_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    newAdmin: { value: input.newAdmin ?? null, isWritable: false },
    permissionConfig: {
      value: input.permissionConfig ?? null,
      isWritable: true,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.newAdmin),
      getAccountMeta(accounts.permissionConfig),
    ],
    data: getAcceptOwnershipInstructionDataEncoder().encode({}),
    programAddress,
  } as AcceptOwnershipInstruction<
    TProgramAddress,
    TAccountNewAdmin,
    TAccountPermissionConfig
  >);
}

export type ParsedAcceptOwnershipInstruction<
  TProgram extends string = typeof PERMISSION_MANAGER_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** New admin (must be the pending_admin) */
    newAdmin: TAccountMetas[0];
    /** PermissionConfig PDA */
    permissionConfig: TAccountMetas[1];
  };
  data: AcceptOwnershipInstructionData;
};

export function parseAcceptOwnershipInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedAcceptOwnershipInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      newAdmin: getNextAccount(),
      permissionConfig: getNextAccount(),
    },
    data: getAcceptOwnershipInstructionDataDecoder().decode(instruction.data),
  };
}
