/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { PERMISSION_MANAGER_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const GRANT_ROLE_DISCRIMINATOR = new Uint8Array([1]);

export function getGrantRoleDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 1).encode(GRANT_ROLE_DISCRIMINATOR);
}

export type GrantRoleInstruction<
  TProgram extends string = typeof PERMISSION_MANAGER_PROGRAM_ADDRESS,
  TAccountCaller extends string | AccountMeta<string> = string,
  TAccountPermissionConfig extends string | AccountMeta<string> = string,
  TAccountUserPermissions extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TAccountTargetUser extends string | AccountMeta<string> = string,
  TAccountCallerPermissions extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountCaller extends string
        ? WritableSignerAccount<TAccountCaller> &
            AccountSignerMeta<TAccountCaller>
        : TAccountCaller,
      TAccountPermissionConfig extends string
        ? ReadonlyAccount<TAccountPermissionConfig>
        : TAccountPermissionConfig,
      TAccountUserPermissions extends string
        ? WritableAccount<TAccountUserPermissions>
        : TAccountUserPermissions,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountTargetUser extends string
        ? ReadonlyAccount<TAccountTargetUser>
        : TAccountTargetUser,
      TAccountCallerPermissions extends string
        ? ReadonlyAccount<TAccountCallerPermissions>
        : TAccountCallerPermissions,
      ...TRemainingAccounts,
    ]
  >;

export type GrantRoleInstructionData = {
  discriminator: ReadonlyUint8Array;
  roleId: number;
};

export type GrantRoleInstructionDataArgs = { roleId: number };

export function getGrantRoleInstructionDataEncoder(): FixedSizeEncoder<GrantRoleInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 1)],
      ["roleId", getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: GRANT_ROLE_DISCRIMINATOR }),
  );
}

export function getGrantRoleInstructionDataDecoder(): FixedSizeDecoder<GrantRoleInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 1)],
    ["roleId", getU8Decoder()],
  ]);
}

export function getGrantRoleInstructionDataCodec(): FixedSizeCodec<
  GrantRoleInstructionDataArgs,
  GrantRoleInstructionData
> {
  return combineCodec(
    getGrantRoleInstructionDataEncoder(),
    getGrantRoleInstructionDataDecoder(),
  );
}

export type GrantRoleInput<
  TAccountCaller extends string = string,
  TAccountPermissionConfig extends string = string,
  TAccountUserPermissions extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTargetUser extends string = string,
  TAccountCallerPermissions extends string = string,
> = {
  /** Caller (payer if target PDA needs creation) */
  caller: TransactionSigner<TAccountCaller>;
  /** PermissionConfig PDA */
  permissionConfig: Address<TAccountPermissionConfig>;
  /** Target user's UserPermissions PDA (created if needed). Seeds: ["user_perm", target_user] */
  userPermissions: Address<TAccountUserPermissions>;
  systemProgram?: Address<TAccountSystemProgram>;
  /** Target user address (for PDA derivation) */
  targetUser: Address<TAccountTargetUser>;
  /** Caller's UserPermissions PDA (for role-hierarchy check) */
  callerPermissions: Address<TAccountCallerPermissions>;
  roleId: GrantRoleInstructionDataArgs["roleId"];
};

export function getGrantRoleInstruction<
  TAccountCaller extends string,
  TAccountPermissionConfig extends string,
  TAccountUserPermissions extends string,
  TAccountSystemProgram extends string,
  TAccountTargetUser extends string,
  TAccountCallerPermissions extends string,
  TProgramAddress extends Address = typeof PERMISSION_MANAGER_PROGRAM_ADDRESS,
>(
  input: GrantRoleInput<
    TAccountCaller,
    TAccountPermissionConfig,
    TAccountUserPermissions,
    TAccountSystemProgram,
    TAccountTargetUser,
    TAccountCallerPermissions
  >,
  config?: { programAddress?: TProgramAddress },
): GrantRoleInstruction<
  TProgramAddress,
  TAccountCaller,
  TAccountPermissionConfig,
  TAccountUserPermissions,
  TAccountSystemProgram,
  TAccountTargetUser,
  TAccountCallerPermissions
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? PERMISSION_MANAGER_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    caller: { value: input.caller ?? null, isWritable: true },
    permissionConfig: {
      value: input.permissionConfig ?? null,
      isWritable: false,
    },
    userPermissions: { value: input.userPermissions ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    targetUser: { value: input.targetUser ?? null, isWritable: false },
    callerPermissions: {
      value: input.callerPermissions ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.caller),
      getAccountMeta(accounts.permissionConfig),
      getAccountMeta(accounts.userPermissions),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.targetUser),
      getAccountMeta(accounts.callerPermissions),
    ],
    data: getGrantRoleInstructionDataEncoder().encode(
      args as GrantRoleInstructionDataArgs,
    ),
    programAddress,
  } as GrantRoleInstruction<
    TProgramAddress,
    TAccountCaller,
    TAccountPermissionConfig,
    TAccountUserPermissions,
    TAccountSystemProgram,
    TAccountTargetUser,
    TAccountCallerPermissions
  >);
}

export type ParsedGrantRoleInstruction<
  TProgram extends string = typeof PERMISSION_MANAGER_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Caller (payer if target PDA needs creation) */
    caller: TAccountMetas[0];
    /** PermissionConfig PDA */
    permissionConfig: TAccountMetas[1];
    /** Target user's UserPermissions PDA (created if needed). Seeds: ["user_perm", target_user] */
    userPermissions: TAccountMetas[2];
    systemProgram: TAccountMetas[3];
    /** Target user address (for PDA derivation) */
    targetUser: TAccountMetas[4];
    /** Caller's UserPermissions PDA (for role-hierarchy check) */
    callerPermissions: TAccountMetas[5];
  };
  data: GrantRoleInstructionData;
};

export function parseGrantRoleInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedGrantRoleInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 6) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      caller: getNextAccount(),
      permissionConfig: getNextAccount(),
      userPermissions: getNextAccount(),
      systemProgram: getNextAccount(),
      targetUser: getNextAccount(),
      callerPermissions: getNextAccount(),
    },
    data: getGrantRoleInstructionDataDecoder().decode(instruction.data),
  };
}
