/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import { PERMISSION_MANAGER_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const REVOKE_ROLE_DISCRIMINATOR = new Uint8Array([2]);

export function getRevokeRoleDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 1).encode(REVOKE_ROLE_DISCRIMINATOR);
}

export type RevokeRoleInstruction<
  TProgram extends string = typeof PERMISSION_MANAGER_PROGRAM_ADDRESS,
  TAccountCaller extends string | AccountMeta<string> = string,
  TAccountPermissionConfig extends string | AccountMeta<string> = string,
  TAccountUserPermissions extends string | AccountMeta<string> = string,
  TAccountTargetUser extends string | AccountMeta<string> = string,
  TAccountCallerPermissions extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountCaller extends string
        ? ReadonlySignerAccount<TAccountCaller> &
            AccountSignerMeta<TAccountCaller>
        : TAccountCaller,
      TAccountPermissionConfig extends string
        ? ReadonlyAccount<TAccountPermissionConfig>
        : TAccountPermissionConfig,
      TAccountUserPermissions extends string
        ? WritableAccount<TAccountUserPermissions>
        : TAccountUserPermissions,
      TAccountTargetUser extends string
        ? ReadonlyAccount<TAccountTargetUser>
        : TAccountTargetUser,
      TAccountCallerPermissions extends string
        ? ReadonlyAccount<TAccountCallerPermissions>
        : TAccountCallerPermissions,
      ...TRemainingAccounts,
    ]
  >;

export type RevokeRoleInstructionData = {
  discriminator: ReadonlyUint8Array;
  roleId: number;
};

export type RevokeRoleInstructionDataArgs = { roleId: number };

export function getRevokeRoleInstructionDataEncoder(): FixedSizeEncoder<RevokeRoleInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 1)],
      ["roleId", getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: REVOKE_ROLE_DISCRIMINATOR }),
  );
}

export function getRevokeRoleInstructionDataDecoder(): FixedSizeDecoder<RevokeRoleInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 1)],
    ["roleId", getU8Decoder()],
  ]);
}

export function getRevokeRoleInstructionDataCodec(): FixedSizeCodec<
  RevokeRoleInstructionDataArgs,
  RevokeRoleInstructionData
> {
  return combineCodec(
    getRevokeRoleInstructionDataEncoder(),
    getRevokeRoleInstructionDataDecoder(),
  );
}

export type RevokeRoleInput<
  TAccountCaller extends string = string,
  TAccountPermissionConfig extends string = string,
  TAccountUserPermissions extends string = string,
  TAccountTargetUser extends string = string,
  TAccountCallerPermissions extends string = string,
> = {
  /** Caller */
  caller: TransactionSigner<TAccountCaller>;
  /** PermissionConfig PDA */
  permissionConfig: Address<TAccountPermissionConfig>;
  /** Target user's UserPermissions PDA */
  userPermissions: Address<TAccountUserPermissions>;
  /** Target user address (for PDA derivation) */
  targetUser: Address<TAccountTargetUser>;
  /** Caller's UserPermissions PDA (for role-hierarchy check) */
  callerPermissions: Address<TAccountCallerPermissions>;
  roleId: RevokeRoleInstructionDataArgs["roleId"];
};

export function getRevokeRoleInstruction<
  TAccountCaller extends string,
  TAccountPermissionConfig extends string,
  TAccountUserPermissions extends string,
  TAccountTargetUser extends string,
  TAccountCallerPermissions extends string,
  TProgramAddress extends Address = typeof PERMISSION_MANAGER_PROGRAM_ADDRESS,
>(
  input: RevokeRoleInput<
    TAccountCaller,
    TAccountPermissionConfig,
    TAccountUserPermissions,
    TAccountTargetUser,
    TAccountCallerPermissions
  >,
  config?: { programAddress?: TProgramAddress },
): RevokeRoleInstruction<
  TProgramAddress,
  TAccountCaller,
  TAccountPermissionConfig,
  TAccountUserPermissions,
  TAccountTargetUser,
  TAccountCallerPermissions
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? PERMISSION_MANAGER_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    caller: { value: input.caller ?? null, isWritable: false },
    permissionConfig: {
      value: input.permissionConfig ?? null,
      isWritable: false,
    },
    userPermissions: { value: input.userPermissions ?? null, isWritable: true },
    targetUser: { value: input.targetUser ?? null, isWritable: false },
    callerPermissions: {
      value: input.callerPermissions ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.caller),
      getAccountMeta(accounts.permissionConfig),
      getAccountMeta(accounts.userPermissions),
      getAccountMeta(accounts.targetUser),
      getAccountMeta(accounts.callerPermissions),
    ],
    data: getRevokeRoleInstructionDataEncoder().encode(
      args as RevokeRoleInstructionDataArgs,
    ),
    programAddress,
  } as RevokeRoleInstruction<
    TProgramAddress,
    TAccountCaller,
    TAccountPermissionConfig,
    TAccountUserPermissions,
    TAccountTargetUser,
    TAccountCallerPermissions
  >);
}

export type ParsedRevokeRoleInstruction<
  TProgram extends string = typeof PERMISSION_MANAGER_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Caller */
    caller: TAccountMetas[0];
    /** PermissionConfig PDA */
    permissionConfig: TAccountMetas[1];
    /** Target user's UserPermissions PDA */
    userPermissions: TAccountMetas[2];
    /** Target user address (for PDA derivation) */
    targetUser: TAccountMetas[3];
    /** Caller's UserPermissions PDA (for role-hierarchy check) */
    callerPermissions: TAccountMetas[4];
  };
  data: RevokeRoleInstructionData;
};

export function parseRevokeRoleInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedRevokeRoleInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      caller: getNextAccount(),
      permissionConfig: getNextAccount(),
      userPermissions: getNextAccount(),
      targetUser: getNextAccount(),
      callerPermissions: getNextAccount(),
    },
    data: getRevokeRoleInstructionDataDecoder().decode(instruction.data),
  };
}
