/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import { PERMISSION_MANAGER_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const TRANSFER_OWNERSHIP_DISCRIMINATOR = new Uint8Array([3]);

export function getTransferOwnershipDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 1).encode(
    TRANSFER_OWNERSHIP_DISCRIMINATOR,
  );
}

export type TransferOwnershipInstruction<
  TProgram extends string = typeof PERMISSION_MANAGER_PROGRAM_ADDRESS,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountPermissionConfig extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? ReadonlySignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountPermissionConfig extends string
        ? WritableAccount<TAccountPermissionConfig>
        : TAccountPermissionConfig,
      ...TRemainingAccounts,
    ]
  >;

export type TransferOwnershipInstructionData = {
  discriminator: ReadonlyUint8Array;
  newAdmin: Address;
};

export type TransferOwnershipInstructionDataArgs = { newAdmin: Address };

export function getTransferOwnershipInstructionDataEncoder(): FixedSizeEncoder<TransferOwnershipInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 1)],
      ["newAdmin", getAddressEncoder()],
    ]),
    (value) => ({ ...value, discriminator: TRANSFER_OWNERSHIP_DISCRIMINATOR }),
  );
}

export function getTransferOwnershipInstructionDataDecoder(): FixedSizeDecoder<TransferOwnershipInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 1)],
    ["newAdmin", getAddressDecoder()],
  ]);
}

export function getTransferOwnershipInstructionDataCodec(): FixedSizeCodec<
  TransferOwnershipInstructionDataArgs,
  TransferOwnershipInstructionData
> {
  return combineCodec(
    getTransferOwnershipInstructionDataEncoder(),
    getTransferOwnershipInstructionDataDecoder(),
  );
}

export type TransferOwnershipInput<
  TAccountAdmin extends string = string,
  TAccountPermissionConfig extends string = string,
> = {
  /** Current admin */
  admin: TransactionSigner<TAccountAdmin>;
  /** PermissionConfig PDA */
  permissionConfig: Address<TAccountPermissionConfig>;
  newAdmin: TransferOwnershipInstructionDataArgs["newAdmin"];
};

export function getTransferOwnershipInstruction<
  TAccountAdmin extends string,
  TAccountPermissionConfig extends string,
  TProgramAddress extends Address = typeof PERMISSION_MANAGER_PROGRAM_ADDRESS,
>(
  input: TransferOwnershipInput<TAccountAdmin, TAccountPermissionConfig>,
  config?: { programAddress?: TProgramAddress },
): TransferOwnershipInstruction<
  TProgramAddress,
  TAccountAdmin,
  TAccountPermissionConfig
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? PERMISSION_MANAGER_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: false },
    permissionConfig: {
      value: input.permissionConfig ?? null,
      isWritable: true,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.admin),
      getAccountMeta(accounts.permissionConfig),
    ],
    data: getTransferOwnershipInstructionDataEncoder().encode(
      args as TransferOwnershipInstructionDataArgs,
    ),
    programAddress,
  } as TransferOwnershipInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountPermissionConfig
  >);
}

export type ParsedTransferOwnershipInstruction<
  TProgram extends string = typeof PERMISSION_MANAGER_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Current admin */
    admin: TAccountMetas[0];
    /** PermissionConfig PDA */
    permissionConfig: TAccountMetas[1];
  };
  data: TransferOwnershipInstructionData;
};

export function parseTransferOwnershipInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedTransferOwnershipInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { admin: getNextAccount(), permissionConfig: getNextAccount() },
    data: getTransferOwnershipInstructionDataDecoder().decode(instruction.data),
  };
}
