/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertIsInstructionWithAccounts,
  containsBytes,
  fixEncoderSize,
  getBytesEncoder,
  type Address,
  type Instruction,
  type InstructionWithData,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  parseCancelRedemptionInstruction,
  parseExecuteRedemptionInstruction,
  parseInitializeRedemptionInstruction,
  parseOnRedeemInstruction,
  parseSetMinimumInstruction,
  type ParsedCancelRedemptionInstruction,
  type ParsedExecuteRedemptionInstruction,
  type ParsedInitializeRedemptionInstruction,
  type ParsedOnRedeemInstruction,
  type ParsedSetMinimumInstruction,
} from "../instructions";

export const REDEMPTION_PROGRAM_ADDRESS =
  "GZEFPC74n1ifKrsH9vh67qntZ8bqpzpdDrBasGVCUPPo" as Address<"GZEFPC74n1ifKrsH9vh67qntZ8bqpzpdDrBasGVCUPPo">;

export enum RedemptionAccount {
  RedemptionConfig,
  TokenMinimum,
  RedemptionOperation,
}

export function identifyRedemptionAccount(
  account: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): RedemptionAccount {
  const data = "data" in account ? account.data : account;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 1).encode(new Uint8Array([1])),
      0,
    )
  ) {
    return RedemptionAccount.RedemptionConfig;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 1).encode(new Uint8Array([2])),
      0,
    )
  ) {
    return RedemptionAccount.TokenMinimum;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 1).encode(new Uint8Array([4])),
      0,
    )
  ) {
    return RedemptionAccount.RedemptionOperation;
  }
  throw new Error(
    "The provided account could not be identified as a redemption account.",
  );
}

export enum RedemptionInstruction {
  InitializeRedemption,
  ExecuteRedemption,
  CancelRedemption,
  SetMinimum,
  OnRedeem,
}

export function identifyRedemptionInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): RedemptionInstruction {
  const data = "data" in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 1).encode(new Uint8Array([0])),
      0,
    )
  ) {
    return RedemptionInstruction.InitializeRedemption;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 1).encode(new Uint8Array([1])),
      0,
    )
  ) {
    return RedemptionInstruction.ExecuteRedemption;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 1).encode(new Uint8Array([2])),
      0,
    )
  ) {
    return RedemptionInstruction.CancelRedemption;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 1).encode(new Uint8Array([3])),
      0,
    )
  ) {
    return RedemptionInstruction.SetMinimum;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 1).encode(new Uint8Array([4])),
      0,
    )
  ) {
    return RedemptionInstruction.OnRedeem;
  }
  throw new Error(
    "The provided instruction could not be identified as a redemption instruction.",
  );
}

export type ParsedRedemptionInstruction<
  TProgram extends string = "GZEFPC74n1ifKrsH9vh67qntZ8bqpzpdDrBasGVCUPPo",
> =
  | ({
      instructionType: RedemptionInstruction.InitializeRedemption;
    } & ParsedInitializeRedemptionInstruction<TProgram>)
  | ({
      instructionType: RedemptionInstruction.ExecuteRedemption;
    } & ParsedExecuteRedemptionInstruction<TProgram>)
  | ({
      instructionType: RedemptionInstruction.CancelRedemption;
    } & ParsedCancelRedemptionInstruction<TProgram>)
  | ({
      instructionType: RedemptionInstruction.SetMinimum;
    } & ParsedSetMinimumInstruction<TProgram>)
  | ({
      instructionType: RedemptionInstruction.OnRedeem;
    } & ParsedOnRedeemInstruction<TProgram>);

export function parseRedemptionInstruction<TProgram extends string>(
  instruction: Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array>,
): ParsedRedemptionInstruction<TProgram> {
  const instructionType = identifyRedemptionInstruction(instruction);
  switch (instructionType) {
    case RedemptionInstruction.InitializeRedemption: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: RedemptionInstruction.InitializeRedemption,
        ...parseInitializeRedemptionInstruction(instruction),
      };
    }
    case RedemptionInstruction.ExecuteRedemption: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: RedemptionInstruction.ExecuteRedemption,
        ...parseExecuteRedemptionInstruction(instruction),
      };
    }
    case RedemptionInstruction.CancelRedemption: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: RedemptionInstruction.CancelRedemption,
        ...parseCancelRedemptionInstruction(instruction),
      };
    }
    case RedemptionInstruction.SetMinimum: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: RedemptionInstruction.SetMinimum,
        ...parseSetMinimumInstruction(instruction),
      };
    }
    case RedemptionInstruction.OnRedeem: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: RedemptionInstruction.OnRedeem,
        ...parseOnRedeemInstruction(instruction),
      };
    }
    default:
      throw new Error(
        `Unrecognized instruction type: ${instructionType as string}`,
      );
  }
}
